### ISSUE TITLE
content vertical align not working for some layouts

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1000]
content vertical align is not working in

1. Heading
2. Heading 2
3. Faded layout

add a number box block
set layout to faded
Advanced > Column / Container spacing
set _min column height_ = 500
set content vertical align to _align center / align bottom_

the number does not align together with the title & description

![image](https://user-images.githubusercontent.com/28699204/101320399-a807be00-389e-11eb-8767-aaf4b809041c.png)

**Comment by blankart** [comment]
Background, Heading, Heading 2, and Faded Layouts use `position: absolute` to number boxes So it should not be affected by vertical alignment.
