### ISSUE TITLE
title is not present in Header block attributes

### ISSUE THREAD

**Issue by squibbleFish** [gambitph/Stackable#1004]
**Describe the bug**
I am using this through a headless CMS. From the most recent update, the `title` attribute is no longer present in the `attributes` object of the header block

**Screenshots**
The `title` attribute should be present in the `attributes` object

**Comment by bfintal** [comment]
@squibbleFish can you provide any more information about this? Is this the only block where this happens? Since the last update, there wasn't anything changed from the Header block, aside from the attributes being separated into another file `schema.js`
