### ISSUE TITLE
Columns on mobile

### ISSUE THREAD

**Issue by ivan-vilches** [gambitph/Stackable#1010]
Hello i am using free version of stackable , i want display a section with “our clients” this section will have on desktop 3 rows with 6 colums each row, inside of each column am gonna put just text the name of the company.
I want display the same 3 rows with 6 columns (maybe 3 columns) on mobile and tablet too.
The default behavier is show me one column on Mobile.
It is possible 
Thanks you very much

**Comment by blankart** [comment]
Hi @ivan-vilches , we are closing this since it will be addressed by Stackable v3 blocks.
