### ISSUE TITLE
Uncaught type error in Oxygen Builder

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#1012]
Reported in a support ticket:
> I'm seeing this error message when I open Oxygen Builder. I can dismiss the error message and things work fine:
>
> Uncaught TypeError: Illegal invocation on line #1 in stackable-ultimate-gutenberg-blocks-premium/dist/frontend_blocks.js?ver=2.13.2

**Comment by blankart** [comment]
Already resolved.
