### ISSUE TITLE
Google font messed if Global Font Family is not set

### ISSUE THREAD

**Issue by rsm0128** [gambitph/Stackable#1019]
If Font Family is not set for Global Setting, it enqueues empty string as Google font, and it makes all google font messed.
Should add a line to the [/src/fonts.php line 92](https://github.com/gambitph/Stackable/blob/5bb5cf8552812de385980a06faa233ff1e218578/src/fonts.php#L92)
`foreach ( $google_fonts as &$font ) {
				if (empty($font)) continue;
				$font = str_replace( ' ', '+', $font ) . ':100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic';
			}`

**Comment by bfintal** [comment]
Thanks for the report and PR

**Comment by rsm0128** [comment]
My pleasure!
