### ISSUE TITLE
Accordion Block: Text overlaps other content in backend

### ISSUE THREAD

**Issue by bbdf-design** [gambitph/Stackable#102]
Hello, I described this bug in an already opened bug (Accordion Block: Text overlaps other content). But I'm not sure, if you've seen it, so I'll add it here again (sorry for posting it twice, if you've seen the other one already):

**Describe the bug**
If you have a longer content in accordion in the backend, it will overlap following blocks and it is difficult to work with the (overflowing) text added to the accordion-block. (The accordion closes on its own, when using the keyboard to move down in the overflowing text.)

**To Reproduce**

    Make an accordion with longer text
    Put any content below and see the accordion overlaping its border and the following content.
    Use the keyboard to move down in the text and see the accordion closing itself.

**Expected behavior**
The accordion text shouldn't overlap the next contents and the accordion shouldn't close by itself.

**Screenshots**
![overlaping accordion in backend](https://user-images.githubusercontent.com/50144872/57231836-a8353d00-701b-11e9-9b73-182ee14215f2.JPG)
.

**Desktop**
 - OS: Windows
 - Browser:  Chrome, Firefox
 - Browser Version: latest

Would be really glad, if you could help. Perhaps with a temporary fix?
Thanks and best regards
Eva

**Comment by bbdf-design** [comment]
I've seen you fixed the issue in the new version. Thanks a lot for this :-)!

**Comment by bfintal** [comment]
No problem!
