### ISSUE TITLE
Load more button panel is missing

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1021]
The Load More button panel in Blog Posts is missing in Premium version

![image](https://user-images.githubusercontent.com/28699204/104868120-7bef5a80-597d-11eb-8a52-549bb4e10c11.PNG)

**Comment by blankart** [comment]
What version are you using? I can't reproduce the issue

**Comment by legaspielaine** [comment]
> What version are you using? I can't reproduce the issue

v2.13.3 and WP v5.6
I used both sandbox and local to test and same issue for both

**Comment by blankart** [comment]
Make sure that you already activated the premium features

**Comment by legaspielaine** [comment]
> Make sure that you already activated the premium features

ok i tested it in my local again and it's showing already. will close this
