### ISSUE TITLE
Header Block: Empty Header block Height in mobile

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#106]
**Describe the bug**
Empty Header blocks look too small in mobile.

**To Reproduce**
1. Create a Header Block
2. Delete all the texts including the buttons
3. Save and View the page in mobile or smaller screen sizes

**Expected behavior**
The height should be relative to the desktop size and is responsive.
Adding height option for Header is also recommended.

**Screenshots**
![image](https://user-images.githubusercontent.com/11436202/57917750-e78b4580-78c7-11e9-9b01-9381f3a8a0ae.png)

**Comment by bfintal** [comment]
For mobile, the Header block doesn't impose any height styles and just follows the content it has. If there are no contents, then I'd expect the block to look like that. I don't think this is an issue.
