### ISSUE TITLE
UI bug on Column / Container Spacing

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1067]
When the Column / Container Spacing panel is collapsed on tablet and mobile mode,
the current viewport is not selected anymore in Column / Container Spacing.

Steps to reproduce:
1. Add a Card block
2. Go to Advanced tab - and collapse Block Spacing panel
3. Change Preview Mode to tablet or mobile
4. Collapse Column/Container Spacing - see bug

https://user-images.githubusercontent.com/28699204/108828547-f442de80-7601-11eb-8598-d7cba319858c.mov

**Comment by bfintal** [comment]
This is already addressed in v3. When v3 gets released, v2 should be fixed as well.
