### ISSUE TITLE
Tooltips for style tab not showing video

### ISSUE THREAD

**Issue by acostacos** [gambitph/Stackable#1081]
Tooltips in styles tab do not display the video for visual reference. Expected behavior is for it to automatically when you hover.

1. Create any Stackable block
2. Navigate to styles tab
3. Hover over tooltip and see that video doesn't show
4. Show to console to see error

Screenshots:
![firefox_DHcMkkVOuX](https://user-images.githubusercontent.com/33932255/109927761-a6b02b00-7cff-11eb-9f04-ab5bdc5e21c3.png)

**Comment by blankart** [comment]
What browser are you using?

**Comment by bfintal** [comment]
I cannot also reproduce this issue in the sandbox
