### ISSUE TITLE
Blockquote block shows a different font weight in front end when set to default

### ISSUE THREAD

**Issue by acostacos** [gambitph/Stackable#1082]
When font weight is set to default, it becomes greater when it is shown in the front end. Expected behavior is for the font weight in the front end and back end to be the same.

1. Create blockquote block
2. By default, the font weight should be set to "Default"
3. Switch to front end and compare font weight with back end

Screenshots:
![firefox_nwRobvk95A](https://user-images.githubusercontent.com/33932255/109929365-53d77300-7d01-11eb-8c3e-a7e5520ff698.png)

**Comment by bfintal** [comment]
This is just a minor issue, I think we can set this to won't fix since v3 would drastically change how the blockquote block works.
