### ISSUE TITLE
Blog Posts showing duplicate entry in backend

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1083]
When adding a blog post block and setting the Specific Post IDs, the results in backend shows duplicate entries of specific posts.
1. Add a new post
2. in a new page, add a Posts block
3. In the Display specific post IDs, enter the Post ID of the newly created post
4. see bug in backend

https://user-images.githubusercontent.com/28699204/109940191-c39f2b00-7d0c-11eb-9fbf-7365361fbbe6.mov

**Comment by blankart** [comment]
There's a bug when fetching gutenberg's `getEntityRecords` 
![image](https://user-images.githubusercontent.com/24480990/110052987-7914c180-7d93-11eb-9251-352dacc799e6.png)

Debouncing the post query results might solve the issue
