### ISSUE TITLE
UI bug on Global Settings when changing the Heading sizes

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1085]
I get the following bug when I'm changing the heading size on Global Settings using range control.
video snippet:

https://user-images.githubusercontent.com/28699204/110050255-83808c80-7d8e-11eb-93bf-52383f032dc9.mov

Steps:
1. Go to Stackable Global settings
2. click Heading 4 popover
3. adjust the size to 30 using the range control
4. see bug

**Comment by blankart** [comment]
Please specify how to reproduce the issue

**Comment by legaspielaine** [comment]
> Please specify how to reproduce the issue

updated the issue with steps. Please check

**Comment by blankart** [comment]
I can't reproduce the issue

**Comment by legaspielaine** [comment]
> I can't reproduce the issue

It happens on Chrome, Safari, firefox & edge for me
the range control is snapping at different points

https://user-images.githubusercontent.com/28699204/110089686-5d301080-7dd1-11eb-8186-f5965a3fd6d4.mov

**Comment by blankart** [comment]
Can you ask @acostacos to reproduce the issue also?

**Comment by legaspielaine** [comment]
closing this issue as it happens only on my machine
