### ISSUE TITLE
Textbox input for RGB and HSL custom colors do not register changes for new blocks

### ISSUE THREAD

**Issue by acostacos** [gambitph/Stackable#1089]
When I use the RGB and HSL textboxes for custom colors, the values revert back to 0 after I input it. This only happens for newly made blocks. 

Steps to reproduce:
1. Create an accordion block
2. Navigate to styles tab and change title color
3. Assign a custom color and use the RGB / HSL textboxes
4. See how values revert back to 0 and changes are not saved

Screen Recording:

https://user-images.githubusercontent.com/33932255/110066477-7f636780-7dac-11eb-82ac-1708932a9c46.mp4

**Comment by blankart** [comment]
I can't reproduce the issue. What browser did you use?

**Comment by acostacos** [comment]
I used Chrome for testing
