### ISSUE TITLE
Invalid Content error on certain blocks when you add a Custom CSS

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#109]
**Describe the bug**
Adding a Custom CSS on Image Box, Feature Grid, Testimonial, Number Box, Pricing Box or Team Member blocks ruins the styling and causes _Invalid Content error_ when you edit the page.

**To Reproduce**
1. Add any of the blocks mentioned
2. Add Custom CSS via **Custom CSS** tab
3. Notice that the entire styling from the block has changed, some even break
4. Save the page and edit again, the Invalid Content error should appear

**Expected behavior**
The Custom CSS should only change the specific area and as intended from the styling rule

**Screenshots**
![image](https://user-images.githubusercontent.com/11436202/58014179-cc6c4000-7b2a-11e9-810e-da448d0724bc.png)

**Comment by bfintal** [comment]
Fixed by 85c9dca56dc7ba8ef70c7244fa5e04371b590494
