### ISSUE TITLE
Advanced panel keeps showing under Style tab of Columns block

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1091]
When you add a Columns block, deselect then select it again, the Advanced panel keeps showing under Style tab as well.
It disappears when you switch tabs, but keep showing when you deselect then select the Columns block again

see video below:

https://user-images.githubusercontent.com/28699204/110078304-84cbac80-7dc2-11eb-9ce0-2c6f43a48c15.mov

**Comment by blankart** [comment]
I think we won't fix this for now. Advanced option is not part of Stackable modules.

**Comment by bfintal** [comment]
Please confirm if this is still happening, we hide the advanced panel if the current tab selected isn't the advanced tab.

**Comment by blankart** [comment]
This still happens when selecting from advanced column to advanced columns

**Comment by bfintal** [comment]
The issue seems to be coming from the `.component-panel` not getting the correct data attribute `data-ugb-tab="style"` when selecting from advanced column to advanced columns. When you select a Stackable block, a `data-ugb-tab` attribute should be added.
