### ISSUE TITLE
Updating failed

### ISSUE THREAD

**Issue by Whyath** [gambitph/Stackable#110]
Using Stackable for the first time on our live site and when implementing a Stackable Card block, as soon as we insert an image, the post will not save or preview. An error message comes up saying 'Updating Failed'.

Have loaded a screenshot showing the error. 

Gutenberg blocks work without stackable plug-in just fine.

Using a macbook pro, and have tried on Safari, Firefox and Chrome same issue.

<img width="1263" alt="Screen Shot 2019-05-20 at 4 15 29 pm" src="https://user-images.githubusercontent.com/50833544/58024401-c0788200-7b1a-11e9-8df5-dfe891b44f6b.png">

Any advice would be appreciated because the plug-in looks superb but can't assess whether we want to upgrade until it works properly.

**Comment by Gambit-Alyssa** [comment]
Hi there! 🙂

This issue doesn't happen in our end. It may be possible that a certain plugin or theme might be also causing the issue. You can check on these:

1. Are you able to create the Card Block in **Pages** (instead of your Events post type)?

2. It's possible that deactivating your other plugins may address the issue. You can temporarily deactivate plugins or change to one of the default themes so that we can narrow down if the issue may be a conflict. If deactivating a certain plugin addressed the problem, please let us know about the plugin so that we can test it out.

**Comment by Whyath** [comment]
Hi Alyssa,

Thank you for your email. 

Attached is a screenshot of the console error. Maybe it relates to the TinyMCE plug-in?
<img width="1271" alt="Screen Shot 2019-05-21 at 2 47 08 pm" src="https://user-images.githubusercontent.com/50833544/58094072-7b1a8a00-7bd8-11e9-8fc5-030a18bf653e.png">

I also deactivated the Stackable plug-in to see what effect it had, if any, on other plug-ins for Gutenberg. Another block plug-in came up with this error as follows:
<img width="1272" alt="Screen Shot 2019-05-21 at 1 11 48 pm" src="https://user-images.githubusercontent.com/50833544/58094182-b452fa00-7bd8-11e9-9757-76170409bfbf.png">
Not sure if this has any relation to what could be conflicting with Stackable.

Otherwise everything is identical on the staging site to the live site in terms of theme and plugins. Just that the live site is continuing to get the error.

Thank you for your help.

Michael

**Comment by Whyath** [comment]
Alyssa,

i forgot to answer the rest of your question. We did try and create a regular post and page and the same error message came up. So it is not limited to Event posts.

Thanks,

Michael

**Comment by Whyath** [comment]
Further debugging this issue: It seems that we can save and update the post using a Stackable Card as long as there is no image attached. As soon as you load an image to the Stackable Card, the post is unable to update. Note sure if this helps establish what the problem may be?

**Comment by yssagambit** [comment]
This should have been fixed on V2. Closing this, but please reopen if you still encounter the error after updating to V2.
