### ISSUE TITLE
block error on accordion when editing as html

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1108]
1. in a new page, add an accordion block
2. in its toolbar, click options > edit as Html
3. click the options button again - see error

<img width="963" alt="Screen Shot 2021-03-15 at 2 56 31 PM" src="https://user-images.githubusercontent.com/28699204/111114762-abe26500-859e-11eb-9b87-da125a257163.png">

**Comment by blankart** [comment]
please provide a screenshot of your console

**Comment by legaspielaine** [comment]
> please provide a screenshot of your console

<img width="378" alt="Screen Shot 2021-03-15 at 3 10 07 PM" src="https://user-images.githubusercontent.com/28699204/111116151-8e15ff80-85a0-11eb-819c-d458f864fd74.png">
