### ISSUE TITLE
min-height property in Image box block does not reflect in mobile mode

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1110]
When i change the Height in Style tab > General panel of Image Box block, the min-height does not reflect in `.ugb-image-box__item` when in Mobile mode.

Steps:
1. add an image box block
2. Go to Style > General
3. Change viewport to Mobile - adjust Height to 273
4. see bug - the `height` changes, but the `min-height` does not reflect in `.ugb-image-box__item` like in Tablet or Desktop mode

<img width="1326" alt="Screen Shot 2021-03-18 at 12 02 59 PM" src="https://user-images.githubusercontent.com/28699204/111571542-e38d1f00-87e1-11eb-8fb2-b0f76fb7a83d.png">

**Comment by blankart** [comment]
We need to remove the min-height assertion in our e2e test.
