### ISSUE TITLE
contents of advanced text not being displayed in get_the_excerpt()

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1123]
steps to reproduce:
1. in your site, add a new post
2. inside that post, add a native paragraph and an advanced text
3. save and publish
4. take note of its post id
5. open the content-page.php of your site's active theme inside `Local Sites/.../themes/theme-name/template-parts/content/` and add the following code at the last part:
change the post id - use the one from # 4
```
Test text
<?php
$excerpt = get_the_excerpt(post-id-here);
echo "<h2> Excerpt start: " . $excerpt . "</h2>"; ?>
```
6. In your site, open a page and view this in frontend - the advanced text is not being displayed

**Comment by blankart** [comment]
Ticket tracker: https://core.trac.wordpress.org/ticket/47637

Related issues:
https://github.com/godaddy-wordpress/coblocks/issues/735
https://github.com/WordPress/gutenberg/issues/17078
