### ISSUE TITLE
Page not found - Stackable settings link to docs

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1125]
Some of the links inside the Stackable settings page & welcome page are not working:
https://user-images.githubusercontent.com/28699204/112966171-8cd9fa80-917c-11eb-9ce6-58e717faa66a.mov

- All links inside the plugin that redirect to docs.wpstackable are returning `Page Not Found`
- Need to update all "Learn More" links inside the plugin, such as:

<img width="295" alt="Screen Shot 2021-03-31 at 11 44 07 AM" src="https://user-images.githubusercontent.com/28699204/113087721-d24b0600-9216-11eb-968d-febbb3226a73.png">

**Comment by legaspielaine** [comment]
List of links returning `Page Not Found`: (Check for updates)
- `Read full guide` in Welcome page: https://docs.wpstackable.com/stackable-guides/beginner-guides/customizing-blocks?utm_source=wp-getting-started-footer&utm_campaign=getting-started&utm_medium=wp-dashboard
-

**Comment by blankart** [comment]
Resolved by: https://github.com/gambitph/Stackable/pull/1203
