### ISSUE TITLE
"This block has encountered an error and cannot be previewed" 

### ISSUE THREAD

**Issue by TheShadowZone12** [gambitph/Stackable#1126]
Me and my team have run into this problem recently and cannot edit or move forward with any of our projects until we get this figured out.

This is what we see when we simply click on a Stackable Block to edit it on the backend, then we can't edit or do anything with it.
![Screenshot 2021-03-31 084950](https://user-images.githubusercontent.com/8580265/113158682-9ce7ed80-9201-11eb-9707-436ac69f138d.png)

As far as I can tell, it's only happening with Stackable blocks, no other blocks are affected.

**System:**
WordPress Version | 5.6.2
Storefront-child | by Automattic - 2.4.2 
Storefront (Parent) | by Automattic - 3.4.0 
Gutenberg | by Gutenberg Team - 10.2.1
Stackable - Gutenberg Blocks | by Gambit Technologies, Inc - 2.14.1
PHP Version | 7.4.11

If any further information is necessary, I will do my best to provide as much information as I can.

Thank you in advance.

**Comment by blankart** [comment]
Thank you for the report @TheShadowZone12 . 

Have you tried disabling the Gutenberg plugin?
