### ISSUE TITLE
Youtube videos don't autoplay in video-popup

### ISSUE THREAD

**Issue by ckiehl** [gambitph/Stackable#113]
Hi,

I when trialing Stackable blocks I noticed that Youtube videos in the "video popup" block don't autoplay. I had a quick look and it seems that this is due to a bug in BigPicture: https://github.com/henrygd/bigpicture/commit/50f40b658900ac8baa76903f4442b0d4304b4623

Any chance you could upgrade to a recent version of BigPicture to get autoplay working?

**Comment by bfintal** [comment]
Tested it as well :) Thanks for the report 👍

**Comment by bfintal** [comment]
Out in v1.15.4

**Comment by ckiehl** [comment]
Just upgraded and can confirm that it's fixed! Thanks @bfintal for the quick response.
