### ISSUE TITLE
Posts Block: Pagination

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#114]
**Is your feature request related to a problem? Please describe.**
I want to include a lot of entries for Posts Block, but I don't want it to look "too long".

**Describe the solution you'd like**
Add pagination for posts block and a capability to choose a number of posts per page.

**Comment by jeffreynolte** [comment]
+1 on this

**Comment by nickwinder** [comment]
+1 also!

**Comment by Holyphoenix** [comment]
+1
