### ISSUE TITLE
Adding a dynamic field that's shown as link inside buttons messes up in frontend

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1144]
Steps
1. Add a dynamic field that is shown as link inside a button.
2. see bug in frontend

in backend it looks like:
<img width="679" alt="Screen Shot 2021-04-28 at 9 59 44 AM" src="https://user-images.githubusercontent.com/28699204/116334842-77ea9880-a808-11eb-8be5-5c1224ed0a26.png">

in frontend:
<img width="679" alt="Screen Shot 2021-04-28 at 10 00 46 AM" src="https://user-images.githubusercontent.com/28699204/116334927-9badde80-a808-11eb-9d2d-c71c7d86e366.png">

**Comment by bfintal** [comment]
Please note that the style of the link is okay, our issue lang is that the link goes outside the button.

@blankart I think this will be fixed with the `<span>` and `</span>` detection you're doing

**Comment by legaspielaine** [comment]
> Please note that the style of the link is okay, our issue lang is that the link goes outside the button.
> 
> @blankart I think this will be fixed with the `<span>` and `</span>` detection you're doing

the style of the dynamic link does not change when I adjust the button options. But if it's only a dynamic text inside that button, it changes.

Also noting that I'm getting a block error on this when saving then refreshing the editor (after adding the dynamic link inside the button):
<img width="1462" alt="Screen Shot 2021-04-28 at 12 27 54 PM" src="https://user-images.githubusercontent.com/28699204/116346597-2ac4f180-a81d-11eb-81c3-c4b3322810d7.png">

**Comment by blankart** [comment]
I think it has something to do with our `render_block` filter.

Upon checking the function, the `$block_content` was properly parsed. Sample block content  snipped below:


```php
// $block_content 
'<a class="ugb-button ugb-button--size-normal" href="" rel="" title="">
   <span class="ugb-button--inner">
      <a href="http://stackable.local/784-2/" target="_blank" rel="noreferrer noopener">
          TEST
      </a>    
   </span>
</a>'
```

But this markup was rendered:
```php
'<a class="ugb-button ugb-button--size-normal" href="" rel="" title="">
   <span class="ugb-button--inner">        
   </span>
</a>
<a href="http://stackable.local/784-2/" target="_blank" rel="noreferrer noopener">
   TEST
</a> '
```
