### ISSUE TITLE
Dynamic popover not showing when dynamic content is added on a new line

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1148]
when you type a text then click enter, if you try to add a new dynamic content in that new line, the dynamic popover is not showing anymore when you click the content.

Steps:
1. add a text block
2. type something and press enter
3. insert a new dynamic content below. click Apply
4. select the added dynamic content - popover is not showing up

**Comment by bfintal** [comment]
For me, this happens when I select "post type", then apply, click on the dynamic content, select "post status", then apply. Now you have to click on the dynamic content 3 times for the popover to appear.

**Comment by legaspielaine** [comment]
This is what happens with mine:
the popover is not showing up no matter how many times you click the content:

https://user-images.githubusercontent.com/28699204/116496258-3a087580-a8d7-11eb-88f8-50b8bcc0d5d1.mov
