### ISSUE TITLE
Slider Block

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#115]
**What is the purpose of the block? Please describe.**
A slider for images and other contents similar to Carousel.

**Describe ways how the block will be used**
I want to add any content in a slider that will rotate them in the same container.

**Who is the block for?**
Definitely applicable to many range users: bloggers, artists, advertisers, business, etc.

**Comment by yssagambit** [comment]
Duplicate [#179 ](https://github.com/gambitph/Stackable/issues/179)
