### ISSUE TITLE
when toggle is clicked, the Popover moves up/down: Site > Site URL > show as link

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1165]
pls see vid:
https://user-images.githubusercontent.com/28699204/116519058-984b4d80-a903-11eb-88fe-8ffc65d237b4.mov

**Comment by blankart** [comment]
This isn't a bug. This is how gutenberg handles popover's position when its height does not fit between the anchor element to the bottom of the screen.
