### ISSUE TITLE
I want to use a custom icon for the icon list

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#118]
**T#8829**

**Is your feature request related to a problem? Please describe.**
I want to use a custom icon for icon list, this will be possibly useful with other blocks that uses icons too.

**Describe the solution you'd like**
Allow uploading custom icons or SVG fields to add your own icons. Add a favorite or custom icon picker for the icons.

**Comment by jrgong420** [comment]
+1 for this! It would be already helpful to have the full choice for icons

**Comment by blankart** [comment]
Already implemented
