### ISSUE TITLE
Blue pagination button, text blended with the button

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#1180]
I have Twenty Twenty One, I added a new page with a blog posts block. I turned on pagination and hit preview. Here's what I see in the frontend:

![image](https://user-images.githubusercontent.com/1033611/117421658-5187d400-af51-11eb-9ad2-5286501b79f2.png)

**Comment by legaspielaine** [comment]
reopening this. @blankart 
the `...` <span> is still blending with the buttons

https://user-images.githubusercontent.com/28699204/117427193-5fd8ee80-af57-11eb-894e-f40c39e8368a.mov
