### ISSUE TITLE
when you click a page in frontend, the other posts block goes to that page as well

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1181]
when 2 posts are created in a page with both their Pagination on, in frontend when you click page 2, the other post block goes to page 2 as well:

https://user-images.githubusercontent.com/28699204/117426433-79c60180-af56-11eb-930b-677c62394ff5.mov

1. add a blog posts block. turn on Pagination.
2. in the same page, add another posts block and turn on Pagination.
3. see bug in frontend

**Comment by blankart** [comment]
This is not a bug
