### ISSUE TITLE
UI issue - dropdown in URL input not aligned

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1183]
When you search any post or page in the URL input, the dropdown is not aligned.
Steps:
add a card
turn on container link, type ‘post’ or ‘page’ in the url input

https://user-images.githubusercontent.com/28699204/117600069-d1928180-b17d-11eb-9291-27b9c180c43e.mov

**Comment by bfintal** [comment]
The spinner is also misaligned
![Screen Shot 2021-05-10 at 1 41 06 PM](https://user-images.githubusercontent.com/1033611/117611099-74a2c580-b195-11eb-8410-b3949fdcc577.jpg)
