### ISSUE TITLE
How can I change Feature block title from h2 to h3 or h4

### ISSUE THREAD

**Issue by mohanvpatta** [gambitph/Stackable#119]
I use Stackable's Feature block for featuring many products on my blog. But the problem is that it's title is creating many h2's which is messing up the TOC. But the main concern is that it also affects the on-page SEO of the blog.

Google prioritizes the h1's and h2's more than h3's and so forth. So it is a good practice to include less h2's (with target keywords) in a single page. I would like to switch the h2's to h3's or h4's. I tried to change it myself before posting here, but I can't figure out how.

Related question posted by @Daddaaff [Make Title Headings selectable #64](https://github.com/gambitph/Stackable/issues/64). But I don't see any suggestions made there.

![Capture](https://user-images.githubusercontent.com/51280293/59148244-cd0a3f00-8a23-11e9-8760-006032758b6f.PNG)

**Comment by bfintal** [comment]
This will be added in across all blocks in version 2 :)

**Comment by mohanvpatta** [comment]
Thanks for the support!
