### ISSUE TITLE
right & bottom padding values are exchanged

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1191]
when upgrading to v2.16.0, the right and bottom padding values are exchanged.
steps:
1. activate the 2.15.3
2. add Feature grid / Card block and adjust the Spacing > Padding (tablet & mobile viewport) values to
```
top - 22
right - 23
bottom - 24
left - 25
```
3. save this page & activate v2.16.0
4. open & check the padding values of the feature grid:
```
top - 22
right - 24
bottom - 23
left - 25
```

expected behavior: the right & bottom padding values should not be exchanged because this will change the block designs

**Comment by blankart** [comment]
It's just a visual bug. Both options represent the same padding values. Already fixed in https://github.com/gambitph/Stackable/pull/1188
