### ISSUE TITLE
Feature button cut off on mobile

### ISSUE THREAD

**Issue by jrgong420** [gambitph/Stackable#120]
**Describe the bug**
The button in the feature box is cut off and is wider than the content. 

**To Reproduce**
1. Go to https://www.cannabisanbauen.net/equipment-guide/#growbox on smartphone
Scroll down to one of the feature boxes
4. See button behaviour

**Expected behavior**
The button should be max as wide as the description and the text should have an automatic line break

**Smartphone (please complete the following information):**
 - Device: Galaxy S 5
 - OS: Android
 - Browser: Chrome
 - simulated in chrome desktop inspector

**Screenshot:**
<img width="386" alt="Screen Shot 2019-06-08 at 18 54 05" src="https://user-images.githubusercontent.com/34307108/59150137-14420100-8a1f-11e9-9900-c86a686899fb.png">

**Comment by bfintal** [comment]
Thanks for the report!
