### ISSUE TITLE
block validation failed for image box block

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1238]
<img width="1473" alt="Screen Shot 2021-06-18 at 3 33 16 PM" src="https://user-images.githubusercontent.com/28699204/122524492-c703bb80-d04a-11eb-8478-3136f6561e86.png">

from a ticket:
this image box is not displaying in the backend, only in frontend:
image box code -
https://gist.github.com/legaspielaine/397cf9ebb1d3eb90598bb3f801ab548f

**Comment by blankart** [comment]
I can't reproduce the issue. Upon refreshing the page, the block auto recovers

**Comment by legaspielaine** [comment]
user replied: the issue fixed itself
