### ISSUE TITLE
Several Blocks: Top and Bottom Separators are missing when Block BG Image is turned on

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#124]
**Describe the bug**
Top and Bottom Separators went missing when you turn on the Block Background Image. Count Up and Icon List are the blocks that are affected.

**To Reproduce**
1. Add a new page
2. Create new Icon List block
3. Add details to your Icon List
4. Add Top or Bottom Separators
5. Turn on the Block Background

**Expected behavior**
The Top and Bottom Separators should not be missing

**Video**
https://streamable.com/yhnq3

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by bfintal** [comment]
This should be tested together with #163 & #164 since this bug affects all of them.
