### ISSUE TITLE
Adding stackable block inside a post shows the code of the block in the editor

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1271]
https://user-images.githubusercontent.com/28699204/124086426-9f1d4a80-da83-11eb-96f1-77c0108cdf0d.mov

add a new post with a stackable block inside. Publish.
add a new page
add a **Query block**
see bug in backend.

**Comment by blankart** [comment]
Related issue: https://github.com/WordPress/gutenberg/issues/33154
