### ISSUE TITLE
Stackable Blocks seems to generate AMP Issues

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#131]
**Describe the bug**
A customer reported that Stackable seems to generate AMP issues. 
He received the following warning when he installed Stackable.
![image](https://user-images.githubusercontent.com/51441886/59754263-563d3380-92b8-11e9-9924-42daba5a1135.png)

When he uses Stackable blocks on his site, he is getting a warning about AMP issue 'excessive_css'.
![image](https://user-images.githubusercontent.com/51441886/59754389-943a5780-92b8-11e9-9604-9fccb71a0c0b.png)

**Comment by bfintal** [comment]
Plugin: https://wordpress.org/plugins/amp/

**Comment by yssagambit** [comment]
can't replicate. possibly fixed by V2. closing this, please reopen if the issue still exist
