### ISSUE TITLE
global typography does not apply to native blocks when a template is set for the page

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1318]
Steps:
Add this inside the functions.php file of your active theme: `add_theme_support( 'block-templates' );`
1. in a new page, add a native paragraph & heading block
2. adjust the Stackable global typography for h2 & body text. Apply styles to `Stackable & native blocks only`
3. in the inspector Page options, click the Template panel > New > create
4. it will show the page template view. Publish and check frontend:
the global typography did not apply to these native blocks

**Comment by legaspielaine** [comment]
I can still reproduce this:

https://user-images.githubusercontent.com/28699204/125601439-d5776e1e-2de8-4b2e-a3fb-31e85587ce01.mov

Note: In backend, the typography applies to Native blocks. In the frontend it does not apply.

**Comment by bfintal** [comment]
Fixed by #1345
