### ISSUE TITLE
Links are still active in the space below the block even if the block is collapsed

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#132]
**Describe the bug**
If you added a Linked text inside the Accordion block, when the block is collapsed, the links will be still active below the accordion block. But it will disappear when you added any block under the accordion block.

**To Reproduce**
1. Add a new page
2. Add Accordion Block
3. Add a Linked Text inside the Accordion Block. **note: do not add any block under it**
4. Publish the page
5. Check the front page

**Expected behavior**
No links under the accordion block when it is collapsed.

**Screenshots**
https://streamable.com/oqbpu

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by Titelsongfuzzie** [comment]
I was about to submit the same bug report, even created an account for this :). I made an [example page](https://perspectives-francophones.blogs.uni-hamburg.de/bug-test/) on a blog. If you hover the mouse beneath the collapsed accordion, the links remain active. This interferes with the elements beneath the Accordion.
