### ISSUE TITLE
 In IOS, Fixed Background setting appears to be zoomed in

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#133]
**Describe the bug**
On IOS, when you turn on the Fixed Background in Header Block, the background image appeared to be zoom in, instead of it's normal size.

**To Reproduce**
1. Add a new page
2. Add a Header Block
3. Change the Background Image
4. Turn on the Fixed Background
5. Publish your page
6. Check the page on IOS

**Expected behavior**
The background image should not appear to be zoomed in

**Screenshots**
Android: https://streamable.com/3ztho
IOS: https://streamable.com/1j5cm

**Smartphone (please complete the following information):**
 - Device: iPhone
 - OS: iOS 12.0
 - Browser: Safari, Chrome

**Comment by yssagambit** [comment]
Sandbox Link:
[http://sandbox.gambit.ph/stackable-premium/8966_parallax-issue-ios/](http://sandbox.gambit.ph/stackable-premium/8966_parallax-issue-ios/)

**Comment by yssagambit** [comment]
reopening this issue. 

not yet fix for iOs, the issue also happens on all of our blocks with the fixed bg. the fixed background is working on android.

sandbox link:http://sandbox.gambit.ph/stackable-v1-for-testing/fixed-background-ios-issue/

using iOs:
![ezgif-3-47c77d22c9d7](https://user-images.githubusercontent.com/51441886/78556895-68d22a80-7842-11ea-9c7e-342aee9376ee.gif)

using android:

![ezgif-3-72f85eb551c5](https://user-images.githubusercontent.com/51441886/78558879-f5321c80-7845-11ea-855c-67f5fe0b5664.gif)

**Comment by bfintal** [comment]
related: https://github.com/WordPress/gutenberg/issues/17718
