### ISSUE TITLE
Double clicking on a text of a stackable block hides all widgets in Customizer widgets area

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1343]
Steps:
1. Go to customizer > widgets
2. add a CTA block or any stackable block
3. double click the title to select it
4. see bug.

https://user-images.githubusercontent.com/28699204/125725738-dc3439ef-2568-4a83-8666-37daf225d790.mov

**Comment by bfintal** [comment]
fixed by a8ef1d5
