### ISSUE TITLE
adjusting the paddings of 1 column, affects the width of both columns

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1407]
Steps:
1. add a columns block
2. add image block in the first col.
3. add a heading & a long text in the 2nd col.
4. unlink both the columns then select the 2nd column.
5. adjust the Block > Spacing > Paddings
6. see bug in backend & frontend

this happens when adjusting `margins` as well.

see vid snippet:

https://user-images.githubusercontent.com/28699204/127611156-755d56cf-333c-4680-83e4-d216613d9a11.mov

https://user-images.githubusercontent.com/28699204/132198415-eb826260-f836-45c2-beb1-33fb47e53587.mov

**Comment by bfintal** [comment]
@legaspielaine can you re-test this whether this is still happening?

**Comment by legaspielaine** [comment]
this is still happening in frontend:

https://user-images.githubusercontent.com/28699204/133387187-ccb2a9fb-1a46-47a3-b55e-486afc9dd58d.mov
