### ISSUE TITLE
"Collapse Buttons On" is showing even if you only have 1 button.

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#141]
**Describe the bug**
The option "Collapse Buttons On" is showing even if you only have 1 button.

**Expected behavior**
The "Collapse Buttons On" should only appear if you have 2-3 buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/51441886/60073129-32636d00-9752-11e9-8eaf-d89cecdf958d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by jkapunan** [comment]
Won't fix. Better for UX if collapse option is seen even with one button.
