### ISSUE TITLE
adjusting column spacing also adjusts the column widths in backend

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1410]
steps:
1. add a columns block
2. add inner blocks to 1st & 2nd column
3. select the 2nd column inspector
4. **style tab > column spacing > spacing**
5. adjust right spacing to 170
6. see bug in backend. column widths are affected

note: The spacing in frontend is correct & width is not affected.

https://user-images.githubusercontent.com/28699204/127627737-25b4954a-8ea2-4c3b-8224-63840e832ee8.mov

**Comment by bfintal** [comment]
@legaspielaine please retest
