### ISSUE TITLE
left & right margins still reflecting even if block background is on

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1415]
steps
add a v2 cta block
adjust the left & right margins in Advanced
turn on Block background.

the left & right margins are still there even if there's no option to adjust left & right margins because block background is turned on.

https://user-images.githubusercontent.com/28699204/127638874-fd9d40ec-73d7-43c5-8150-842365b3ef4f.mov

**Comment by blankart** [comment]
We won't fix this anymore. The fix might cause block errors to existing blocks.
