### ISSUE TITLE
Ghost button has a different height than a normal button

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#1416]
![image](https://user-images.githubusercontent.com/1033611/127769132-6152aef9-db2e-4dae-989a-05e61dac3a6e.png)
Instead of using the CSS style rule `borders` on the actual button `.stk-block-button__button`, we should use borders on a pseudo element instead to ensure that the button's dimensions won't change when changing border widths.

The button currently has an `:after` pseudo element, check whether we can use that for borders.

**Comment by blankart** [comment]
Will create a PR for this
