### ISSUE TITLE
Image focal point not working when image is zoomed

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1444]
From beta feedback:
"i couldn't get the image focal point to work"

steps:
add a v3 Card block or an Image block
upload the image.
go to Style > Image
adjust Zoom to 2.32
adjust the focal point to the left or right
see bug.

https://user-images.githubusercontent.com/28699204/128815926-4acecf8d-8f3d-4ac2-b1d8-95e0dfa4202a.mov

**Comment by blankart** [comment]
related PR: https://github.com/WordPress/gutenberg/pull/33637
