### ISSUE TITLE
Block error on Image block when typing into focal point input

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1454]
add an image block
go to Style tab > Image > Focal point
input 20 - Left, 72 - Right
select the entered text in Left input
delete this and type again - see block error

https://user-images.githubusercontent.com/28699204/129499755-3b0702d7-3ddf-4d2f-a308-9cd207729a13.mov

**Comment by blankart** [comment]
Related PR: https://github.com/WordPress/gutenberg/pull/33637
