### ISSUE TITLE
PHP error: wp_enqueue_script() has been called incorrectly on Widgets page

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1455]
Activate stackable 2.17.5 free version
activate twentytwentyone theme
go to appearance > widgets 
see error:

```
wp_enqueue_script() has been called incorrectly “wp-editor” script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). in Users…\wp-includes\functions.php on line 5535
```

vid snippet from Blocksy:
https://d.pr/v/OkiqxK

**Update:**
When stackable is deactivated, the PHP error goes away

**Comment by blankart** [comment]
Related link: https://core.trac.wordpress.org/ticket/53569

**Comment by bfintal** [comment]
This was fixed by removed the dependency to `wp-edit-post` and `wp-editor`
