### ISSUE TITLE
Adding dynamic content in URL input does not retrieve the correct value

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1461]
Steps
add a v3 CTA block
go to Block tab > Link panel
add a dynamic content in the URL input
toggle - open in new tab
see bug in frontend - it adds `<source>/<fieldname>!#` as the href:
<img width="434" alt="Screen Shot 2021-08-20 at 12 24 29 PM" src="https://user-images.githubusercontent.com/28699204/130178816-818d6c05-6bbe-4db0-a428-2bb2fafec02e.png">

https://user-images.githubusercontent.com/28699204/130178475-46ddda60-9b35-4844-91ef-a16a546ae968.mov

**Comment by blankart** [comment]
I can't reproduce the issue

**Comment by legaspielaine** [comment]
I can still reproduce this

Steps:
1. Add a v3 button block
2. enter inner text
3. add URL for the button
4. Set Dynamic source > Current post > post URL for the Link
5. save and see bug in frontend.

Note: this is failing in e2etest

<img width="1053" alt="Screen Shot 2021-09-07 at 2 21 34 PM" src="https://user-images.githubusercontent.com/28699204/132294398-4e27c117-ea50-4bed-b3b4-bcadd0d50647.png">
