### ISSUE TITLE
Block error on v3 button when setting button text color (Brave browser)

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1469]
Steps:
1. Open the Brave browser in Windows
2. Add a v3 CTA block
2. add background color for the cta button.
3. click 'Add button' to add another button
4. unlink both buttons
5. set the 1st button style to **default**; set the 2nd button style to be **plain**
6. set the text colors of each button to be black
7. add an icon for the 2nd button and set Icon position to left. Set icon color.
8. add a feature grid block below the cta
9. copy the cta's 1st button & paste the styles to the first button in feature grid
10. copy the cta's 2nd button & paste the styles to the second button in feature grid
11. refresh & see in frontend - the font color did not change 
12. refresh the backend - there are block error on buttons

<img width="1453" alt="Screen Shot 2021-08-23 at 1 27 58 PM" src="https://user-images.githubusercontent.com/28699204/130395060-9ca46ba3-2288-4423-a743-44d24fd0e468.png">

code of the button with block error:
https://gist.github.com/legaspielaine/2cc2e9ce1249e4f94f8d7b4a165cb9cf

video snippet from bea:

https://user-images.githubusercontent.com/28699204/132282260-0f2961c5-0ab2-4eda-9e88-7390d91cdabf.mp4

**Comment by blankart** [comment]
Try reproducing this issue without using the linking feature of the button?

**Comment by bfintal** [comment]
@legaspielaine please retest whether this is still applicable

**Comment by legaspielaine** [comment]
@blankart 
More details:

OS: Windows
Browser: Brave
Browser Version: v 1.29.81

**Comment by bfintal** [comment]
Finally found what was going on: https://github.com/gambitph/Stackable/issues/1659
