### ISSUE TITLE
Query Monitor plugin showing stackable missing dependencies when optimization setting is on

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1484]
**Describe the bug**
The Query Monitor plugin reports that Stackable has missing dependencies on pages where no stackable block is used & if the optimization setting is turned on.

**To Reproduce**
1. Install Query Monitor plugin
2. Go to Settings > Stackable and turn on Optimization Settings
3. Add a page with no Stackable blocks (e.g. native paragraph block)
4. Publish page and check Query Monitor in frontend > Scripts to see error

**Expected behavior**
There should be no missing dependencies shown since there are no stackable blocks in the page & the files should not be required / loaded there.

**Screenshots**
<img width="1452" alt="Screen Shot 2021-08-26 at 5 00 08 PM" src="https://user-images.githubusercontent.com/28699204/130934099-e1c74ab5-b734-4a45-9f7e-6539e39c96b9.png">

**Snippet**
https://user-images.githubusercontent.com/28699204/130934047-fe4b5f2a-c788-4f9c-aad2-70606f2a95a4.mov

https://user-images.githubusercontent.com/28699204/130934373-0b7f8fbc-22fe-40e0-88f6-33a2ab3cc8ae.mov

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: Version 92.0.4515.159 (Official Build) (x86_64)

**Comment by bfintal** [comment]
@legaspielaine can you check if this happens in v3
