### ISSUE TITLE
advanced text is not wrapping in mobile view

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1488]
**Describe the bug**
When adding long text / url without spaces, the advanced text block is not wrapping in mobile

**To Reproduce**
1. add a v2 text block
2. enter / paste a long url or text without spaces
3. change the preview mode to mobile
4. see bug

**Expected behavior**
The text block should wrap in mobile just like in tablet & desktop

**Screenshots**
<img width="771" alt="Screen Shot 2021-08-31 at 4 31 14 PM" src="https://user-images.githubusercontent.com/28699204/131469788-81dd740d-e06d-4bc5-969d-903502ba4818.png">

**Note**
This bug happens in 2.17.5 only

**Comment by blankart** [comment]
This is normal for texts without white spaces
