### ISSUE TITLE
Firefox bug: Icon list's toolbar becomes huge

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1495]
**Describe the bug**
When I'm selecting the text in icon list, the toolbar becomes huge

**To Reproduce**
1. Add an icon list
2. Type something
2. Click on the entered text
3. See bug

**Screenshots**
<img width="1414" alt="Screen Shot 2021-09-02 at 2 32 54 PM" src="https://user-images.githubusercontent.com/28699204/131794002-46cd091d-f39f-42be-8e50-c014fd1321b9.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Browser Version: 91.0.2 (64-bit)

**Comment by blankart** [comment]
Can you also test if the same thing happens in core/list block?

**Comment by legaspielaine** [comment]
> Can you also test if the same thing happens in core/list block?

@blankart tested it also when i opened this and it does not happen to native list
