### ISSUE TITLE
AMP plugin conflict: V2 blocks JS frontend files are missing

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1547]
**Describe the bug**
If I activate AMP plugin (optimization plugin) and then add a v2 accordion in the editor, the accordion does not open in the frontend when clicked. (JS file is not loaded)

**To Reproduce**
1. Activate AMP plugin. Setting: Standard mode
2. Add a v2 accordion or count up block
2. View this in frontend.
3. See bug - the accordion can't be opened & count up doesn't trigger animation

**Expected behavior**
The JS files should be loaded

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by bfintal** [comment]
We won't fix this anymore in v2. But we need to make sure that the V3 Accordion block works with AMP.
