### ISSUE TITLE
Current post source in Query Loop's "read more" text show the Query data values instead

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1572]
**Describe the bug**
When Im adding **dynamic content: current post source** in the Read more text of the Query loop block, the content shows the data of the Queried post instead of the current post

**To Reproduce**
1. Add a new page. Type into the page Title. Save.
2. Add a query loop block inside this page. Click Choose.
3. Add dynamic content: current post > Post title to the read more text
4. It shows the correct data in backend but not in frontend.

**Expected behavior**
It should get the actual current post's data

**Screenshots**

https://user-images.githubusercontent.com/28699204/133043318-7a498a37-78b9-4c6b-aac4-77e3f56509a5.mov

**Comment by blankart** [comment]
It will show the query item's post title since it's inside the query loop
