### ISSUE TITLE
Add a custom ID field for anchoring

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#16]
**Is your feature request related to a problem? Please describe.**
I want in-page anchors

**Describe the solution you'd like**
Enable [anchor support](https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/) for all relevant blocks.

**Comment by jrgong420** [comment]
+1! that would be great since i am trying to achieve that

**Comment by benolswang** [comment]
+1! Yes indeed. I am trying to do just this. I want to be able to add an anchor to any heading in every block.

**Comment by ombion** [comment]
Is this feature rolling out any soon? In my case, I'm using a script to display full screen overlay. The scripts relies on #customid to trigger a data set to display. WP only offers custom class for each block and not ID. Thank you.

**Comment by blankart** [comment]
You can now add html anchors in Stackable blocks

**Comment by ombion** [comment]
Thanks for the quick response. That's right, I see the HTML anchor box for the block now. This really helps. Thank you.
