### ISSUE TITLE
Global Typography: The font is not applied in frontend

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1618]
**To Reproduce**
1. Add a Hero block
2. Select the Heading in Hero > change to H1
3. Set H1 font family in Global Typography to Monospace
4. See bug in frontend - The font is not applied

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: Version 93.0.4577.82 (Official Build) (x86_64)

**Comment by blankart** [comment]
I can't reproduce this
