### ISSUE TITLE
Content Horizontal Align in v2 blocks not working in Frontend

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1627]
**Describe the bug**
The Content Horizontal Align in v2 blocks is not working in v3 build

**To Reproduce**
1. Add a Blockquote block. Layout: Centered quote
2. The following settings for the icon:
<img width="302" alt="Screen Shot 2021-09-21 at 5 45 21 PM" src="https://user-images.githubusercontent.com/28699204/134149439-299dd7a9-72d5-40f5-b295-e6c15faa89c1.png">

2. Turn on block BG, set Gradient. set the colors
3. Turn on Top & Bottom Separator, toggle the separator layers for both
4. Add Container link > add url & toggle open in new tab
5. In advanced tab, set content horizontal align to flex end.
6. see bug in Frontend.

**Screenshots**

**Comment by blankart** [comment]
I can't reproduce the issue
