### ISSUE TITLE
Container goes full width when Block background is on

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1628]
**Describe the bug**
All v2 blocks with block background goes full width once the block background is turned on.

**To Reproduce**
1. Add a v2 container block with Basic layout
2. Turn on the block background. Save.
3. See bug in Frontend

**Screenshots**
In v3 build: 

<img width="1541" alt="Screen Shot 2021-09-22 at 10 47 38 AM" src="https://user-images.githubusercontent.com/28699204/134275804-63f86d39-dd2b-447f-8891-c8aa3d02c71c.png">

**Expected behavior**
It should not go full width (by default) when block background is turned on:

<img width="1541" alt="Screen Shot 2021-09-22 at 10 47 47 AM" src="https://user-images.githubusercontent.com/28699204/134275823-64f79b51-8b0a-4b16-bb91-b729cc933d5b.png">

**Comment by blankart** [comment]
I can't reproduce this issue
