### ISSUE TITLE
Range control thumb not moving for horizontal & vertical padding of v2 Buttons

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1632]
**To Reproduce**
1. Add a v2 Button block
3. Adjust the horizontal & vertical padding.
4. See bug

**Screenshots**

https://user-images.githubusercontent.com/28699204/134297788-a0dee2e2-63af-4aa0-a60c-74c2bf6695f9.mov

**Comment by blankart** [comment]
I can't reproduce this
