### ISSUE TITLE
Optimization setting: Feature padding-top of 200 is added on the block

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1634]
**Describe the bug**
When Angled Feature (v2) design is added in the editor, there is a 200px padding-top added in the Frontend.

**To Reproduce**
1. Activate v3. Turn on optimization setting
2. Add a Feature block v2
3. Choose Angled / Aspire / Dare / Devour / Lush / Proact design - Proact has 200 for top & bottom
4. See bug in frontend

**Expected behavior**
There should be no padding top (like in v2.17.5)

**Active Theme**
twenty twenty one

**Comment by blankart** [comment]
I can't reproduce this
