### ISSUE TITLE
Yule Icon list: There is a huge horizontal gap in between the list items

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1637]
**To Reproduce**
1. Add a v2 icon list
2. Choose Yule design
3. Save and view in frontend.

**Expected behavior**
There should be no huge horizontal gap in between the lists

Backend:
<img width="1236" alt="Screen Shot 2021-09-23 at 12 31 57 PM" src="https://user-images.githubusercontent.com/28699204/134455038-b7be25d2-7b1c-4a34-b677-c281453f99ee.png">

Frontend:
<img width="1548" alt="Screen Shot 2021-09-23 at 12 34 43 PM" src="https://user-images.githubusercontent.com/28699204/134455062-f545fd19-d4df-4c3e-81db-c646b57d9b71.png">

**Comment by blankart** [comment]
I can't reproduce the issue
