### ISSUE TITLE
Can't Align Center (front end)

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#165]
**Describe the bug**
Align Center won't apply to the Icon List on the Front End. But is visible on Back End

**Screenshots**
Back End
![image](https://user-images.githubusercontent.com/51441886/60158033-b6852580-9822-11e9-81c0-e925f607c7e8.png)

Front End
![image](https://user-images.githubusercontent.com/51441886/60158045-bdac3380-9822-11e9-9fcd-fec10109de26.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by bfintal** [comment]
Doesn't happen in my copy, please re-test in the next dev version
