### ISSUE TITLE
[Toolset Integration] When Toolset is activated, the advancedSelectControl is huge

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1656]
**To Reproduce**
1. Activate Toolset Blocks / Types
2. Add a v2 / v3 Card
3. Go to Advanced tab
4. Collapse the General panel - see bug

**Screenshots**

https://user-images.githubusercontent.com/28699204/134893927-4323cafc-8da6-49f5-9f53-bf9aefa55acb.mov

**Comment by blankart** [comment]
This isn't our issue anymore. It seems like there are added styles affecting our components.
