### ISSUE TITLE
[ACF Integration] ACF shortcodes not working

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1657]
**To Reproduce**
1. Activate ACF / ACF Pro
2. Add a field group (and field types) & assign this to Posts
3. Add a new Post
4. Fill up the ACF fields below the Post
5. Add a v2 CTA block
6. In the CTA's title, write this: `[acf field="<your_created_field_name_here>"]`
7. Save and see this in frontend. It should display the correct data. (There is no text)

**Comment by blankart** [comment]
I can't reproduce this

**Comment by legaspielaine** [comment]
Closing the issue. Cannot reproduce this with the updated v3 build anymore.
