### ISSUE TITLE
Different view in Front End and Back End, when changing the 'Max. Content Width'

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#167]
**Describe the bug**
Different view in Front End and Back End

**Screenshots**
Back End
![image](https://user-images.githubusercontent.com/51441886/60241963-252bb700-98e7-11e9-91ea-82061d3de8e6.png)

Front End
![image](https://user-images.githubusercontent.com/51441886/60242006-3a084a80-98e7-11e9-8689-7826700e583d.png)

**Comment by bfintal** [comment]
Please retest whether this is still the case
