### ISSUE TITLE
Add More Columns Controls in section blocks

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#1674]
Add this control in section blocks such as Hero block and CTA block under a Style tab > General panel:
![image](https://user-images.githubusercontent.com/1033611/135111253-db1a48b7-71df-4b42-9b3a-b420e4114cf6.png)

For example, in the Hero block:
1. Add `stk-block-hero__inner-container` class
2. Add `alignwide` or `alignfull` in the inner block wrapper

Ensure that you can set the main block to wide/full and then you can set the contents as center/wide/full also.

Make sure this is also applied: https://github.com/gambitph/Stackable/issues/1667

**Comment by legaspielaine** [comment]
Need also to add for Feature block
