### ISSUE TITLE
Removing v3 blocks from Query loop shows an error

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1690]
**To Reproduce**
1. Go to a new page
2. add a query loop block
3. click 'choose'
4. add a v3 icon list / pricing box inside the **query loop** (not post template). save page & reload
5. remove the added block using the keyboard shortcut / delete
6. see error:

**Screenshots**

<img width="978" alt="Screen Shot 2021-10-08 at 2 15 34 PM" src="https://user-images.githubusercontent.com/28699204/136507646-53887bc8-2114-4ca0-9e46-1cab6c63ad44.png">

https://user-images.githubusercontent.com/28699204/136507649-c176be5f-655b-4d6e-9fd6-ab83bba73f7d.mov

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: Version 94.0.4606.61

**Comment by blankart** [comment]
I can't reproduce this

**Comment by legaspielaine** [comment]
Updated the description above & the labels
