### ISSUE TITLE
Entrance animation: No difference in Animation Speed of slow vs fast

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1691]
**To Reproduce**
1. Add a Hero block
2. Select the Heading
3. Go to Advanced > Motion Effects > Add entrance animation
4. Scale: 0.16
5. Animation Speed to slow. compare this with fast

there is no difference

**Comment by legaspielaine** [comment]
This is happening on the released version again

Note:
the fix for this is present in Release Candidate 4:

[stackable-v3.0.0-rc4-premium.zip](https://github.com/gambitph/Stackable/files/7601964/stackable-v3.0.0-rc4-premium.zip)

The issue happened again on 3.0.0 release

**Comment by bfintal** [comment]
@legaspielaine do we have notes on when this was fixed?

**Comment by legaspielaine** [comment]
> @legaspielaine do we have notes on when this was fixed?

@bfintal We do not have notes, but I have the build where this issue was fixed

**Comment by bfintal** [comment]
fixed by https://github.com/bfintal/Stackable-Premium/commit/4831caaf3dd0b1029c0c73d57e1756c417d5f719
