### ISSUE TITLE
Columns > Column Alignments not working correctly

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#1698]
Normal:
![image](https://user-images.githubusercontent.com/1033611/135412945-d43213b0-a484-40ea-adf9-63a8b81e25ea.png)

When centered:
![image](https://user-images.githubusercontent.com/1033611/135412989-6a64bcf3-42e0-4cc2-88c1-4bf179d5f2c5.png)

Start:
![image](https://user-images.githubusercontent.com/1033611/135413025-ad96280f-0fc9-4d54-9814-59563dea82f3.png)

**Comment by blankart** [comment]
I can't reproduce the issue
