### ISSUE TITLE
v2 Icon list: Cannot change icon for the 21st and above item in the list

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1699]
**To Reproduce**
1. Add v2 icon list
2. change to 2 columns
3. add 23 list items
4. change the 21st icon in the list - see bug

this happens in v2 icon list only

https://user-images.githubusercontent.com/28699204/135417414-4aad6110-a2d7-4763-b8f1-48e0bec04aba.mov

**Comment by blankart** [comment]
We only support 20 custom icons
