### ISSUE TITLE
Posts: Content Arrangement not followed when style is Vertical card

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1701]
**To Reproduce**
1. Add a v3 posts. Style: Vertical card
2. Adjust General > Content Arrangement > move category to top
4. See bug in backend & frontend.

<img width="900" alt="Screen Shot 2021-09-30 at 5 57 01 PM" src="https://user-images.githubusercontent.com/28699204/135431150-e16728b6-569f-43a2-ac80-f6b4ff8b90ba.png">

**Comment by blankart** [comment]
The featured image will always be on top in this layout. The others work correctly
