### ISSUE TITLE
Safari: Adding v3 Posts shows duplicated buttons in its toolbar

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1705]
Add a v3 card then:
Add a v3 Posts block in Safari:

https://user-images.githubusercontent.com/28699204/135553923-eae396fa-54d1-4538-bac0-8e53b1c0cbf0.mov

Details:
MacOS
Safari Version 14.0.3 (16610.4.3.1.7)

**Comment by blankart** [comment]
This is not exclusive for safari browser.
