### ISSUE TITLE
Safari: v3 Accordion container goes beyond the block

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1707]
<img width="961" alt="Screen Shot 2021-10-01 at 10 15 47 AM" src="https://user-images.githubusercontent.com/28699204/135555405-b9e20515-18c0-4f38-b3e9-17d5b4d4fc2b.png">

Add v3 columns - 2 columns
add an accordion for each column
see bug in backend & frontend

Details:  
MacOS  
Safari Version 14.0.3 (16610.4.3.1.7)

**Comment by blankart** [comment]
Fixed by #1747

**Comment by blankart** [comment]
Fixed #1742
