### ISSUE TITLE
Block Title and Description won't appear in Front End

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#171]
**Describe the bug**
Block Title and Description won't appear in Front End

**Screenshots**
Back End
![image](https://user-images.githubusercontent.com/51441886/60245353-06312300-98ef-11e9-9740-a7bfa25b8243.png)

Front End
![image](https://user-images.githubusercontent.com/51441886/60245370-10ebb800-98ef-11e9-8f9c-2a1ed686ee2e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by bfintal** [comment]
Can you make sure that the title and description has some text. Based on the screenshots it looks like the text are placeholder text
