### ISSUE TITLE
Widgets page: Cannot resize the image block using the tooltip & by dragging the image

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1721]
Go to Appearance > Widgets
Add a v3 Image block. Upload image
Resize the image using the tooltip / by dragging the edges
see bug

This also happens with Card's image

https://user-images.githubusercontent.com/28699204/135700172-7bdcd74a-9bbd-4b19-abbd-93d61af5b9b1.mov

**Comment by blankart** [comment]
I can't reproduce this
