### ISSUE TITLE
Testimonial Demo Site: some blocks are "This block contains unexpected or invalid content."

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#174]
**Describe the bug**
Some Testimonial blocks in our demo site have an error. "This block contains unexpected or invalid content."

**Screenshots**
![image](https://user-images.githubusercontent.com/51441886/60329751-92ad1580-99c3-11e9-9458-d6d209b942ef.png)

![image](https://user-images.githubusercontent.com/51441886/60329777-9e98d780-99c3-11e9-804a-746f9baaf051.png)

![image](https://user-images.githubusercontent.com/51441886/60329790-a3f62200-99c3-11e9-9f08-8f7b242a7b87.png)

**Link:**
[https://demo.wpstackable.com/testimonial/](https://demo.wpstackable.com/testimonial/)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by bfintal** [comment]
Let's check this during the last stages of the v2 update
