### ISSUE TITLE
Featured Image doesn't work inside a Query Loop

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#1754]
1. Add a Query Loop block
2. Add a column
3. In the column settings, enable container background, and pick the background image as dynamic content > Current Post > Featured Image

or

1. Add a Query Loop block
2. Add an adv image block
3. Pick the image as dynamic content > Current Post > Featured Image

Image won't show up in the backend and frontend

**Comment by blankart** [comment]
Duplicate of #1577
