### ISSUE TITLE
Video PopUp not working on IE11

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#183]
**Describe the bug**
Video PopUp not working on IE11

**Screenshots**
https://streamable.com/j5xh7

**Desktop (please complete the following information):**
 - Browser: IE 11

**Comment by webaware** [comment]
Further info: it's getting a JavaScript error:

>  Object doesn't support property or method 'forEach'

If this is calling `forEach()` on a NodeList, it won't work on IE11 because [IE11 doesn't support that method](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Browser_Compatibility).
