### ISSUE TITLE
Separator Block - multisite - not displaying

### ISSUE THREAD

**Issue by cirrusskelton** [gambitph/Stackable#184]
**Describe the bug**
When Wordpress is configured in multisite mode, on the main site, the separator block displays correctly, on subsites, it displays in the editor, but is missing when the page is previewed and / or published.

**To Reproduce**
Add a separator block to a subsite page and preview / publish the page.

**Expected behavior**
The separator should display.

**Screenshots**
https://ibb.co/HGCz8pr
https://ibb.co/GpLTbLn

**Desktop**
 - OS: Windows 10, Ubuntu 19.04
 - Browser: Chrome, Firefox, Edge, IE
 - Browser Version: Latest release

**Comment by cirrusskelton** [comment]
I have an update to this issue

Separators (and other elements) are broken for anyone lower than a Super Admin for a multisite install.

**Comment by bfintal** [comment]
@cirrusskelton What HTML output are you seeing where the separator is supposed to be?

Did some research and it seems that other plugins are affected as well: https://github.com/WordPress/gutenberg/issues/15137

Here's a closed issue that can give us some clues: https://github.com/WordPress/gutenberg/issues/2539 

It seems that if the user who created the page doesn't have the `unfiltered_html` capability (e.g. Author role or non-Super Admin in multisite), content is filtered out using [wp_kses](https://developer.wordpress.org/reference/functions/wp_kses/) and breaks the block output.

One can simulate the error by adding `define( 'DISALLOW_UNFILTERED_HTML', true );` in `wp-config.php`

Possible untested solutions:
- Allow stripped out HTML tags or attributes that Stackable blocks use in [`wp_kses_allowed_html`](https://developer.wordpress.org/reference/hooks/wp_kses_allowed_html/) filter
- Allow stripped out CSS rules with the [`safe_style_css`](https://developer.wordpress.org/reference/hooks/safe_style_css/) filter

**Comment by yssagambit** [comment]
this is already fixed in V2.
