### ISSUE TITLE
Disable cloning of content in Columns by default

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1879]
**Describe the bug**
From Release Candidate feedback:
> Issues Encountered: "If i duplicate a column, the background color is synced between both. Every change is global for both."

Users may think this is a bug like the feedback on Release Candidate. Let's make the cloning disabled by default - to mimic the behavior of core/columns block when using the slider in the Columns inspector

<img width="349" alt="Screen Shot 2021-10-13 at 3 59 19 PM" src="https://user-images.githubusercontent.com/28699204/137092379-8f3ec4b1-4ca7-4815-82e1-c693e9493915.png">

**Comment by bfintal** [comment]
This has been fixed by 49f46faba0f7a14a26e95f240695493ca2ca1929
