### ISSUE TITLE
Text shadow value of 5 does not look like a shadow

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1881]
**To Reproduce**
1. Add a v3 Text / heading / subtitle
2. Adjust the Shadow slider in Typography to 5

the shadow is added on top of the text block

in backend & frontend:
<img width="538" alt="Screen Shot 2021-10-13 at 4 31 26 PM" src="https://user-images.githubusercontent.com/28699204/137097195-ea9e8f84-34a6-48a3-acd4-6f17600eef40.png">

**Comment by bfintal** [comment]
This is intentional so that users can see that a solid text shadow is possible
