### ISSUE TITLE
The reset button on Content Width should not appear when changing block width to wide/full

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#1897]
1. add a columns block
2. make it wide. check the style tab, the Content Width will turn wide. See that the reset button appears, clicking it will reset it to center
3. make it full. check the style tab, the Content Width will turn full. The reset button appears also.

Expected behavior: the reset button should not appear.
Solution: When the block is wide, the default value should be wide. When full, the default should be full.

https://user-images.githubusercontent.com/1033611/137420214-ee24726d-be65-462d-9cc5-674bf6ddece9.mp4

**Comment by legaspielaine** [comment]
the fix only works for Align center. When you set block alignment of columns to Wide / Full, the reset button still appears in Content Width
