### ISSUE TITLE
Feature: Overlap Background 1 - UI issue in editor

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1972]
When adding Feature > Overlap BG 1 (do not upload an image yet)
When you click after the Feature (to add a paragraph block below it) it hides the paragraph.

There should be space after the Feature block because the paragraph / next block gets hidden:

https://user-images.githubusercontent.com/28699204/138221376-a2ff2446-1582-4941-a554-3ebe8fec58e1.mov

### Frontend: (top Feature is Overlap BG 1, the bottom Feature is Overlap BG 2)
<img width="1567" alt="Screen Shot 2021-10-21 at 2 17 53 PM" src="https://user-images.githubusercontent.com/28699204/138222029-f1c59e82-0edc-47ec-b478-e0134bc1d5b6.png">

**Comment by bfintal** [comment]
I think this is okay, since in overlap background 1, it's really meant for the image to be larger, and for the text to occupy the top left side of the block
