### ISSUE TITLE
[PublishPress Conflict]: Stackable blocks are missing in the editor

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1978]
Stackable blocks are missing when this plugin is activated with Stackable:

<img width="421" alt="Screen Shot 2021-10-22 at 5 29 35 PM" src="https://user-images.githubusercontent.com/28699204/138430729-a53840d2-50e4-4975-aa6e-b3fe3275e7c5.png">

**Comment by htmgarcia** [comment]
Thanks guys for including this fix in 3.0.5! We appreciate it.
