### ISSUE TITLE
setting columns to full width does not display as full width in frontend

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1988]
From a ticket: [Video Snippet](https://www.dropbox.com/s/efn2zd5kauwqt9m/Screen%20Recording%202021-10-26%20at%206.32.44%20PM.mov?dl=0)

**To Reproduce**
1. Add a columns block
2. set background color to black
3. make the columns full width
4. See bug in frontend

**Findings**
- This only happens to some of the users' sites with their themes.
- Removing the `width` property of `.stk-block.alignfull` fixes the issue

**Tickets**
[Website link 1](http://kirkb10.sg-host.com/?page_id=4200&preview=true) - Patricia Barry
[Website link 2](https://christiancreative-dev.10web.me/?page_id=4387&preview=true) - David Martin

**Comment by bfintal** [comment]
@legaspielaine the website links are 404s
