### ISSUE TITLE
Trigger if ALL conditions match is not working

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1997]
**To Reproduce**
1. Login to your local site (with administrator access)
2. In a new page, add a Heading block
3. Advanced tab > Conditional Display
4. Add 2 New conditions
5. set the following options like below:

<img width="313" alt="Screen Shot 2021-11-04 at 4 02 13 PM" src="https://user-images.githubusercontent.com/28699204/140278129-ce80ffb5-f460-432a-8a00-769ae9241dd8.png">

6. based on these settings, the heading block should not be shown in the frontend as it does not meet all the conditions set.
7. see bug - the heading block is still displayed in frontend.

**Comment by bfintal** [comment]
@legaspielaine there's another issue. If you use ANY, and then HIDE with multiple conditions, it also doesn't work.
