### ISSUE TITLE
Texts has too wide padding

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#200]
**Describe the bug**
The text of Horizontal Layout has too much padding/spacing on the left.

**Screenshots**
Backend
![image](https://user-images.githubusercontent.com/51441886/62351408-00ef7580-b538-11e9-8ed4-26247b552fc4.png)

Frontend
![image](https://user-images.githubusercontent.com/51441886/62351415-06e55680-b538-11e9-936c-7d4775df974c.png)

**Comment by bfintal** [comment]
This may have been fixed by #205
