### ISSUE TITLE
Custom Attributes applies to <a> tag instead of the `.stk-block-button` element

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#2002]
**To Reproduce**
1. Add a button / icon button block
2. Select the button & add Custom attribute in advanced tab
3. Save & see this in frontend:

<img width="755" alt="Screen Shot 2021-11-08 at 4 06 14 PM" src="https://user-images.githubusercontent.com/28699204/140705754-68c054ec-77dc-4277-9290-964d7722a9bd.png">

the custom attribute added should be added to the `.stk-block-button` element

**Comment by blankart** [comment]
This might be intentional for button block to achieve certain interactions with other third party plugins (e.g. Lightbox, Modal, Popovers)
