### ISSUE TITLE
HTML anchor is added to <a> tag instead of `.stk-block-button`

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#2003]
Similar to the previous issue #2002  -
When adding HTML anchor to a button / icon button, the id gets added to the <a> tag of the button:

<img width="755" alt="Screen Shot 2021-11-08 at 4 13 23 PM" src="https://user-images.githubusercontent.com/28699204/140706699-6f467941-7127-43f6-ad96-5a19b2809e4c.png">

**Comment by blankart** [comment]
This might be intentional for button block to achieve certain interactions with other third party plugins (e.g. Lightbox, Modal, Popovers)
