### ISSUE TITLE
Custom CSS of Icon block not applying in backend

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#2005]
**To Reproduce**
1. Add Icon block
2. Add custom CSS in advanced tab (e.g: `background-color: red; `)
3. See bug in backend:
<img width="1057" alt="Screen Shot 2021-11-08 at 6 31 10 PM" src="https://user-images.githubusercontent.com/28699204/140726762-fc25a492-99cd-4a52-8fe0-61ce19235e70.png">

**Findings:**
- The selector generated in `<styles>` is incorrect: `.stk-7d2c502.stk-block-icon`
- The selector should have space: `.stk-7d2c502 .stk-block-icon` since the unique selector (`.stk-7d2c502`) is not the same level as the `.stk-block-icon`

**In frontend everything works:**

<img width="1057" alt="Screen Shot 2021-11-08 at 6 31 39 PM" src="https://user-images.githubusercontent.com/28699204/140727193-68df287c-171c-4d93-b23e-e3ebc9b77cde.png">

**Comment by legaspielaine** [comment]
Reopened because this is failing in E2E Tests. Closing this issue once the fix is merged to the `master` branch.

**Comment by bfintal** [comment]
Fixed by https://github.com/gambitph/Stackable/commit/89ff1e2787f67fc443864afcec40f35a6da72f93
