### ISSUE TITLE
Accordion wont open on older version of browsers

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#2009]
**Describe the bug**
Our v3 accordion is using the browser when opening & closing the block. In older versions of browsers, this isn't supported. We need to add backwards compatibility for our accordion.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari
 - Browser Version (not working): 13.1.2
 - Browser Version (working): 14.1.2

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J5
 - OS: Android 7.0
 - Browser: Chrome
 - Browser Version (not working): 95.0.4638.50

**Comment by bfintal** [comment]
Technical notes:
- Our accordion block relies on the browser's support for the `details` HTML tag. https://caniuse.com/?search=details
- The `details` feature isn't supported in older browsers
- Ideal fix: if an older browser is detected (or if support for `details` is not present), then the opening and closing of the accordion should be handled by a frontend JS script. It's important that for browsers that do support the `details` tag, the default browser behavior should be used.
