### ISSUE TITLE
Icon list: Icon & text are not centered in backend & frontend

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#2025]
**To Reproduce**
1. Add icon list (7 list item)
2. change the icon of each item
3. change the icon size to 4
4. See bug > Icons are not aligned correctly and List text is not centered with its Icon

**Screenshots**
<img width="763" alt="Screen Shot 2021-11-15 at 5 58 54 PM" src="https://user-images.githubusercontent.com/28699204/141762038-704936b8-8f4b-4b6e-b1b7-76a8e8c612d5.png">

**Expected behavior**
the list text should be center aligned with the corresponding icon
icons should be centered as well

it should look like this:
<img width="763" alt="Screen Shot 2021-11-15 at 6 04 02 PM" src="https://user-images.githubusercontent.com/28699204/141762287-342ed08f-af2e-4226-a928-03b8cf79e5b3.png">

**Comment by bfintal** [comment]
closed in favor of #2818
