### ISSUE TITLE
Scroll Animation sometimes loads late when Smoothen Scroll Animation is on

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#2029]
**To Reproduce**
1. Add this code of blocks in your editor: [gist](https://gist.github.com/legaspielaine/805fe85ff63b85ee0b482f04e358a2be)
2. Save and view in frontend (adjust your screen width to a smaller size):

https://user-images.githubusercontent.com/28699204/142147614-d91284db-56ef-4dd5-9466-156b9607f65f.mov

3. Try turning off the Smoothen Scroll Animation (on all the Column blocks): the animation loads ok

**Expected behavior**
The animation should immediately load upon entry, regardless of screen size

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome & Edge

**Comment by gumacahin** [comment]
I couldn't reproduce this. The animation seems to be behaving properly regardless of the viewport width:

Uploading Screen Recording 2022-01-25 at 9.05.36 PM.mov…

**Comment by gumacahin** [comment]
I was trying to upload a video to share my findings when I miss clicked.


https://user-images.githubusercontent.com/479559/151091061-24149817-536b-484c-85f8-505d971fe153.mov

**Comment by gumacahin** [comment]
I'm unable to reproduce this issue:

## Steps Taken

### Reproduce bug by rebuilding 4 column block with scroll animation each

* Animation is correct 

### Reproduce bug by using code in gist and replacing missing images for visibility

* Animation is correct (see video)


https://user-images.githubusercontent.com/479559/163747470-ae0fc5d1-ca95-4077-a818-0091e671482e.mov
