### ISSUE TITLE
Button block adder gets covered when changing unit of button paddings to %

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#2034]
**To Reproduce**
1. Add a button block
2. Style > Button Size & Spacing
3. Change vertical padding unit to % > set to 50%
4. Horizontal padding to 20%
5. See bug in Editor

**Expected behavior**
The block adder should not be covered when changing to % unit

**Screenshots**

https://user-images.githubusercontent.com/28699204/142818756-f40f091d-7ffd-4648-b3e8-ee2fc8897f36.mov

**Comment by prconcepcion** [comment]
Issue cannot be replicated anymore since the button adder is on the bottom right and it did not get covered when the paddings changed as stated.
