### ISSUE TITLE
Add option to use a stylesheet only containing the blocks of the latest versions.

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#204]
From an email conversation:

"...one way we can lessen the filesize is probably to have an option to use the styles of only the latest block versions. One quirk of the block editor is that it's a bit strict with regards to block structures being updated, so we're still keeping the styles of the old / deprecated block in the css. I haven't ran any tests about this, but I would bet that the css size would drop significantly if the deprecated block versions were removed."

**Comment by yssagambit** [comment]
there's no reliable way to detect the blocks of the page. so we won't pursue this.
