### ISSUE TITLE
ACF Image type looks blurry when added as Dynamic Content

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#2064]
**Describe the bug**
Using Dynamic content for ACF Image type makes the image blurry - it uses the thumbnail instead of the default image file.

**To Reproduce**
1. Add a Field Group for Posts with 1 field > Image type
2. In a new post, populate the ACF Image field
3. In a new page, add a Dynamic content in Image block > source: the page with the ACF image field
4. see bug > the image looks blurry because we're adding the thumbnail instead of the default image.

We can add the "Image Size" option when adding the ACF Image field - just like when adding Feature Image content:

<img width="329" alt="Screen Shot 2021-12-15 at 5 32 25 PM" src="https://user-images.githubusercontent.com/28699204/146163097-e70e6735-1258-42d4-a006-8283e8e72eb8.png">

so the users can choose whether to display the Full/Medium/Large/Thumbnail of the Image.

**Comment by tusamni** [comment]
Yup, just got this issue.

Only way it gets fixed is by choosing "File" instead of "Image" in ACF.
