### ISSUE TITLE
Setting Posts' Category to gradient Text Color makes the text background gradient

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#2066]
**To Reproduce**
1. Add a Posts block
2. Go to Style > Category
3. Choose gradient color type for Text color, set colors
4. See bug in backend & frontend

Note: This also happens in Title (Frontend) & Excerpt

**Expected behavior**
it should display the text as gradient, and not the background of the text

**Screenshots**
<img width="861" alt="Screen Shot 2021-12-16 at 11 32 56 AM" src="https://user-images.githubusercontent.com/28699204/146303424-438ab1fd-a183-4e5c-91f7-7dab37235598.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: Version 96.0.4664.110 (Official Build) (x86_64)

**Comment by bfintal** [comment]
This has been fixed already
