### ISSUE TITLE
Opacity slider starts at the left end. 

### ISSUE THREAD

**Issue by prconcepcion** [gambitph/Stackable#2098]
![image](https://user-images.githubusercontent.com/49634311/149064387-299c1bc2-9325-402e-9bea-d090e2a5ae63.png)

1. Go to Advanced.
2. Go to Position.

Expected behavior:
The slider should start at the default value of opacity (which is 1).

**Comment by gumacahin** [comment]
This happens in size and opacity slider in the number box block as well.
<img width="274" alt="Screen Shot 2022-01-12 at 1 57 08 PM" src="https://user-images.githubusercontent.com/479559/149072237-8e5e26d3-912e-430b-a980-4586358a1907.png">
