### ISSUE TITLE
Count Up Block > Block Settings > Style Tab > Dynamic Field Icon is unresponsive

### ISSUE THREAD

**Issue by gumacahin** [gambitph/Stackable#2099]
**Duplicate**
https://github.com/gambitph/Stackable/issues/2085

In WP5.9 the dynamic field icon under block settings > style tab is unresponsive to clicks. After clicking the icon does not display the proper resting state.

**To Reproduce**
1. Insert the count up block.
2. Find the dynamic field icon under block settings sidebar > styles
3. Click the icon.

**Expected behavior**
Clicking the icon should display a dialog of options or a prompt to learn more about premium. Icon should be restored to the proper rest state when the user is no longer interacting with it.

**Screenshots**
<img width="276" alt="Screen Shot 2022-01-12 at 12 58 57 PM" src="https://user-images.githubusercontent.com/479559/149067209-0053dcff-3cc7-42ba-a2b7-781d439681a7.png">

**Comment by bfintal** [comment]
Duplicate of #2085
