### ISSUE TITLE
Enabling background to the image in a horizontal team member block misaligns it.

### ISSUE THREAD

**Issue by prconcepcion** [gambitph/Stackable#2100]
1. Add a team member block.
2. Choose horizontal variation.
3. Add a background to the image block. 

https://user-images.githubusercontent.com/49634311/149081148-10720721-64d7-4d89-9b58-51601422f69c.mov

**Comment by bfintal** [comment]
Setting this to `wontfix` because this is the normal behavior, this is happening because the size of the image already occupies the available width of the area, so adding a background (that also adds paddings) pushes the image outward.
