### ISSUE TITLE
Custom CSS not appearing on the backend

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#211]
**Describe the bug**
Custom CSS not appearing on the backend

**Screenshots**
backend:
![image](https://user-images.githubusercontent.com/51441886/63747557-01cabb80-c8da-11e9-9aa9-f3db2f729b65.png)

frontend:
![image](https://user-images.githubusercontent.com/51441886/63747476-d3e57700-c8d9-11e9-9d15-c3f297cfe6b2.png)

**Comment by jkapunan** [comment]
Won't fix.
