### ISSUE TITLE
Clicking on an Icon block does not bring up the icon selector pop up 

### ISSUE THREAD

**Issue by prconcepcion** [gambitph/Stackable#2114]
1. Add an icon block.
2. Click on the icon block. 

https://user-images.githubusercontent.com/49634311/149449566-4bca32a0-936e-478f-b3fb-9b9f72fd8333.mov

**Comment by bfintal** [comment]
Looks like in `src/block-components/icon/index.js`, the `clickOutsideListener` function is also getting triggered when clicking on the icon.
