### ISSUE TITLE
Margin bottom placeholder goes up

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#2154]
https://user-images.githubusercontent.com/1033611/151478041-2a0aca01-40d9-4bed-8ead-265e3caf422c.mov

Steps to replicate:
1. Add a Stackable text block
2. Drag the bottom margin to make it bigger, see the placeholder issue

Notes: 
* Might be related to https://github.com/gambitph/Stackable/issues/1916
* Will need to make sure that the fix works in WP 5.8

**Comment by gumacahin** [comment]
I couldn't reproduce this in 5.9 and 5.8 neither could I reproduce [1916](https://github.com/gambitph/Stackable/issues/1916).

**Comment by gumacahin** [comment]
Discussed.
