### ISSUE TITLE
Copying or pasting styles message lingers.

### ISSUE THREAD

**Issue by prconcepcion** [gambitph/Stackable#2160]
1. Add a block.
2. Repeatedly copy or paste the style. 

https://user-images.githubusercontent.com/49634311/152302965-d60504e4-7038-4f40-9b42-cef2973b3061.mov

**Comment by bfintal** [comment]
It's hardcoded in Gutenberg for each notification to display for 10 seconds and there's no way to change it. The ideal solution is to keep a count of all copy & paste notifications, and ensure that we don't surpass 4 notifications displayed at a time. When a new notification displays, the last one should get removed.
