### ISSUE TITLE
Changing the spacing of the featured image of the posts block does not reflect in the front-end. 

### ISSUE THREAD

**Issue by prconcepcion** [gambitph/Stackable#2161]
1. Add a posts block. 
2. Go to spacing in the style component. 
3. Change the value of the featured image to 1.

https://user-images.githubusercontent.com/49634311/152464443-d91a3fb7-b36f-4a83-818a-860c6807e5e5.mov

**Comment by gumacahin** [comment]
The margin applies correctly when the link  on the featured image is disabled.
