### ISSUE TITLE
Button's shadow disappears when button's border radius is set.

### ISSUE THREAD

**Issue by gumacahin** [gambitph/Stackable#2162]
**Describe the bug**
Button's shadow disappears when button's border radius is set.

**To Reproduce**
1. Add button block.
2. Add button shadow in style tab > button border & shadows (it will work)
3. Add border radius -- shadow disappears.

**Expected behavior**
The button's shadow shouldn't disappear when the button's border radius is set.

**Screenshots**
Video below could possibly show the source of the problem.

https://user-images.githubusercontent.com/479559/152482247-2a982e9a-abee-41a9-a250-e91232a46511.mov

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows, iOS, Android, Palm OS]
 - Browser: [e.g. Chrome, Firefox, Edge, Safari, IE 11, IE 7]
 - Browser Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS 12.0]
 - Browser: [e.g. stock browser, Safari, Chrome]
 - Browser Version: [e.g. 22]

**Comment by bfintal** [comment]
Already fixed
