### ISSUE TITLE
Unable to set button's shadow color from the color picker. Color picker gets dismissed.

### ISSUE THREAD

**Issue by gumacahin** [gambitph/Stackable#2163]
**Describe the bug**
Unable to set button's shadow color from the color picker. When attempting to change the shadow's color via the color picker dialog the dialog gets dismissed and the selected color is never set.

**To Reproduce**
1. Add the button block.
2. On the block's setting panel go to Style > Button Borders/Shadow > Shadow/Outline
3. Click the cog to bring up the dialog. 
4. Click the panel below the section heading to bring up the color picker dialog.
5. Click on the color picker to attempt to select the color. This operation won't work because the dialog will disappear.

**Expected behavior**
The dialog should not disappear and the selected color should appear on the panel that brought up the dialog when clicked.

**Screenshots**

https://user-images.githubusercontent.com/479559/152498449-0766995b-e873-4908-925e-4a5892b632b1.mov

**Comment by bfintal** [comment]
Already fixed
