### ISSUE TITLE
Enabling the Stackable plugin removes color options in the settings sidebar

### ISSUE THREAD

**Issue by gumacahin** [gambitph/Stackable#2189]
**Describe the bug**
When the Stackable plugin is disabled, there are three color settings, Text, Background, Link in settings sidebar >  block tab > color pane. Enabling the Stackable plugin removes color text and link.

**To Reproduce**
1. Enable Stackable Plugin
2. Enable an FSE theme (tested with Twenty Twenty-Two theme)
3. Go to Themes > Editor
4. Click on the header.
5. Go to the settings sidebar > block tab > color pane
6. Only the background setting appears

**Expected behavior**
Link and text settings should also be available in color pane.

**Screenshots**
<img width="1429" alt="Screen Shot 2022-03-01 at 11 10 24 AM" src="https://user-images.githubusercontent.com/479559/156101717-1f720d49-cc3f-4db0-8b05-66eada44cc16.png">

<img width="1435" alt="Screen Shot 2022-03-01 at 11 15 07 AM" src="https://user-images.githubusercontent.com/479559/156101738-f97de7fe-496f-4a8b-acc9-ff8595464fea.png">

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser: N/A
 - Browser Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Browser Version: N/A

**Comment by bfintal** [comment]
Other findings:
- [ ] core paragraph - no color settings if stackable is activated
- [ ] core heading - no appearance settings under typography if stackable is activated
- [ ] core image and core table- no border settings if stackable is activated
- [ ] core quote - no appearance settings if stackable is activated
