### ISSUE TITLE
You cannot edit the link in the popup for v2 button block. 

### ISSUE THREAD

**Issue by prconcepcion** [gambitph/Stackable#2192]
1. Add a v2 button block.
2. Enter and submit a link in the popup when you click the button.
3. When you try to edit the link, the popup closes. 

https://user-images.githubusercontent.com/49634311/156301949-4ebcc2ca-8a43-4d6f-8628-f4d6d6fb70fb.mov

**Comment by gumacahin** [comment]
Related: https://github.com/gambitph/Stackable/issues/2180
