### ISSUE TITLE
Dynamic Content - The contents in the pop-up overflows

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2260]
**Describe the bug**
The contents in the pop-up overflows when scrolling.

**To Reproduce**
1. Add a block with text
2. Highlight text and click the Dynamic Content icon
3. Select "Current Post" in Dynamic Source field
4. Select "Post Taxonomy" in Field
5. Check if the pop-up overflows
6. Repeat steps 2-5 while selecting Dynamic Content in the indicator

**Expected behavior**
- Pop-up contents should not overflow.
- Dynamic Content pop-up should not be overlapped by the Page/Block sidebar when selecting through highlight.

**Screenshots**
Video:
https://user-images.githubusercontent.com/103395655/165062496-25d42c99-ddbd-4d5c-97db-a02625a37c51.mp4

Screenshot image for the overlapped thingy (additional issue):
![image](https://user-images.githubusercontent.com/103395655/165065553-1c16b695-2da6-488a-9f25-51cd49c33dab.png)

**Comment by bfintal** [comment]
Fixed by https://github.com/gambitph/Stackable/commit/35897035ad5fecb4cf7479561cc6ce5aeb019153
