### ISSUE TITLE
Optimize inline css issue for overflowing images

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2264]
**Describe the bug**
The overflowing image was cut when Optimize inline css is enabled in Stackable settings
_Note: Reported using Blocksy starter site_

**To Reproduce**
1. Import "Justice" starter site in Blocksy
2. In Services page, copy code of CTA block (the one with the overflowing image)
3. Add new page and paste the CTA block
4. Publish and view page in frontend
5. Check if image is cut if inline css optimization setting are enabled
6. Issue is not happening if inline css optimization setting is disabled

**Expected behavior**
- Overflowing Image should not be cut in front end view if inline css optimization setting are enabled

**Screenshots**
![image](https://user-images.githubusercontent.com/103395655/165074654-34801a9f-f88e-4e97-b3a7-e08e194c538a.png)
![image](https://user-images.githubusercontent.com/103395655/165074716-b66a1356-4aa3-40fd-b072-73a310c162e4.png)
Video:
https://user-images.githubusercontent.com/103395655/165073084-f3e5e89d-642c-465e-bc05-1ef3d00b8c51.mp4

**Comment by bfintal** [comment]
@andeng1106 I think they fixed this, can't replicate anymore

**Comment by andeng1106** [comment]
@bfintal This issue happens when viewing the page after Published/Updated. It looks fine on editor/backend and preview in new tab.

https://user-images.githubusercontent.com/103395655/167789668-22b675b7-7cf7-481f-9c22-216d574f177f.mp4

**Comment by bfintal** [comment]
@andeng1106 Can you try re-importing the starter site again? I think they might have fixed the issue on the Starter site
