### ISSUE TITLE
Blocks break or get block errors when using a page duplicator/duplicating pages

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2265]
**Describe the bug**
Blocks break or get block errors when using any page duplicator but usually when adding background, icon colors, etc..

Usual happenings where "Attempt Block Recovery" appears:
- Icon Block - when using a diff. icon (from fontawesome or upload)
- Column/Container block - adding bg color settings
- Social Buttons - this might be due to the icons
- under observation for other Blocks....

**To Reproduce**
1. activate stackable and any page duplicator plugin
2. populate a page with stackable blocks (any stackable block. better to add color, bg color settings and stuff to see the issue)
3. duplicate the page
4. check duplicated page and see if some blocks are broken or have block errors

**Expected behavior**
Stackable blocks should display properly and should have no error blocks.

**Screenshots**

https://user-images.githubusercontent.com/103395655/165200710-493fa951-1ee5-4a03-9de1-32ddc06fc5ac.mp4

**Comment by bfintal** [comment]
closing this because this is not an issue with Stackable.
