### ISSUE TITLE
Slow query results using the query monitor plugin

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2267]
**Describe the bug**
While using the Query Monitor plugin, the client receives a slow query that might be related to Dynamic Content.

**To Reproduce**
1. Go to this page https://motionmastertemplates.com/photo-video-slideshow-maker/
2. Click on Log in
3. Login using credentials provided
4. Go back to Step 1 front end view
5. Check if Query Monitor is activated. If not activated, activate Query Monitor plugin
7. Once plugin is activated, check query results (queries > slow queries) and see slow query calls for stackable blocks

**Expected behavior**
Dynamic content queries should be optimized.

**Screenshots**
**Query Monitor > Slow Queries**

https://user-images.githubusercontent.com/103395655/165260665-cca7d2dd-7e64-412f-9a7b-db7ea639fe3b.mp4

**Query Monitor Plugin used**
![image](https://user-images.githubusercontent.com/103395655/165260961-135f3f3f-79a7-40bf-a1bf-99d732348420.png)
![image](https://user-images.githubusercontent.com/103395655/165261040-dde244f7-680a-4156-b9ad-833660f8ce11.png)

**Comment by bfintal** [comment]
fixed by https://github.com/bfintal/Stackable-Premium/commit/a4b93293185505c4f6c51d53b811b21b90d3f12a
