### ISSUE TITLE
Separator block causes horizontal scroll to activate

### ISSUE THREAD

**Issue by preahkumpii** [gambitph/Stackable#227]
**Describe**
When using the separator block, "Wave 1" separator layout, and under Separator Settings -> Separator Width is set > 1, the horizontal scrollbar is activated in the browser, b/c the SVG is breaking out of the width of the parent. This only occurs, as far as I know, with the "Wave 1" layout. Also, it exceeds the width of the parent by the same factor as the "Separator Width" setting.

**To Reproduce**
1. Add Separator block
2. Choose "Wave 1" as separator layout.
3. Go to Separator Settings.
4. Set Separator Width to any value > 1.

**Expected behavior**
The separator should not exceed the visible width of the page, and should not activate the horizontal scrollbar.

**Screenshots**
https://pintasticpinning.com/wp-content/uploads/2019/08/Screen-Shot-2019-08-31-at-2.19.33-PM.png

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser: Opera
 - Browser Version:  63.0.3368.53

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 12.4
 - Browser: Stock
 - Browser Version: ?

**Comment by yssagambit** [comment]
Thanks for the report! Could you test if this fixes the issue?

```css
.ugb-separator.alignfull .ugb-separator__svg-wrapper {
    overflow-x: hidden !important;
    overflow-y: visible !important;
}
```

**Comment by preahkumpii** [comment]
Yes. The CSS code you provided did fix the issue for me.
