### ISSUE TITLE
Pop-up for Highlight and Dynamic Content should overlap to the page toolbar, sidebar, and list view

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2272]
**Describe the bug**
Pop-up for Highlight and Dynamic Content should overlap to the page toolbar, sidebar, and list view. Do the exact thing that happens with Styles option.

**To Reproduce**

**Steps for the page toolbar**
1. Add a block (text block might be preferred)
2. Highlight a text
3. Click the Dynamic content
4. Scroll down and check if the Dynamic Content pop-up was blocked by the page toolbar
5. Click the Highlight
6. Scroll down and check if the Highlight pop-up was blocked by the page toolbar

**Additional steps for the list view**
7. Highlight text near List view
8. Click the Dynamic content again
9. Check if the Dynamic Content pop-up was blocked by the List view

**Additional steps for the side bar**
10. Highlight text near side bar
11. Click the Dynamic content again
12. Check if the Dynamic Content pop-up was blocked by the side bar

**Expected behavior**
Dynamic Content and Highlight pop-up should overlap to the page toolbar, sidebar, and list view.

**Screenshots**

https://user-images.githubusercontent.com/103395655/165721031-60a806ab-3904-4ebf-9a65-e6cadae0da6c.mp4

**Comment by bfintal** [comment]
Can someone test this with WP 6.0 and see whether the issue is still present?

**Comment by andeng1106** [comment]
@bfintal Tested on WP-6.0: 
- Styles and Highlight options works well.
- This issue only exists for **Dynamic Content** pop-up

See video below:

https://user-images.githubusercontent.com/103395655/167775610-1201abdf-b5c8-4c04-a4ab-4409e8af9e1f.mp4
