### ISSUE TITLE
Highlight color feature issue - Unable to change color through color code system (Hex, RGB, HSL)

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2315]
**Describe the bug**
- When I try to change the color (Text or Highlight color) through Custom by deleting the numbers, it cannot be deleted properly
- When copy pasting, it works fine. But when deleting then typing it doesn't.
- Notes:
	- Applies to all blocks that has text
	- Applies to three highlight options: Normal, Highlight, Low

**To Reproduce**
1. Add any block that has text (e.g. Text block or Button block etc.)
2. Add sample text
3. Select text then click Highlight from toolbar
4. Select text from palette
5. Click the custom color selector
6. Click the Settings icon
7. In Hex, try typing or deleting text in the field
8. In RGB, try typing or deleting text in the R, G, B fields
9. In HSL, try typing or deleting text in the H, S, L fields

**Expected behavior**
Should be able to change text color by typing or deleting in the fields.

**Screenshots**

https://user-images.githubusercontent.com/103395655/172298829-d18b2cda-ae8a-45e8-a7d2-ac3d25926e08.mp4

**Comment by bfintal** [comment]
Let's not fix this. It appears that something built in with the text formatting is causing the issue. This issue is also present in the native highlight toolbar option
