### ISSUE TITLE
Number Box block issue - When selecting Number Box, 2 accordions are expanded at the same time in the Inspector by default

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2319]
**Describe the bug**
Upon adding then selecting a Number Box and going to the Inspector > Style, it shows that both accordions are open at the same time.

**To Reproduce**
1. Add a Number Box block
2. Upon selecting Number Box, check if both the **Shape** and **Typography** accordion are open
3. Refresh page
4. Select the Number Box again and check if both the **Shape** and **Typography** accordion are open
5. Collapse any of the two accordion
6. Check if they both collapsed at the same time

**Expected behavior**
The first accordion should be the only accordion open by default upon selecting Number Box block

**Screenshots**

https://user-images.githubusercontent.com/103395655/173796283-6ddd770a-391b-4298-a1e1-4df7c9a61ec7.mp4

**Comment by bfintal** [comment]
This has been fixed in #2509
