### ISSUE TITLE
Notification block issue - icon not visible in backend/editor

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2323]
**Describe the bug**
icon in notification block is not visible in backend after update (3.3.4)
Stackable version used: 3.3.4
Layout: Large Icon only
Note: Icon in notification block works fine in frontend

**To Reproduce**
1. Install latest Stackable version 3.3.4
2. Add a notification block (v3)
3. Choose Large Icon layout
4. Observe that icon color's opacity is too faded even if it's default to 1
5. Observe the icon position changed compared to what's expect (see in frontend since this one works fine)

**Expected behavior**
Icon in the notification block should be visible and position should be same from what's expected before
Like this:
![image](https://user-images.githubusercontent.com/103395655/175222670-acb72da8-69d4-4e42-b3eb-5d518433bdc3.png)

**Screenshots**

https://user-images.githubusercontent.com/103395655/175222892-5bdb8e77-bd7b-4d02-a856-5b5c8889ed83.mp4

**Comment by prconcepcion** [comment]
Image is present but out of place. 

![image](https://user-images.githubusercontent.com/49634311/181098336-169c8072-210b-40c8-aed1-fd26cee592b1.png)
