### ISSUE TITLE
Size & Spacing issue - Resetting Max. Content Width hides Content Horizontal Align settings but doesn't reset it

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2338]
**Describe the bug**
If a user uses the Max. Content Width, that's where the feature Content Horizontal Align only shows. 
But if I unintentionally reset Max. Content Width and forgot to reset Content Horizontal Align, I might mistakenly saw a bug since the Content Horizontal Align is not resetting and automatically hides whenever I reset the Max. Content Width.

Note: This might also apply to all blocks that has Size & Spacing like:
- Inspector > Block tab > Size & Spacing
- Inspector > Style tab > Container Size & Spacing panel
- etc...

**To Reproduce**
1. Copy this code to your editor: 
[max content width & content horizontal align issue.txt](https://github.com/gambitph/Stackable/files/9177310/max.content.width.content.horizontal.align.issue.txt)

2. Follow the steps from the video provided in **Screenshots**
3. Check if the issue also happens

**Expected behavior**
Possible solutions:
1. If Max Content Width is reset, Content Horizontal Align settings should also reset
2. Do not hide Content Horizontal Align feature if it still has settings on and not yet reset even though Content Horizontal Align settings are reset
3. Show both Max. Content Width and Content Horizontal Align features by default

**Screenshots**

https://user-images.githubusercontent.com/103395655/180680022-35a7d307-c034-4aaa-9af3-3f40bb7d9ec4.mp4

**Comment by bfintal** [comment]
#2347
