### ISSUE TITLE
Link / URL - Should be able to select and add "mailto:" and "tel:" in link

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2343]
**Is your feature request related to a problem? Please describe.**
Yes. A user asked if there's an option to add "mailto:" to an link. But since it's not a part of the scope, he has to edit the HTML and add "mailto:" in the href=""
![image](https://user-images.githubusercontent.com/103395655/181467727-38742209-a4ca-47be-9824-16a429b6ce6c.png)

**Describe the solution you'd like**
Should add a feature in Link / URL where you can switch a button to automatically input "mailto:" or "tel:" in the link/url (href)

**Describe alternatives you've considered**
Edit as HTML (manually adding)

**Comment by bfintal** [comment]
Closing this, you don't need to edit the HTML, you can just type it in directly on the link field
