### ISSUE TITLE
Update Freemius SDK to >2.5.0 to solve duplicated page issues

### ISSUE THREAD

**Issue by ouun** [gambitph/Stackable#2344]
**Describe the bug**
Freemius (what is a nightmare BTW) has added a safe mode with their SDK v.2.5.0:
https://freemius.com/help/documentation/wordpress-sdk/safe-mode-clone-resolution-duplicate-website/

It also seems to fix an issue that registers `WP_SITEURL` (example.com/wherever/wp/is/) instead of `WP_HOME` (example.com). 

Stackable currently uses SDK 2.4.3 and it would be great if you could update.

Thanks and kind regards,

Philipp

**Comment by bfintal** [comment]
Hey @ouun! I'm eagerly awaiting the release of Freemius v2.5.0 for the reasons you mentioned. From what I know they haven't released 2.5.0 yet, but the moment they release it we will update to it :)

**Comment by bfintal** [comment]
Please see [49b1817](https://github.com/gambitph/Stackable/commit/49b181768950fe3d37174e9e4a717261756f099e)

While Freemius SDK is still at RC status `2.5.0-rc2`, it seems to be stable. Will be updating this in the release 👍
