### ISSUE TITLE
Posts block issue - Featured image hover color not showing

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2351]
**Describe the bug**
When adding a hover color (either single or gradient) for Posts block > Style > Featured Image and hovering the image in frontend, it doesn't show the hover color.

**To Reproduce**
1. Add a Posts block
2. Choose any layout
3. Make sure to add a featured image in your posts
4. In Inspector > Style > Featured Image, click Hover State and select Hover
5. Add a color for Hover
6. Click Hover State again and choose Normal
7. Hover any featured image in your Posts block
8. Observe if the hover color is appearing or not
9. Save page and check frontend
10. Repeat steps 7-8

**Expected behavior**
Hover color should appear upon hovering featured image in Posts block

**Screenshots**

https://user-images.githubusercontent.com/103395655/182751481-9611f10b-8fe9-4d4c-b63e-7beff5083483.mp4

**Comment by bfintal** [comment]
Fixed by https://github.com/gambitph/Stackable/pull/2533
