### ISSUE TITLE
Accordion block issue - If animations is turned off in Windows and reduced motions is turned on in Mac, "Close adjacent on open" feature not working

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2352]
**Describe the bug**
"Close adjacent on open" feature not working if:
- Windows - Animation effects is turned off
- Mac - Reduced Motion is turned on

**To Reproduce**
1. Add two Accordion blocks
2. In Inspector > General, toggle "Close adjacent on open" ON for both blocks you created
3. Save page and view frontend
4. See if it works well
5. For Windows user, proceed to step 7
6. For Mac user, proceed to step 11

For Windows user:
7. In your settings, turn off Animation effects

8. Reload the page with two accordion blocks
9. Try expanding accordions
10. Check if it doesn't work anymore

For Mac User:
11. In your settings, turn on reduced motions
12. Repeat steps 8-10

**Expected behavior**
"Close adjacent on open" feature should work if animations is turned off in Windows and reduced motions is turned on in Mac

**Screenshots**

https://user-images.githubusercontent.com/103395655/182787602-f0780b14-3a32-4b66-b781-baf49b871d07.mp4

**Comment by bfintal** [comment]
@andeng1106 please test these scenarios:
- Have 2 accordions that open independently from each other
  - should close/open with animation if reduced motion is disabled
  - should close/open without animation if reduced motion is enabled
- Have 2 accordions that has the close adjacent option
  - should close/open with animation if reduced motion is disabled
  - should close/open without animation if reduced motion is enabled
