### ISSUE TITLE
More Posts block options

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2356]
**Is your feature request related to a problem? Please describe.**
Related to this: https://www.notion.so/Improved-Posts-block-4302cd26e0be47378495c328ac26e751#f7fdb1a813564b9d9959eac43142685d

**Describe the solution you'd like**
- add a top filter function

**Describe alternatives you've considered**
N/A

**Comment by bfintal** [comment]
Let's not do this in this form. It's better to create our own filtering feature on our own query loop
