### ISSUE TITLE
Image Customization Features (Image slider, Lightbox, gallery layout, image stacking layout, floating text animation)

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2360]
**Is your feature request related to a problem? Please describe.**
A user is suggesting image customization features.
Related to this: https://www.facebook.com/groups/wpstackable/permalink/1025029651718881/?_rdc=1&_rdr

**Describe the solution you'd like**
Add image customization features:
- Image slider
- Lightbox
- gallery layout
- image stacking layout
- floating text animation

**Describe alternatives you've considered**
N/A

**Comment by bfintal** [comment]
I'll close this issue since this is a set of block & feature requests which we handle separately from issues
