### ISSUE TITLE
Icon List block - Should be able to add border lines between icon list items

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2365]
**Issue #2025 should be done first before proceeding with this.**

**Feature specs**
- should be able to enable/disable the line
- should be able to change the thickness of the line
- should be able to change the width of the line
- should be able to change the color of the line

**Is your feature request related to a problem? Please describe.**
- Related to this post: https://www.facebook.com/groups/wpstackable/permalink/1039202623634917/?_rdc=1&_rdr
- User wanted to put border bottom border lines to separate the icon list items.

**Describe the solution you'd like**
Add a feature to be able to add border lines between icon list items.

**Describe alternatives you've considered**
N/A

**Comment by bfintal** [comment]
closed in favor of #2818
