### ISSUE TITLE
Image Box block issue - Blocks selection goes beyond outside the Image Box container when using Default Layout

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2369]
Related to https://github.com/gambitph/Stackable/issues/2408

**Describe the bug**
When using Default Layout in Image Box, blocks selection bleeds through outside the Image Box container when using Default Layout and it's not aligned to center
Note: 
- This only happens when using the Default Layout. For other layout, it displays correctly.
- This only happens in editor. Frontend view looks good.

**To Reproduce**
1. Add an Image Box
2. Select Default Layout
3. Hover over the Image Box
4. Check if blocks selection indication goes beyond the Image Box container

**Expected behavior**
Blocks selection inside an Image Box container should be aligned to center.

**Screenshots**
![image](https://user-images.githubusercontent.com/103395655/183349426-bcfc05a6-6c28-4ea2-a44d-a6fb67f92a62.png)

**Comment by andeng1106** [comment]
@bfintal Adding this to to Release Cycle Project since this might be fixed by this one: https://github.com/gambitph/Stackable/issues/2408

**Comment by andeng1106** [comment]
@bfintal @vmc08 This will be merged with https://github.com/gambitph/Stackable/issues/2408

**Comment by bfintal** [comment]
Fixed by #2548
