### ISSUE TITLE
Horizantal scroller after using "container block" at full width

### ISSUE THREAD

**Issue by aaqib0003** [gambitph/Stackable#237]
Hey, can you please have a look at the given link below.

https://wheelsmaestro.com/dash-cams/

I am having horizontal scroller on this page, which is caused by the header I think.
If you move the horizontal scroller all the way right, you will see a pinch of the header is missing.

Please have a look at this screenshot:
https://ibb.co/QjxpVhN

Can you help me in fixing it?

**Comment by aaqib0003** [comment]
Resolved...
.no-sidebar .entry-content .alignfull {
max-width: 99.5vw !important;
}

Added this code in css and it fixed.

**Comment by bfintal** [comment]
@aaqib0003 You can also suggest that one to your theme author :)
