### ISSUE TITLE
[Blocksy] Button & Heading block - No underline for links in frontend

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2387]
**Describe the bug**
For buttons: When selecting Style > Link for buttons, there is no underline in frontend compared to editor.
For text block links: When I set a text block as "Show as Link", it doesn't appear as link (no underline)
Note: 
- This issue only happens for Blocksy theme
- This issue happens for blocks such as:
  -  Button block > Link style
  - Heading block

**To Reproduce**
1. Change theme to Blocksy

- For Button block:
   2. Add a button block
   3. Change button style to "Link" (Inspector > Style > Styles > Link)

- For Heading block:
   2. Add a Heading block
   3. Add a URL for that link (using toolbar or dynamic content)

4. Save page
5. Check editor if there's an underline (looks like a link; expected appearance)
6. Check frontend if there's no underline

**Expected behavior**
There should be an underline in frontend button if Button style is set to "Link"

**Screenshots**
**Button block**
https://user-images.githubusercontent.com/103395655/184845225-8097e62c-9e15-41b3-a9e2-94d48e8d5ee4.mp4

**Heading block**
https://user-images.githubusercontent.com/103395655/211230096-ef8db3af-9902-440d-906d-7cf8b2e29041.mp4

**Comment by bfintal** [comment]
Let's not fix this. @mxkae and I investigated and it seems that adding a fix to this might cause more problems.
