### ISSUE TITLE
block team member link

### ISSUE THREAD

**Issue by madvik** [gambitph/Stackable#239]
**Is your feature request related to a problem? Please describe.**
The team member have no option for add a link for a special page for them.
For CV a author page or a special member page…

**Describe the solution you'd like**
Adding a field for link

https://wordpress.org/support/topic/block-team-member-link/

**Comment by yssagambit** [comment]
In V2, we already have a feature "Social Media Buttons". You can also add links to your texts.

Closing this, reopen if needed.

**Comment by madvik** [comment]
How to add an internal link ?
