### ISSUE TITLE
Problem in Image Box block

### ISSUE THREAD

**Issue by madvik** [gambitph/Stackable#240]
**Is your feature request related to a problem? Please describe.**
I have many trouble in usability of this block. When we editing text for long description it is very difficult to correct text.
When we delete description or title for rewrite, the field not appear, we are lost.
It is very difficult fir my customers.

**Describe the solution you'd like**
For usability and accessibility. It should be add fields in the setting of the block on the right side of the screen.

thanks

**Comment by yssagambit** [comment]
I think your block editor is too narrow in the backend. I suggest making the block wide-width or full-width or try zooming out your browser. Unfortunately, this issue isn't specific to Stackable, any three-column block in your case would look that way because of the limited space.

**Comment by madvik** [comment]
screen : 24" 
![image](https://user-images.githubusercontent.com/3822529/74947048-8e25e900-53fa-11ea-85f9-a9ecfd692301.png)

**Comment by madvik** [comment]
Here in front : 
No problem
![image](https://user-images.githubusercontent.com/3822529/74947229-dd6c1980-53fa-11ea-804b-8c458ad9431d.png)

**Comment by madvik** [comment]
I add a screenshot a the zoom
It is to 100%

![image](https://user-images.githubusercontent.com/3822529/75166178-c8a5c380-5723-11ea-899d-4f2f1ad123b7.png)

**Comment by madvik** [comment]
Just image box with 4 columns :
It is difficult to see text in good context
![image](https://user-images.githubusercontent.com/3822529/75166575-57b2db80-5724-11ea-8497-05267d2b9286.png)

**Comment by madvik** [comment]
3 columns :
![image](https://user-images.githubusercontent.com/3822529/75166683-87fa7a00-5724-11ea-93b0-c1d1af360313.png)
