### ISSUE TITLE
Icon Box issue - Icon Box container background overlapping outside the block in frontend view

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2403]
**Describe the bug**
- Issue happens in frontend view only but looks good in editor/backend. 
- Issue happens to some themes such as 2022 & 2023 theme

Issue is noticeable if Block > Background and Container Background is toggled on.

**To Reproduce**
1. Add an Icon Box block
2. Add block background
3. Add container background
4. Save page
5. View frontend page
6. Check if container background is overlapping in frontend

**Expected behavior**
![image](https://user-images.githubusercontent.com/103395655/186836280-334ab60f-c357-405c-b2e0-a1bf41e48568.png)

**Screenshots**

https://user-images.githubusercontent.com/103395655/186836329-5b4f697d-5b47-45e5-b4c7-b8e59024359d.mp4

**Comment by bfintal** [comment]
This has been fixed by #2509
