### ISSUE TITLE
Icon with Style tag causes invalid block error

### ISSUE THREAD

**Issue by vmc08** [gambitph/Stackable#2411]
Uploading icons with color causes invalid block error upon refreshing

Steps to reproduce:

1. Download any icons with color
2. Add icon block then upload the downloaded icon
3. Save the changes then refresh the page

Expected behavior:

1. Should still work as is without the block error

**Comment by bfintal** [comment]
@andeng1106 additional test scenarios (these should be fine after you update and refresh the editor - note that after you refresh the editor the block should look correct):
- in an icon block, icon button block and an icon list block, use an icon from the icon picker and change its color
- in an icon block, icon button block and an icon list block, upload an icon without any color
- add a text block and change the text color (this is to test normal style generation)

**Comment by andeng1106** [comment]
@vmc08 Will move this to Backlog since there's an issue related to the changes. See https://github.com/gambitph/Stackable/pull/2412#issuecomment-1250475079
