### ISSUE TITLE
Icon issue - Some settings are not working properly in backend/editor

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2426]
**Describe the bug**
Issue is present for 3.4.3 versions and above.

Settings that aren't working properly in backend/editor but looks good in frontend:
- [x] Draggable margin bottom
- [x] Block > All settings in Background panel
- [x] Block > All settings in Size & Spacing panel
- [x] Block > All settings in Borders & Shadow panel
- [ ] Style > Icon panel
    - [ ] Gradient Direction (degrees)
  - [x]  hover states
     - [x] Color (Single, Gradient, Multicolor)
     - [x] Icon Opacity
     - [x] Icon Rotation
- [x] Style > Icon Shape panel
  - [x]  hover states
     - [x] Color (Single, Gradient)
     - [x] Shape Border Radius
     - [x] Shape Outline Color
 - [x] Style > Background panel
  - [x]  hover states
     - [x] Shape Color
     - [x] Shape Opacity
- [x] Advanced > Position panel
  - [x]  hover states
     - [x] Opacity
     - [x] Position
- [x] Advanced > Transform & Transition panel
  - [x]  hover states
     - [x] TRANSFORM
- [x] Default Icon block - Not changing to assigned icon (the default star shows even when I set it to an icon from selection or upload svg)
- [x] Custom CSS

Try using this copy of blocks and compare editor and frontend:
[icon block.txt](https://github.com/gambitph/Stackable/files/9565160/icon.block.txt)

**Comment by bfintal** [comment]
@andeng1106 can we verify if the PR #2333 fixes this issue?

**Comment by andeng1106** [comment]
Remaining was moved in https://github.com/gambitph/Stackable/issues/2439
