### ISSUE TITLE
Block Patterns - Add Block notice is shown on Patterns menu preview

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2430]
**Describe the bug**
Related to https://github.com/gambitph/Stackable/issues/2371 but issue only shows for the preview. It works well if Pattern is added in the page/post.

Note: _Please also include the other Custom Patterns plugins for the fix._

Here are some example plugins used to create Patterns:
- Blockmeister
![image](https://user-images.githubusercontent.com/103395655/190536285-167e1d44-a139-4c1b-841a-892a99fea8c2.png)

- Custom Block Patterns
![image](https://user-images.githubusercontent.com/103395655/190537072-4b1a56b1-b52b-4c9d-b031-02162100974c.png)

**To Reproduce**
Blockmeister:
1. Install and Activate Blockmeister plugin
2. Add a Pattern using Stackable blocks (much better to use columns or buttons which have an add block notice)
3. Add new page and add a Pattern block through: **block inserter > Patterns tab**
4. In dropdown, go to your site as option (e.g. WP Local Testing Site)
5. See the preview for the Pattern you created
6. Check if the Add Block notice is shown
 
Custom Block Patterns:
1. Install and Activate Custom Block Patterns plugin
2. Add a Pattern using Stackable blocks (much better to use columns or buttons which have an add block notice)
3. Add new page and add a Pattern block through: **block inserter > Patterns tab**
4. In dropdown, select [CBP]
5. See the preview for the Pattern you created
6. Check if the Add Block notice is shown

**Expected behavior**

**Screenshots**
**BLOCKMEISTER**

https://user-images.githubusercontent.com/103395655/190536725-1ed708bd-dd56-4fe8-a9e6-f27e0bd18082.mp4

**CUSTOM BLOCK PATTERNS**

https://user-images.githubusercontent.com/103395655/190536828-05cafb8e-188f-4f1f-ba8e-85d318845606.mp4

**Comment by bfintal** [comment]
Cannot replicate anymore
