### ISSUE TITLE
Transparent color icon: Line looks crooked

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2449]
WP 6.0.2 (expected):
- Straight line
![image](https://user-images.githubusercontent.com/103395655/195524659-0371210a-2539-48a3-b42b-b1870456586c.png)

WP 6.1 (actual):
- Crooked line
![image](https://user-images.githubusercontent.com/103395655/195524638-5e3c4064-07d7-4744-9bda-b554f3ad8f74.png)

**Comment by prconcepcion** [comment]
Only appears when zoom is browser zoom is 125%
