### ISSUE TITLE
Icon Popover overlapping when scrolling further

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2483]
WP 6.0 (Expected):

https://user-images.githubusercontent.com/103395655/197179019-7fe2b6ee-46f6-4227-ae96-4e527fc2b10f.mp4

WP 6.1 (Actual):

https://user-images.githubusercontent.com/103395655/197179119-72ad2021-d9f6-49da-ab54-2262e605d91a.mp4

**Comment by andeng1106** [comment]
Icon picker popover still overlaps @bfintal. Tried this using 2022, 2023, & Blocksy theme
https://user-images.githubusercontent.com/103395655/200530324-fd910ccc-50fd-483f-b2c9-a4952b6a9c4a.mp4

**Comment by bfintal** [comment]
Let's not fix this. This is dependent on Gutenberg's DropDown & Popover behavior
