### ISSUE TITLE
blob designs on Edge have a weird horizontal line

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#251]
**Describe the bug**
blob designs on Edge have a weird horizontal line when the Stretch Shape Mask is not turned on.

Featured Grid:
![image](https://user-images.githubusercontent.com/51441886/66102550-5520df80-e5e5-11e9-9ca5-237a4e9d97de.png)

https://streamable.com/1td2e

Feature:
![image](https://user-images.githubusercontent.com/51441886/66102636-8ef1e600-e5e5-11e9-95f8-b712499c617d.png)

**Comment by yssagambit** [comment]
This also happens to the native Image Block when used with a Circle style. Wait for a fix from Gutenberg

**Comment by blankart** [comment]
Already resolved
