### ISSUE TITLE
[WPML] Map Block - Prevent translation on some parts only

### ISSUE THREAD

**Issue by prconcepcion** [gambitph/Stackable#2511]
### Issue from user: Map Block doesn't show up on a translated page

Fix from WPML (temporary):
To fix this, we should set the widget as "not-translatable" as it does not have any translatable content on it.
To fix the issue on existing pages, we should:

1. Add the code to WPML > Settings > Custom XML configuration
2. Do a small modification on the original page
3. Update the translation

This code should be added on WPML remote config:

```
<wpml-config>
<gutenberg-blocks>
<gutenberg-block type="stackable/map" translate="0">
</gutenberg-block>
</gutenberg-blocks>
</wpml-config>
```

---

### Prevent translation on some parts of Map Block

As per Jami, we'd like to include some translatable strings to the Map block

Translate the ff:
TBD

We can register the translatable parts using the instructions from here: https://wpml.org/documentation/support/language-configuration-files/#gutenberg-blocks then the unregistered parts will continue untranslatable

Remote configuration link:
https://github.com/OnTheGoSystems/wpml-config/tree/master/stackable-ultimate-gutenberg-blocks

**Comment by bfintal** [comment]
Done, updated in config from WPML's side
