### ISSUE TITLE
Posts Pagination & Load More block - Hide "Link" panel for both Pagination and Load More buttons

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2515]
**Is your feature request related to a problem? Please describe.**
- https://github.com/gambitph/Stackable/issues/2298
- It seems that this is not necessary for both blocks mentioned since each buttons have their own behavior in terms of link/URL.

**Describe the solution you'd like**
Remove "Link" panel/feature for both Pagination and Load More buttons.

**Describe alternatives you've considered**
N/A

**Comment by bfintal** [comment]
This has been fixed by #2509
