### ISSUE TITLE
Countdown block issue - Some strings are not displayed as translated

### ISSUE THREAD

**Issue by DAnn2012** [gambitph/Stackable#2585]
**Describe the bug**
Some strings are not displayed as translated in the editor area of the new Countdown block.

Probably the cause of the issue is these two lines in the source code that differ from the other blocks:
https://github.com/gambitph/Stackable/blob/9072c4b615b4304e67a8ed093335d6fe52a74019/src/block/countdown/edit.js#L27
https://github.com/gambitph/Stackable/blob/9072c4b615b4304e67a8ed093335d6fe52a74019/src/block/countdown/edit.js#L42

and in these files:
https://github.com/gambitph/Stackable/blob/9072c4b615b4304e67a8ed093335d6fe52a74019/src/block/countdown/divider.js#L24
https://github.com/gambitph/Stackable/blob/9072c4b615b4304e67a8ed093335d6fe52a74019/src/block/countdown/schema.js#L7
https://github.com/gambitph/Stackable/blob/9072c4b615b4304e67a8ed093335d6fe52a74019/src/block/countdown/schema.js#L24

**To Reproduce**
Activate the editor area for the Countdown block in a language other than English.

**Expected behavior**
The display of all item translations as for other blocks.

**Screenshots**
![countdown1](https://user-images.githubusercontent.com/1197819/218107979-c022c583-fe8b-4c00-aa07-a639084c67ca.png)

![countdown2](https://user-images.githubusercontent.com/1197819/218107994-373fb5d2-914a-41b6-90da-9c8cfab833ab.png)

![countdown3](https://user-images.githubusercontent.com/1197819/218108029-a62cc022-fad9-4670-8019-4b0f56df41a5.png)

![countdown4](https://user-images.githubusercontent.com/1197819/218108047-a2a237b4-4459-4348-b24e-a67ccc030de1.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6.3
 - Browser: Safari
 - Browser Version: 16.3 (17614.4.6.11.4, 17614)

**Comment by bfintal** [comment]
Thanks for catching this! Will prioritize this
