### ISSUE TITLE
[WP 6.2] Remove native WordPress Copy Paste styles for Stackable blocks

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2605]
**Describe the bug**
Reference: https://www.wpbeginner.com/news/whats-coming-in-wordpress-6-2-features-and-screenshots/#:~:text=your%20own%20requirements.-,Copy%20and%20Paste%20Block%20Styles,-Now%20that%20editing

When I tried out this feature with Stackable blocks, it doesn't work as intended and this feature might be only for Native WordPress blocks. And also, we already have this feature which is the Copy Paste style blocks.

![image](https://user-images.githubusercontent.com/103395655/224298769-ae2abae2-5dee-4458-8aea-7b8103090fcb.png)

**Comment by prconcepcion** [comment]
Based on investigating how this was implemented, it seems that it cannot be taken off as of writing. 

https://github.com/WordPress/gutenberg/pull/45477#issuecomment-1477435875
