### ISSUE TITLE
[WP 6.2] Style Book - When adding additional css for Stackable V3 blocks, it applies to frontend but doesn’t apply in editor and in style book

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2606]
**Describe the bug**
- Reference to new feature: https://www.wpbeginner.com/news/whats-coming-in-wordpress-6-2-features-and-screenshots/#aioseo-see-styles-for-all-blocks-in-the-style-book:~:text=site%20as%20well.-,See%20Styles%20for%20All%20Blocks%20in%20The%20Style%20Book,-The%20site%20editor
- Applicable to both 2022 & 2023 theme
- Works fine for Stackable V2 blocks

**To Reproduce**
1. Go to Appearance > Editor
2. Click Styles
3. In Styles, click the eye icon to go to Style Book
4. Select any Stackable block
5. In the Styles panel, click Additional block CSS
6. Add additional css (e.g. background)
7. Check if it changes on Style Book or not
8. Check also in editor if it changes or not
9. Check frontend if it changes or not

**Expected behavior**
Additional CSS should apply to editor and Style Book
See these videos on what's expected:
- **Stackable V2 Block**

https://user-images.githubusercontent.com/103395655/224223286-fbd3885e-fdd9-4745-bf45-b7c5ff885a98.mp4

- **Native WordPress block**

https://user-images.githubusercontent.com/103395655/224223312-817829a2-0efe-4203-87c7-70e74b9fc419.mp4

**Screenshots**

https://user-images.githubusercontent.com/103395655/224223489-1b8424f1-9b17-4121-8bd7-b06a1871c1ec.mp4

**Comment by bfintal** [comment]
I'm closing this. It works, it's just that you need to know how to target the HTML that you want to style. For example, in a **Button Block** you can add additional CSS like this:

To change the color of the text (mind the space at the selector):
```css
 .stk-button__inner-text {
color: red !important;
}
```

To change the background of the block:

```css
background: red !important;
```
