### ISSUE TITLE
[WP 6.2] Style Book - Some Stackable blocks are missing and preview looks off

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2607]
**Describe the bug**
Blocks such as:
**V3 Blocks**
- [x] Button - missing
- [ ] Icon/Social Buttons - missing
- [x] Load More Button - missing
- [x] Pagination Button - missing
- [x] Progress Bar - missing
- [x] Progress Circle - missing
- [x] Horizontal Scroller - not missing but it overlaps & preview doesn’t look good
![image](https://user-images.githubusercontent.com/103395655/224232702-81d258c7-ea26-4a38-8b7c-4fdfd46ddcbe.png)
- [ ] ~Separator~ - not missing but preview doesn’t look good
![image](https://user-images.githubusercontent.com/103395655/224232742-7f3d919d-0598-4dff-bd9a-55e555ad48d5.png)

**V2 Blocks**
- [ ] Divider - not missing but preview is just blank
![image](https://user-images.githubusercontent.com/103395655/224233202-731fb731-3bae-472f-b901-ecc320088914.png)
- [ ] Icon - not missing but preview doesn’t look good
![image](https://user-images.githubusercontent.com/103395655/224233173-7b4f8eab-2b91-427c-9ee2-ed0c858a9d07.png)
- [ ] Separator - not missing but preview is just blank
![image](https://user-images.githubusercontent.com/103395655/224233148-6f98aff4-f529-4131-9b16-0f721e029cc7.png)
- [ ] Video Popup - not missing but preview doesn’t look good
![image](https://user-images.githubusercontent.com/103395655/224233124-e17de8ae-ab25-48d5-9854-c8853a804589.png)

**To Reproduce**
1. Go to Appearance > Editor
2. Click on Styles
3. Click the eye icon to go to Style Book
4. Select blocks in the description above to see what's wrong

**Comment by bfintal** [comment]
@andeng1106:

1. Since the Icon Button and Social Buttons are variations of the Button Group, they are not yet supported to be part of the Style Book: https://github.com/WordPress/gutenberg/issues/47443
2. The Separator block seems to have been resolved by RC2
3. Let's skip this for V2 blocks since this would be an enhancement to them.
