### ISSUE TITLE
[WP 6.2] Focal point changed UI - Should we preserve the old one or use the new one instead?

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2613]
Old UI (Original - WP 6.1 and below):
![image](https://user-images.githubusercontent.com/103395655/224586611-5a15cd2f-8943-442b-9d0b-cfb08ef05274.png)

New UI (WP 6.2):
![image](https://user-images.githubusercontent.com/103395655/224586630-0439d5d1-f1d3-4269-be56-6fa21fdce308.png)

**Comment by bfintal** [comment]
Let's use the new one if it simplifies our implementation

**Comment by andeng1106** [comment]
will close this after RC 3 release.
