### ISSUE TITLE
Add a enable/disable loop for video background

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2700]
**Is your feature request related to a problem? Please describe.**
Yes. A user is asking if they can disable loop for video background. As per research, it might not be possible by only using Custom CSS.

Reference: https://secure.helpscout.net/conversation/2273713742/20782/

**Describe the solution you'd like**
Should have a feature to be able to enable/disable loop for video background

**Describe alternatives you've considered**
N/A

**Comment by bfintal** [comment]
Let's not do this because it would also need us to start controlling when the background video should play because it can start playing while off screen and the video might already have ended when the user sees the video
