### ISSUE TITLE
Carousel block - Accessibility/ARIA error PageSpeed insights

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2722]
**Describe the bug**
This error shows up for PageSpeed insights if there's a Carousel block in the page:
<img width="965" alt="Screenshot 2023-07-10 at 5 57 49 PM" src="https://github.com/gambitph/Stackable/assets/103395655/5b4f1490-96af-488c-aa1b-9f850cfc4521">

Sample link w/ the error:
https://pagespeed.web.dev/analysis/https-gambitsandbox-instawp-xyz-andrea-aria-carousel/v6pp960wka?form_factor=mobile

**To Reproduce**
1. Add a new page
2. Add a Carousel block
3. Publish page and copy page link
4. Go to https://pagespeed.web.dev/ and add the link from step 3
5. Click Analyze
6. Once analysis is done, scroll down to Accessibility and open ARIA dropdown OR click Accessibility
7. See error

**Expected behavior**
Should not have an Accessibility/ARIA error for Carousel block

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/06d032ed-3158-4e98-b8b7-3e644db4b297

**Comment by bfintal** [comment]
Check if adding a `role="listitem"` fixes this
