### ISSUE TITLE
Lightbox is not working if WP Rocket's Lazy Loading feature is enabled

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2724]
**Describe the bug**
After disabling the lazy loading, lightbox began working again.

**Expected behavior**
Lightbox should work whether WP Rocket's Lazy Loading is enabled or disabled.

**Comment by bfintal** [comment]
Check whether WP Rocket has their own `srcset` attribute for lazy loading that we need to support here: https://github.com/gambitph/Stackable/blob/d2772600c6893cac97be038357ab785e8d43420e/src/lightbox/frontend-image-lightbox.js#L11-L14
