### ISSUE TITLE
Responsive alignment of divisor block not working

### ISSUE THREAD

**Issue by diegosomar** [gambitph/Stackable#2729]
**Steps to reproduce the behavior**
1. Add a divisor block in Gutenberg editor;
2. Change the alignment in responsive modes.

**Expected behavior**
The alignment should change per responsive device.

**Screenshots**

https://github.com/gambitph/Stackable/assets/11670836/8611599f-395b-4376-981e-970591bde8b6

**Desktop**
- OS: Ubuntu 20
- Browser: Firefox
- Browser Version: 115.0.2 (64-bits)
- Stackable Version: 3.9.1 (latest)
- Wordpress Version: 6.2.2 (latest)

**Plugins and themes installed**
- Theme Blocksy Version 1.8.95
- Plugin Blocksy Companion Version 1.8.95
- Plugin Social Chat Version 7.1.3
- Plugin Ninja Forms Version 3.6.28

All plugins and themes are the latest version.

This issue is mentioned in https://github.com/gambitph/Stackable/issues/810 but the problem persists.

**Comment by andeng1106** [comment]
Upon trying out the issue on my end, it seems to not be happening anymore. Closing this issue now. 

@diegosomar Please comment if issue still persists.
