### ISSUE TITLE
Add VW unit

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2735]
**Is your feature request related to a problem? Please describe.**
From user: "Can you please ask your Team if we can have also just not %,EM,REM OR VH, we need also VW for the elements.”

**Describe the solution you'd like**
Add a VW unit

**Describe alternatives you've considered**
N/A

**Comment by bfintal** [comment]
@andeng1106 for QA, we'll need to check whether the new entries for `vw` and `vh` make sense and work, and if we need to add it to other options.
