### ISSUE TITLE
Columns/Carousel block issue on Safari/Firefox browser

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2748]
**Describe the bug**
- Issue happens on Safari or Firefox. Ok on other browsers
- Issue happens when Carousel block is added inside Columns block, there's an unnecessary additional space/padding below the carousel block.
- Issue in frontend only
- Tried removing different settings for both Columns/Carousel block but to no avail, the space still shows.

**To Reproduce**
1. Add a new page
2. Add this block code: 
[carousel block column block issue.txt](https://github.com/gambitph/Stackable/files/12077062/carousel.block.column.block.issue.txt)
3. Save page and view frontend using Safari or Firefox browser
4. See that there's an unnecessary space below

**Expected behavior**
Should have no unnecessary spacing/padding below the carousel block if it's placed inside Columns block.
_Chrome:_

https://github.com/gambitph/Stackable/assets/103395655/0e620ee8-878b-473a-927d-8106160df6a4

**Screenshots**

_Safari:_

https://github.com/gambitph/Stackable/assets/103395655/02b3a5dc-1485-44df-bbb9-18594b007a70

_Firefox:_

https://github.com/gambitph/Stackable/assets/103395655/900c8875-edaa-4bc0-8abd-f414c83ee256

**Comment by andeng1106** [comment]
Additional notes:
- This got fixed on 6.3 but still happens for 6.2 on Safari & Firefox

**Comment by bfintal** [comment]
Let's not fix this.
