### ISSUE TITLE
[WP 6.3] Position Sticky not working for Posts/Pages in editor

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2760]
**Describe the bug**
- When setting Position to Sticky and Z-Index to 10, it doesn't work as expected on Posts/Pages editor
- Still works for site editor (editor & frontend)
- Still works for Posts/Pages frontend

**To Reproduce**
1. Add a new page or post
2. Add any Stackable block
3. In Inspector, go to Advanced > Position
4. Set Z-Index to **10** and Position to **Sticky**
<img width="276" alt="Screenshot 2023-07-20 at 11 52 07 AM" src="https://github.com/gambitph/Stackable/assets/103395655/9f1701c1-bb01-4b25-8541-2166f06f0165">

5. Try scrolling in editor to see if the block sticked or not (see screenshot below to see what's expected to happen)

**Expected behavior**
Position Sticky should work for Posts/Pages in editor

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/e55fdc70-4e33-4baf-9852-1f0a41f4e9ba

**Comment by prconcepcion** [comment]
<img width="1680" alt="image" src="https://github.com/gambitph/Stackable/assets/49634311/948e1f8c-1888-4a6d-972e-a13e2686f483">

**Comment by prconcepcion** [comment]
Fixed in WP 6.3 RC3
