### ISSUE TITLE
[WP 6.3] Link/URL field UI issues

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2761]
- **Dynamic content button is not aligned/centered**
- **No arrow/enter label inside the field**
    - Expected:
        
       <img width="270" alt="Screenshot 2023-07-19 at 10 50 19 AM" src="https://github.com/gambitph/Stackable/assets/103395655/cfde71b8-adf4-44c1-917f-88ab7dfbf8df">

       
       <img width="270" alt="Screenshot 2023-07-19 at 10 48 43 AM" src="https://github.com/gambitph/Stackable/assets/103395655/b3990dc7-e4fd-41a5-92dc-2bed2ce21c8a">
        
    - Actual:
       
      <img width="242" alt="Screenshot 2023-07-19 at 10 46 46 AM" src="https://github.com/gambitph/Stackable/assets/103395655/afdaf6c4-90dc-4f77-a430-057b2401f241">

        
- **When adding link, there’s no margin between the field and search results**
    - Expected:
        
        
       <img width="270" alt="Screenshot 2023-07-19 at 10 50 02 AM" src="https://github.com/gambitph/Stackable/assets/103395655/49199052-4ea8-47af-8cec-03c4d08c9cec">

        
    - Actual:
        
        
       <img width="259" alt="Screenshot 2023-07-19 at 10 50 45 AM" src="https://github.com/gambitph/Stackable/assets/103395655/d03904b1-033d-4dfa-b7ef-696378193826">

       <img width="272" alt="Screenshot 2023-07-19 at 10 47 34 AM" src="https://github.com/gambitph/Stackable/assets/103395655/8c3ba9b2-b4ff-4a04-8a94-c0a55aa8ae11">

**Comment by bfintal** [comment]
The UI seems to be broken here, please follow these points:

1. **Dynamic button alignment** - The dynamic button should be aligned like this even if the link search is open:


![Image](https://github.com/gambitph/Stackable/assets/1033611/3212c2c1-a772-4849-96c5-18769f7ea957)

dynamic button should be aligned to the top (centered along the text field:


![Image](https://github.com/gambitph/Stackable/assets/1033611/86307f5a-2fb2-40ec-858e-ebcff8a219e6)



2. **Dynamic button size** - the button looks squished when the picker is open, it should be square:

![Image](https://github.com/gambitph/Stackable/assets/1033611/44b91dd8-dd20-4a51-a69f-2a1bc297a060)

3. **Button overlaps with the reset button**:

![Image](https://github.com/gambitph/Stackable/assets/1033611/d0e6c733-35ff-42e0-8ef7-153b2572cc30)
