### ISSUE TITLE
[WP 6.3] When uploading a custom svg and changing Icon settings, the editor lags/has delays

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2763]
**Describe the bug**
- Tried uploading a 9kb SVG file
- Try this icon: https://drive.google.com/file/d/1c8h8Al1yqiEVA9Adq6C8Ft0XNjb3FB8K/view?usp=sharing

**To Reproduce**
1. Add Icon List block
2. Add at least 3 items or more
3. In any item, change icon by clicking it
4. Upload the SVG file provided above
5. Try changing Icon settings in Inspector (e.g. Icon Size)
6. See that it lags (e.g. the slide, the editor display, etc.)

**Expected behavior**
When uploading a custom svg and changing Icon settings, the editor should not lag

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/6de76f65-d270-43ad-be2b-83fa856697f3

**Comment by bfintal** [comment]
@andeng1106 is this a WP 6.3 issue? If this was present before, let's not do this issue now

**Comment by andeng1106** [comment]
@bfintal I tried this using WP Version 6.2.2 and it lags inconsistently but it got worse on WP 6.3.

WP 6.2:

https://github.com/gambitph/Stackable/assets/103395655/085ed67f-2093-4cff-9c0d-545061e75301


WP 6.3:


https://github.com/gambitph/Stackable/assets/103395655/13294fbe-e30d-4d24-96d7-9eeec66119e0

**Comment by bfintal** [comment]
closed in favor of #2818
