### ISSUE TITLE
[WP 6.3] Changing icon settings seems laggy if Icon List is with other blocks such as Columns, Tabs, etc.

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2764]
**Describe the bug**
There are lags if Icon List is with other blocks (e.g. Columns, Tabs, etc.) while changing icon settings and different icons are uploaded on each item list.

**To Reproduce**
1. Add other blocks (e.g Columns, Tabs, from Design Library, etc.)
2. Add Icon List block
3. Add at least two or more items
4. Try changing icons for each item (whether uploaded or through icon selection)
5. Try changing icon settings
6. See if it lags

**Expected behavior**
Changing icon settings should not be laggy.

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/2c3a7ac2-a90d-4a86-a59f-f04c6afbf2a8

**Comment by andeng1106** [comment]
See comment here: https://github.com/gambitph/Stackable/issues/2763#issuecomment-1667115945

**Comment by bfintal** [comment]
closed in favor of #2818
