### ISSUE TITLE
[WP 6.3] When dragging Stackable block out of reusable block, it causes a block error

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2768]
**Describe the bug**
- Related to new feature: [Pattern](https://www.hostinger.com/blog/wordpress-6-3-preview#:~:text=the%20Site%20Editor.-,Patterns,-Two%20notable%20changes) (you can now remove block from reusable block using the “Detach pattern” feature)
- Tried it with Native heading block, it doesn’t have an error when dragging it out

**To Reproduce**
1. Add any Stackable block
2. Set it as a reusable block by clicking  **Create Reusable block**
<img width="316" alt="Screenshot 2023-07-21 at 11 52 40 AM" src="https://github.com/gambitph/Stackable/assets/103395655/fa884e76-f018-482f-91d8-678525a013ea">

3. Add the reusable block by clicking the button:
<img width="396" alt="Screenshot 2023-07-21 at 11 54 11 AM" src="https://github.com/gambitph/Stackable/assets/103395655/e0f9a199-1fb9-48ed-acd6-c961a8ba9d39">

4. Try dragging the stackable block out of the reusable block
5. See if it encounters an error

**Expected behavior**
- When dragging Stackable block out of the reusable block, it should not cause a block error
- See what happens for Native Heading block:

https://github.com/gambitph/Stackable/assets/103395655/e82681fc-dd18-4f44-9db6-820048d0abb2

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/65bfc969-f82e-4fee-8928-bf1e60adcd77

**Comment by andeng1106** [comment]
Update (08/07): Issue still happens when using WP Version 6.3 RC-3


https://github.com/gambitph/Stackable/assets/103395655/f80b4703-cd49-4ecd-9e00-394e7de6692d

**Comment by bfintal** [comment]
Hey @andeng1106 apparently this also happens in WP 6.2. Can you verify whether this is also present (when editing a page) in WP 6.1 and 6.0? If so we might have a better fix for it.
