### ISSUE TITLE
[WP 6.3] Top Toolbar extends because of Stackable features, which blocks the Responsive button

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2771]
**Describe the bug**
- Issue is related to new feature [Top Toolbar](https://www.hostinger.com/blog/wordpress-6-3-preview#:~:text=The%20second%20improvement%20is%20made%20to%20the%20Top%20toolbar%20feature.%20Instead%20of%20adding%20the%20block%20toolbar%20on%20an%20additional%20level%20at%20the%20top%2C%20making%20it%20take%20up%20more%20space%2C%20in%20WordPress%206.3%2C%20the%20block%20toolbar%20will%20be%20placed%20at%20the%20same%2C%20single%20top%20panel.)

**To Reproduce**
1. In Editor, click the 3 dots in the top menu
<img width="361" alt="Screenshot 2023-07-21 at 12 05 11 PM" src="https://github.com/gambitph/Stackable/assets/103395655/d6bcda43-d07a-4dfa-8028-4e87fe8152ef">

2. Click Top Toolbar (this will enable the toolbar)
3. Try clicking any block (e.g. Paragraph or Text block)
4. See top toolbar
5. See that the responsive view is missing
6. Try deactivating Stackable plugin
7. Repeat steps 1-4
8. See that the responsive view is no longer missing

**Screenshots**
- What it looks like without Stackable:
<img width="1678" alt="Screenshot 2023-07-20 at 4 16 07 PM" src="https://github.com/gambitph/Stackable/assets/103395655/702d0829-c93f-47ba-a6cf-0537f54af943">

- What it looks like with Stackable (complete features):
   - Free (only the Highlight feature):
   
     https://github.com/gambitph/Stackable/assets/103395655/b46412ec-5e34-49d9-aac7-69bb68b19944

   - Premium (all features Highlight, C&P Styles, Dynamic Content):
   
     https://github.com/gambitph/Stackable/assets/103395655/3adf59fe-2b4f-4075-b287-b6a259e7f079

**Comment by bfintal** [comment]
I can't replicate this in RC3

**Comment by bfintal** [comment]
@andeng1106 please check if we can close this already because of RC3

**Comment by andeng1106** [comment]
@bfintal Issue still happens for RC3 using Stackable Version 10.1

cc: @prconcepcion 

https://github.com/gambitph/Stackable/assets/103395655/22d92137-5c46-4f84-b0d8-d9d8ded38e36

**Comment by prconcepcion** [comment]
Closing this as issue seems to be on the styling of the native WP toolbar
