### ISSUE TITLE
Revamp how Icon List block is structured

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#2818]
This issue takes over #2763 #2764 #2025 #2365 #2980 #2970 #2971

We have a warning that the `multiline` prop will no longer be supported in WP, this is used by the Icon List block so it can exist as a single block. We'll need to change our implementation of the Icon List block and turn it into the following block structure:

- Icon List block
  - Icon List Item Block
  - Icon List Item Block
  - Icon List Item Block

We also need to change our implementation of the SVG icon to resolve some alignment issues, the new output should be:

```html
<ul>
  <li>
    <span aria-hidden="true">icon</span>
    <span>text</span>
  </li>
</ul>
```

**Comment by andeng1106** [comment]
@bfintal Here are some Icon List issues that need to be fixed also:
- https://github.com/gambitph/Stackable/issues/2980
- https://github.com/gambitph/Stackable/issues/2971
- https://github.com/gambitph/Stackable/issues/2970
