### ISSUE TITLE
When you bulk convert/transform Native text blocks into Stackable text blocks, changing settings will applies to all text blocks

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2820]
**Describe the bug**
When transforming multiple Paragraph blocks to Text block at once, then changed settings on a single Text block, other Text blocks become affected.

Affects blocks as:
- Text
- Heading
- Subtitle

**To Reproduce**
1. Add Paragraph blocks
2. Bulk convert Paragraph blocks to Text blocks
3. Change bottom margin/font family/font size of one Text block
4. See that all Text blocks apply the changes

**Expected behavior**
When changing settings for Text block, it should not affect other transformed/converted Text block

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/734e10ee-0d17-4096-9bac-2a65da6c84ee

**Comment by bfintal** [comment]
Hey @andeng1106 this should have been fixed by #2805

**Comment by andeng1106** [comment]
Fixed by https://github.com/gambitph/Stackable/pull/2805
