### ISSUE TITLE
Remove native spacing support when WordPress version is < 6.3

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#2837]
In WP 6.2, if you add a block (e.g. heading block), you'll see the native spacings tabs in the inspector:

![Image](https://github.com/gambitph/Stackable/assets/1033611/7a589f7b-fafd-4a34-821c-a4c9aa432cfe)

This panel should not be here in WP 6.2 and below. To fix this, the `spacing: true` entry in `supports`  should be removed for WP <= 6.2 across all Stackable blocks.

We have a JS filter `stackable.block.metadata` which can be used to override things in the block metadata before it's registered.

**Comment by andeng1106** [comment]
@bfintal Is this related to https://github.com/gambitph/Stackable/issues/2828?

**Comment by bfintal** [comment]
@andeng1106 yes they're identical
