### ISSUE TITLE
[Toolset] Dynamic Source panel placement issue

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2838]
Minor issue: Dynamic Source panel is placed down below (last panel) but if I go to Advanced tab and return to Style or Layout, it becomes the first panel on all tabs.
Reference: https://www.notion.so/Minor-issue-Dynamic-Source-panel-is-placed-down-below-last-panel-but-if-I-go-to-Advanced-tab-and--592c39954d3f4b2a92a373df4e6a4564

**Steps to replicate:**
1. Add a Stackable block
2. In Inspector, go to Style tab
3. Scroll down to see Dynamic Source panel
4. See if Dynamic Source is the last panel
5. Go to Layout tab
6. Repeat Step 3 & 4
7. See if Dynamic Source is the last panel
8. Go to Advanced tab
9. See that the Dynamic Source is the first panel (Expected)
10. Go back to Layout or Style tab
11. See that the Dynamic Source is now the first panel

**Expected Behavior**
Dynamic Source should always be the first panel if Toolset is installed

**Screenshots**
https://user-images.githubusercontent.com/103395655/260364699-d66bc39e-e0ab-42b0-9a07-80d80c52a70c.mov

**Comment by bfintal** [comment]
Closing this as this also happens with other block plugins. Toolset will fix this on their end
