### ISSUE TITLE
When editing Default Block, it displays as Full Width by default on default block editor

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2839]
**Describe the bug**
- Issue happened on WP 6.3
- Issue happens for FSE theme (2022, 2023)
- If editing a Default block, there's no block width options such as Full Width and Wide Width in the toolbar
- Inconsistent issue. Gets fixed when switching from 2023 > Blocksy > 2023 again. But issue randomly pops up again.

**To Reproduce**
1. Add any Stackable block (e.g. Heading)
2. (optional) Style the Heading block
3. Set the Heading block as Default block (go to Options > Set as Default Block)
4. Go to Global Settings and click the pencil icon to edit Default block
5. In the Default Block editor page, see that the block is displayed full width by default
6. See block width options in the toolbar if full width is included (or if block is set to full width)

**Expected behavior**
Default Block should not display as full width in Default Block editor page. See what happens to WP 6.2.

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/30b1fcf9-4174-40d6-8fae-431741a06cba

**Comment by andeng1106** [comment]
Inconsistent issue. Gets fixed when switching from 2023 > Blocksy > 2023 again. But issue randomly pops up again.

**Comment by bfintal** [comment]
I'm removing this for the target 3.11.4 because it's inconsistent. Blocksy also released something to fix a similar issue

**Comment by bfintal** [comment]
Closing this because of Blocksy fix
