### ISSUE TITLE
The block inside the container moves to the left if the block has Block BG 

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#284]
**Describe the bug**
The block inside the container moves to the left if the block has Block BG 

![image](https://user-images.githubusercontent.com/51441886/66629425-4dd88200-ec34-11e9-8448-c09c165cd814.png)

![image](https://user-images.githubusercontent.com/51441886/67744125-99c05f00-fa5b-11e9-8878-118d7becdf9b.png)

**Comment by yssagambit** [comment]
check _Class WP Block_ to know if the block is nested

**Comment by yssagambit** [comment]
the issue has not yet been fixed

![ezgif-1-a1b99f421e97](https://user-images.githubusercontent.com/51441886/69312908-24673900-0c6b-11ea-8bb9-6cbed87d0d32.gif)

**Comment by jkapunan** [comment]
Bug happens in twenty nineteen theme.
