### ISSUE TITLE
Tabs block - Container spacing for Tabs should follow spacing for blocks that are added

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2844]
**Describe the bug**
- An example scenario would be: When you added 3 accordion blocks in Tab 1 then added 6 accordion blocks in Tab 2, Tab 1 has additional spacing due to Tab 2 having lots of blocks. This shouldn't happen and Tab 1 should not be equal with Tab 2's height.

**To Reproduce**
1. Add a Tabs block
2. In Tab 1, add 3 accordion blocks
3. In Tab 2, add 6 accordion blocks
4. Enable Block or Container Background (issue is more noticeable)
5. Switch between Tab 1 and Tab 2
6. See additional spacing for Tab 1

**Expected behavior**
- Should have a toggle button for Tabs block whether they want all container spacing for tabs to be equal or container spacing would be based on how many blocks are added inside the container

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/cb7bc52f-26f1-483b-8ad0-1c3abba73468

**Comment by bfintal** [comment]
## Fix

Let's add a new option here called "Same height across tabs". This option should be disabled by default, but if you are upgrading from an existing tabs block, then this option should be turned on
