### ISSUE TITLE
Query Loop - When adding a dynamic content data for a stackable block, it doesn't display in editor unless block is clicked

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2854]
**Describe the bug**
- When adding a Stackable block with dynamic content data inside a Query Loop > Post Template, the data doesn't display in editor unless the block is clicked
- Upon investigation, issue started to happen on Stackable version 3.5.0

**To Reproduce**
1. Add a new page
2. Add a Native Query Loop block
3. Inside the Query Loop > Post Template, add any Stackable block (e.g. Heading, Image, Card, etc.)
4. In the Stackable block, add content for text or image as dynamic content (e.g. Current Post > Post Title)
5. See that it doesn't appear for the 2nd or following looped Stackable block
6. Try clicking the 2nd or following posts
7. See that the dynamic content data appears upon clicking, but the 1st or other post is not displaying

**Expected behavior**
When adding a Stackable block with dynamic content data inside Query Loop > Post Template, all data for each post should display whether clicked or not

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/92c76216-c431-49c7-a9f6-1af882aa9139

**Comment by andeng1106** [comment]
Related to https://github.com/orgs/gambitph/projects/2/views/1?pane=issue&itemId=36596769

**Comment by bfintal** [comment]
Fixed by b9b3231628e87d934c8efe539042e6c00ac971e0
