### ISSUE TITLE
Lightbox: External links do not work if used in a lightbox gallery

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2864]
**Describe the bug**
- If Lightbox slider is enabled (previous and next buttons are working), some links doesn't show in the light box:
   - Example scenarios here: https://gambitsandbox.instawp.xyz/lightbox-issue/
- Try adding links on Horizontal scroller > Inner Column blocks, issue will be more noticeable

**To Reproduce**
1. Add a new page
2. Add a Horizontal Scroller block
3. Add at least 5 columns
4. Add links in the Inner Column blocks (you can use the links inside the Inner Columns in Scenario 2 in the page link above):
    - column 1 - youtube link
    - column 2 - google maps link
    - column 3 - image link
    - column 4 - page link
    - column 5 - spotify link
5. Enable lightbox for all Inner Columns
6. Save page
7. Go to frontend
8. Click each columns or navigate through light box slider (previous and next buttons)
9. See that columns 2, 4, and 5 is not displaying

**Expected behavior**
- If Lightbox slider is enabled, all links should display properly in the light box

**Screenshots**
_**Scenario 2**_

https://github.com/gambitph/Stackable/assets/103395655/2e1b4b1f-5942-4eab-85c1-13d437698ef7

**Comment by bfintal** [comment]
The issue seems to be when the lightbox is used as a gallery.

To replicate:
1. create 2 blocks one after the other
2. on the 1st block, add a lightbox to an image
3. on the 2nd block, add a lightbox to a link (non-image and non-video)
4. see that the 2nd lightbox doesn't open
