### ISSUE TITLE
[WP 6.4] Global Typography panel does not show the actual font family used by the current block theme

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2931]
**Describe the bug**
- Tested on themes such as:
   - 2024
   - 2023
   - 2022
   - 2021 (issue on post/page editor only)
   - Tove (FSE theme)
- Related to this closed issue: https://github.com/gambitph/Stackable/issues/2858
- Issue happens on:
   - site editor 
   - post/page editor (when switching to tablet and mobile view)

**Expected behavior**
- Should show the actual font family used by the current block theme

**Screenshots**
_**Site Editor**_

https://github.com/gambitph/Stackable/assets/103395655/b8006714-7990-498a-80f1-5ac73bd72f09

_**Post/Page Editor**_

https://github.com/gambitph/Stackable/assets/103395655/a8b2f172-4680-4769-8365-da6fa4b6f982

**Comment by bfintal** [comment]
We just fixed this, and it's now broken in WP 6.4 again :(

Let's not fix this for now, let's leave that the typography defaults won't be carried over for now. Perhaps let's revisit this when we do global styles
