### ISSUE TITLE
[WP 6.4] [Blocker] V3 blocks are not visible even if enabled in settings

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2932]
**Describe the bug**
- V3 blocks are not visible on editor even if blocks are enabled in Stackable settings 
   - Unable to add block
   - Unable to change settings for existing v3 blocks in the page
   - Blocks are not showing in Block Default

**To Reproduce**
1. Enable ALL Stackable V3 blocks in the settings
2. Add a new page
3. Try adding any v3 block (e.g. Heading)
4. See Block Default
5. See that the enabled blocks are missing and unable to add block or edit settings

**Expected behavior**
V3 blocks should be visible on WP Version 6.4 if it's enabled in Stackable settings.

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/d3ce9f7d-b566-4c49-8021-f1e14d8ae848

**Comment by bfintal** [comment]
Fixed by e734b3a05de0d256295e2e61dd96f2dd0d71b177
