### ISSUE TITLE
[WP 6.4] [Blocker] Design Library won’t open

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2933]
**Describe the bug**
Design Library won’t open and there's an error in console:
![image](https://github.com/gambitph/Stackable/assets/103395655/a75f61eb-a687-418d-8fd6-5f9d4aa1d7ea)

**To Reproduce**
1. Add new page
2. Click Design Library
3. See if it won't open
4. Go to Inspect > Console
5. See console error

**Expected behavior**
Design Library should open upon clicking the button

**Screenshots**
https://github.com/gambitph/Stackable/assets/103395655/e834acce-98e6-4be8-aa8f-118fd362568e

**Comment by bfintal** [comment]
Fixed by e734b3a05de0d256295e2e61dd96f2dd0d71b177
