### ISSUE TITLE
[WP 6.4] Link UI issue - Misaligned additional Enter arrow icon in Link / URL field

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2936]
**Describe the bug**
There's an additional Enter arrow icon in upon updating to 6.4 but it's not aligned properly.

**To Reproduce**
1. Add any block that has the Link feature (e.g. Button)
2. Go to Link > Link / URL field
3. See that there's a new Enter arrow icon
4. See if Enter arrow icon is aligned to center vertically

**Expected behavior**
- ~Remove Enter arrow icon (originally not included on WP 6.3):~
- Enter arrow icon should be aligned to center vertically

**Screenshots**
![image](https://github.com/gambitph/Stackable/assets/103395655/6be9dc9f-1e04-4328-a661-ec63168f2530)

**Comment by bfintal** [comment]
@andeng1106 instead of removing it, let's resize and align it correctly
