### ISSUE TITLE
[WP 6.4] [suggestion] Image block - Show preview for image in the list view

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2938]
**Is your feature request related to a problem? Please describe.**
Yes. Since users might add images in carousel or horizontal scroller block like making a gallery, it's a good thing to add WP 6.4's newest update for our Image block.

**Describe the solution you'd like**
Implementing show preview for Stackable's Image block. See [link](https://www.wpbeginner.com/news/whats-coming-in-wordpress-6-4-features-and-screenshots/#aioseo-the-outline-list-view-revamped:~:text=This%20is%20immensely%20helpful%20and%20makes%20the%20outline%20view%20a%20much%20more%20useful%20tool%20than%20ever%20before.%20Previously%20it%20just%20said%20%E2%80%98Image%20%E2%80%98and%20you%20had%20to%20click%20to%20select%20the%20block%20and%20view%20which%20image%20is%20there.)
<img width="332" alt="Screenshot 2023-10-19 at 4 40 02 PM" src="https://github.com/gambitph/Stackable/assets/103395655/b20a1a81-4a87-4233-8996-b2fe90cecaf6">

Can be applied to:
- Image block

**Describe alternatives you've considered**
N/A

**Comment by bfintal** [comment]
This is something good to have, but I don't think it's necessary enough for us to add it in Stackable
