### ISSUE TITLE
[WP 6.4] v2 Image Box - Minor typo in "open in new tab" checkbox label

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2939]
**Describe the bug**
- Minor typo for v2 Image Box "open in new tab" checkbox label
- Related to a WP 6.4 update [(Open in new tab checkbox)](https://www.wpbeginner.com/news/whats-coming-in-wordpress-6-4-features-and-screenshots/#aioseo-open-in-new-tab-in-link-preview:~:text=organized%20in%20categories.-,Open%20in%20New%20Tab%20in%20Link%20Preview,-In%20the%20previous)

**To Reproduce**
1. Add a new page
2. Add a V2 Image Box
3. Click in the center to show the link field
4. Add any link
5. See that it says "Opens in new tab"

**Expected behavior**
It should say "Open in new tab". Tried with Stackable V3 Text block:
<img width="519" alt="Screenshot 2023-10-19 at 6 03 56 PM" src="https://github.com/gambitph/Stackable/assets/103395655/fe3abd8f-354d-478f-b32e-4cb464ca0021">

**Screenshots**
<img width="419" alt="Screenshot 2023-10-19 at 6 02 57 PM" src="https://github.com/gambitph/Stackable/assets/103395655/d541e9e6-7b59-42a0-a853-eeda9a7cf1fa">

**Comment by bfintal** [comment]
This should be okay
