### ISSUE TITLE
[WP 6.4] Link UI issue - Link / URL preview is now missing which causes a gap between Link / URL field and Open in new tab toggle

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2940]
**Describe the bug**
Link / URL preview is now missing which causes a gap between Link / URL field and Open in new tab toggle.

**To Reproduce**
1. Add any block that has the Link feature (e.g. Button)
2. Go to Link > Link / URL field
3. Add any link / url in the field and select it
4. See that the link preview is now missing and there's a big gap between Link / URL field & Open in new tab toggle

**Expected behavior**
This is how it looks like before on WP 6.3 and below (there's a preview):
<img width="294" alt="Screenshot 2023-10-19 at 6 09 33 PM" src="https://github.com/gambitph/Stackable/assets/103395655/f3b22781-22e5-4507-b69f-dc731bed1fbd">

**Screenshots**
This is how it looks like now on WP 6.4 (no preview and has a gap):
<img width="278" alt="Screenshot 2023-10-19 at 6 10 31 PM" src="https://github.com/gambitph/Stackable/assets/103395655/df81c0f5-1b4e-42ab-bbfe-5ce2bf51debe">

**Comment by bfintal** [comment]
@andeng1106 does this happen in native blocks with this same control? I would think that native would also have this. If so, then we won't have to adjust this since it's an enhancement of WP 6.4

**Comment by andeng1106** [comment]
@bfintal This is how it looks like for Native blocks (Toolbar) since they don't have a Link feature on their Block tab settings:

![Image](https://github.com/gambitph/Stackable/assets/103395655/7fb5d50b-38fc-49f6-a636-e450a31c3046)

**Comment by bfintal** [comment]
Okay, we need to fix to bring it back 👍

**Comment by prconcepcion** [comment]
Intended fix by WP
