### ISSUE TITLE
Unable to edit Thrive Theme's Global Header element if Stackable plugin is activated

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2969]
**Describe the bug**
Reference: https://www.notion.so/Marco-Sison-ab1f6ec128ee46e79a564de1d1eb2b26
- When changing Thrive Theme > Global Element > Header's name, it shows an error: `Invalid parameter(s): featured_image_urls, author_info, comments_num`

**To Reproduce**
1. Go to the page provided in the link above
2. Login using the page credentials provided
3. Go to this [URL](https://nomadicfire.com/wp-admin/admin.php?page=tcb_admin_dashboard#templatessymbols)
4. Go to Headers tab
5. Rename the header named "stackable test" to "stackable test 1"
6. Click enter key
7. See that the error appears

**Expected behavior**
- When renaming Thrive Theme's global header, it should not cause an error if Stackable is active

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/ddaaf590-d00f-4100-b616-0f57e9081bf8

**Comment by bfintal** [comment]
Fixed by 0af14cf83ddea2c6ef296470e458f8b2038e5d13
