### ISSUE TITLE
Container background disappears on backend when updating from v1 to v2

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#297]
Back end

![Untitled](https://user-images.githubusercontent.com/50035760/66815519-fbb49b00-ef6a-11e9-9ba2-cb4f82af7234.png)

Front End

![Untitled2](https://user-images.githubusercontent.com/50035760/66815537-0111e580-ef6b-11e9-90bc-84203f423c2a.png)

**Comment by mico97** [comment]
### **V1**
![vlc-record-2019-10-16-14h12m51s-2019-10-16 13-57-45 mkv-](https://user-images.githubusercontent.com/50035760/66892953-8ce54980-f01f-11e9-8d41-9a5157cd1636.gif)

### **V2**
![vlc-record-2019-10-16-14h11m05s-2019-10-16 14-00-35 mkv-](https://user-images.githubusercontent.com/50035760/66892969-9373c100-f01f-11e9-9f44-429f64ba5920.gif)

**Comment by bfintal** [comment]
I think this is correct. The "block background" is different from the normal background in V1.

Block Backgrounds wrap the entire block. In your case, it wraps the Column block (including the wood texture in your video)

**Comment by jkapunan** [comment]
Block backgrounds were not yet implemented in V1.
