### ISSUE TITLE
Posts block - If Post Type is set to Products or Posts/Pages and order by is set to Random, it endlessly loads on the editor

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2975]
**Describe the bug**
- When selecting a Post Type (Posts, Pages, or others) and set Order By to Random for Posts block, it endlessly loads and doesn't show the results in editor
- Issue only in editor
- Issue happens if "Load version 2 blocks in the editor" is checked
- A console error with 400 Bad Request shows:
<img width="607" alt="Screenshot 2023-11-23 at 1 44 01 PM" src="https://github.com/gambitph/Stackable/assets/103395655/a063af9d-4d1a-4598-8a72-daa3cce2707d">

- More info from user:
> According to WordPress documentation orderby only accept following parameters: author, date, id, include, modified, parent, relevance, slug, include_slugs, title and menu_order

**To Reproduce**
1. Add a new page
2. Add a Posts block
3. In Inspector, go to Style > Query > Post Type and change selection to Posts (or "Products" if you have WooCommerce)
4. Go to Query > Order by and change selection to "Random"
5. See that it loads endlessly and doesn't show the results

**Expected behavior**
If I set Order by to Random, it should show the results on editor

**Workaround**
Disable **Load version 2 blocks in the editor** in Stackable settings

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/2abc3e10-c207-4600-83a7-1946504ebbb1

**Comment by prconcepcion** [comment]
V2 has to be off

![Image](https://github.com/gambitph/Stackable/assets/49634311/28811302-f69d-4d33-b43e-acbbc8cb6d6c)
