### ISSUE TITLE
Icon List - Improvement of deleting multiple items

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2980]
**Describe the bug**
- This issue only applies for WP version 6.4 and above.
- When trying to delete 2 or more icon list items, I am unable to do it.

**To Reproduce**
1. Add a new page
2. Add an Icon List block
3. Add at least 3 items
4. Select items 1 to 3 through selecting via cursor
5. Click backspace or delete
6. See that it doesn't delete compared to before

**Expected behavior**
- Should be easy to delete multiple items at once:

https://github.com/gambitph/Stackable/assets/103395655/4e23c84d-c460-46e0-ac8e-e821959580f5

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/7210c78d-abc2-4450-af1d-7a628085d715

**Comment by ezMaverick** [comment]
This bug is so annoying any update on the fix?
