### ISSUE TITLE
numbers are overlapping

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#299]
v1 
![Untitled4](https://user-images.githubusercontent.com/50035760/66822238-69b28f80-ef76-11e9-8679-87ed2f44fbc9.png)
v2
![Untitled5](https://user-images.githubusercontent.com/50035760/66822244-6ddead00-ef76-11e9-8713-632e69c379a9.png)

**Comment by bfintal** [comment]
Not a bug, the block width became smaller this squishing the available area for the text.
