### ISSUE TITLE
Button block encounters a block error upon refresh when adding an HTML anchor

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2998]
**Describe the bug**
Findings:
- When adding an HTML anchor it assigns an ID. But it assigned an ID to the `<a>` tag:
<img width="1674" alt="Screenshot 2023-12-07 at 12 55 22 PM" src="https://github.com/gambitph/Stackable/assets/103395655/1bf49719-ffe4-4eda-8f5d-476445036049">

**To Reproduce**
1. Add a new page
2. Add a Button block
3. In the Button block, add an HTML anchor (Advanced tab > Advanced > HTML Anchor)
4. Save page
5. Refresh page
6. See that the button block encounters a block error

**Expected behavior**
Should not encounter block error

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/748ca2aa-46d1-4975-b5b0-ad8915531350

**Comment by bfintal** [comment]
Ideal fix:
- In the blockDiv block component, remove the prop `applyAdvancedAttributes` (and remove it from the ones using the prop)
- Add a new attribute & option for all button blocks (all the use `applyAdvancedAttributes`) under **Advanced Tab > General > Anchor ID**
  - This new attribute will be used to for the `id` attribute of the `anchor` link of the button
- Add deprecation to move all `anchor` attribute to the new anchor id attribute
