### ISSUE TITLE
Only load the inline script for animations if needed

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#3006]
In the frontend, Stackable outputs this:

```html
<script>requestAnimationFrame(() => document.body.classList.add( "stk--anim-init" ))</script>
```

Since this is only used for animations, we need to only add this when needed.

**Comment by andeng1106** [comment]
QA notes:

- [ ] If free build, should not load whether i have premium animations or not in the page
- [ ] If premium build, should only load when i have premium animations in the page
