### ISSUE TITLE
Dynamic Content - More than 5 search results should be possible

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3014]
**Is your feature request related to a problem? Please describe.**
Yes. If a user have a lot of posts/products that might have the same name, it might not show up since there are only 5 search results showing in dynamic content.

Can also be related to: https://github.com/gambitph/Stackable/issues/3013

**Describe the solution you'd like**
Dynamic Content search results should possibly show more than 5 results

**Describe alternatives you've considered**
N/A

**Comment by bfintal** [comment]
@andeng1106 I think this was already implemented in https://github.com/bfintal/Stackable-Premium/pull/326/files

**Comment by andeng1106** [comment]
Issue is confirmed to be fixed by https://github.com/bfintal/Stackable-Premium/pull/326
