### ISSUE TITLE
Custom Image Sizes / Image Block / Post Block / Card Block.... any Block with Image

### ISSUE THREAD

**Issue by sinanisler** [gambitph/Stackable#3017]
Registered Custom Image sizes not visible for all Image selections.

**Image Block and Posts Block should be priority** but any Block with Image need this setting.

**Thank you 🙏**

```
add_image_size( 'size-400', 400, 400, true );
```

![image](https://github.com/gambitph/Stackable/assets/1686324/3ab8f52e-f6ca-47a6-8d20-199b9be27146)

**Is your feature request related to a problem? Please describe.**
Custom Image Sizes not Selectable doesn't show on the image size list. 

**Describe the solution you'd like**
Show the Registered Custom Image Sizes in the list if three is any coming from a theme or plugin.

**Describe alternatives you've considered**
No alternative.

**Thank you 🙏**

**Comment by andeng1106** [comment]
Hi @sinanisler!

The dev team looked into this and found out that this is working. You need to regenerate image sizes using an Image Regenerate plugin so the option will appear on the Image Size dropdown.

Here’s a video on how we did it:

https://github.com/user-attachments/assets/a31a8753-f014-4b59-b82a-0569c5b25334

Let us know if it works on your end!
