### ISSUE TITLE
Buttons with no text are overwritten with default text when updating to V2

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#302]
**V1**
![button v1](https://user-images.githubusercontent.com/50035760/66982404-9981a480-f0e8-11e9-852d-7919cc55141b.png)

**V2**
![button v2](https://user-images.githubusercontent.com/50035760/66982417-9f778580-f0e8-11e9-99f9-72511eee2d8e.png)

**Comment by bfintal** [comment]
I think this is a very minor issue and can be ignored. A vast majority of users in v1 won't have an empty text button in their pages.

**Comment by bfintal** [comment]
won
