### ISSUE TITLE
[Freemius] Customized SDK URL conflict

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3021]
**Describe the bug**
As per Leo:

> A user reported that the license whitelabeling admin notice on their end links to https://wpstackable.com/account/ even though the notice is for a different product. The notice I'm referring to looks like [this](https://prnt.sc/-MIWHg-zokwU) ("User Dashboard" links to https://wpstackable.com/account/. We noticed that the mentioned link has been hard-coded in the Freemius SDK that comes with the Stackable plugin. The original URL was https://users.freemius.com/ as shown here: [https://github.com/Freemius/wordpress-sdk/blob/master/includes/class-freemius.php#L13655](https://github.com/Freemius/wordpress-sdk/blob/master/includes/class-freemius.php#L13655)
> 
> We don't recommend modifying the SDK as when there are multiple Freemius-powered products running on a site, only one instance of the SDK will be running and the same instance is used by all the Freemius-powered products on that site.

**More info:**

> For a custom URL, you may submit a PR on GitHub that introduces a relevant filter. Then, in your product's code (not the SDK's code), you can use that filter to customize the URL. Here's how the SDK supports customization of the premium version installation video URL:$this->apply_filters( 'upload_and_install_video_url', '//bit.ly/wp-' . $this->_module_type . '-upload' )Then, in your integration code, you could customize the mentioned URL above like this:sugb_fs()->add_filter( 'upload_and_install_video_url', ... );That is found in the get_complete_upgrade_instructions() method of the Freemius class. The new filter that I mentioned above will work the same way (the name of the filter will just be different).

**Comment by bfintal** [comment]
Already added in
