### ISSUE TITLE
count up background disappears when updating from v1 to v2

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#303]
V1
Back End
![count1back](https://user-images.githubusercontent.com/50035760/66986641-db631880-f0f1-11e9-8f86-4ba207a9b791.png)

Front End
![count1front](https://user-images.githubusercontent.com/50035760/66986709-00f02200-f0f2-11e9-81b5-8fd532c3ab78.png)

V2
Back End
![count2back](https://user-images.githubusercontent.com/50035760/66986760-11080180-f0f2-11e9-9339-837c13ab16cd.png)

Front End
![count2front](https://user-images.githubusercontent.com/50035760/66986764-136a5b80-f0f2-11e9-8cd9-9e72f3994e17.png)

**Comment by bfintal** [comment]
@mico97 After upgrading to v2, it's okay for the block's background to disappear while in the block editor (like what you experienced)

As long as the block in the frontend still displays the background, then it's okay.
