### ISSUE TITLE
Selecting Notification media tint or opacity overrides default background color

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#304]
This only happens when not selecting a specific background color.
it overrides the default color (i.e, red for error, green for success), changing it to a white background for opacity and a black background with white text for media tint. additionally, selecting the opacity while using default colors does not visually change the block's opacity in the backend but does so in the front end.

![2019-10-17 16-29-59](https://user-images.githubusercontent.com/50035760/66993461-33078100-f0fe-11e9-9849-a4b9adb810ff.gif)

**Comment by yssagambit** [comment]
Background Color Opacity is already fixed, Background Media Tint Strength will fix on Version 2.1.
