### ISSUE TITLE
Translation issue for .pot file

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3044]
**Describe the bug**
- Notes:
   - When creating translations via Poedit and using the .mo & .po files, it doesn't apply for some .js files
   - There might be a problem with the .pot file
   - Related to this documentation: https://docs.wpstackable.com/article/524-translate-the-stackable-plugin-manually

**Expected behavior**
- Should be able to translate .js files

**Comment by bfintal** [comment]
Fixed by https://github.com/gambitph/Stackable/commit/6bc37f7c0ff1e37b6f4cd4a9fabb4cfdd90d6ffa
