### ISSUE TITLE
feature image leaks out of the shape when the stretch option is turned off on edge browser [v2][edge][feature]

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#305]
only affects the edge browser, firefox and chrome are working as intended. additionally, for the circle and blob shapes, the image leaks out of the shape when the stretch option is turned off. 

the initial issue is a duplicate of  #258.
 
![featureimg](https://user-images.githubusercontent.com/50035760/67000766-0017ba00-f10b-11e9-9fe7-6285c4cc17f5.png)

**Comment by bfintal** [comment]
Duplicate of #251
