### ISSUE TITLE
Bottom Separator not going to the back of content

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3061]
**Describe the bug**
**_Note: This issue is from the affiliate who encountered bugs when testing out Stackable_**
- Related to: https://www.notion.so/39817c6c8fea42e8ab38e2ae6dae36e4
- Applies to all blocks with Bottom Separator
    - [ ]  Columns/Container
    - [ ]  Feature
    - [ ]  Feature Grid
    - [ ]  Hero
    - [ ]  Call to Action
- Issue is visible if Bottom Separator is enabled (make sure Top Separator is disabled)

**To Reproduce**
1. Add a new page
2. Add any blocks mentioned above (e.g. Columns)
3. (optional) Add inner blocks if none yet
4. In Inspector, enable Bottom Separator
5. Make sure to add Height to see issue
6. See that the bottom separator overlaps the inner blocks even if "Bring in Front" is disabled

**Expected behavior**
- Bottom Separator should not overlap inner blocks if "Bring in Front" is disabled

**Workaround**
- Add this code to Custom CSS:
```
.stk-block-columns .stk-separator {
z-index: -1;
}
```

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/83ba1a0e-bea1-48a6-b9c9-a0ed55c53a9c

**Comment by bfintal** [comment]
The fix https://github.com/gambitph/Stackable/pull/3081 causes issues. We'll need to revisit the fix for this. For the meantime, the fix has been reversed in the develop branch
