### ISSUE TITLE
Posts block > Horizontal layouts - Post details are not showing properly on Tablet & Mobile in editor

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3077]
**Describe the bug**
- Related to: https://www.notion.so/Peter-7066e0e7ecdd4e46adb9f86fd58c0fb5
- Issue might be hard to replicate
- Issue on editor only
- Happens to Horizontal 1 & 2 layout
- Happens mostly if both inspector and list view is open
- Happens on all responsive views

**To Reproduce**
1. Add a new page or use this [test page](https://gambitsandbox.instawp.xyz/andrea/posts-block-horizontal-issue-post-details-missing/)
2. Add a Posts block
3. Select any Horizontal layout
4. Try resizing featured image (any unit)
5. While the image is getting bigger, the post details disappear from view
6. Check tablet view
7. Check mobile view

**Expected behavior**
- Post detals should not disappear if featured image is resized or bigger

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/67d7fd6b-ee2c-4ef5-89cb-a71af102643f

https://github.com/gambitph/Stackable/assets/103395655/b82db9e7-fda5-4793-8989-5555219e0b7e

**Comment by bfintal** [comment]
Looking further into this, it might be quite difficult to address. Since this would almost never be bothersome to users when they're editing their blocks, let's not fix this.
