### ISSUE TITLE
[Suggestion] Can Stackable Typography get the Installed Fonts for Font Manager?

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3095]
Related to the new feature [Fonts Manager ](https://www.wpbeginner.com/news/whats-coming-in-wordpress-6-5-features-and-screenshots/#aioseo-video-tutorial:~:text=list%2C%20keep%20reading-,The%20Fonts%20Library,-Earlier%2C%20we%20reported)

**Comment by bfintal** [comment]
This was already introduced in v3.13.3
