### ISSUE TITLE
List Category Per Column

### ISSUE THREAD

**Issue by jfambrini** [gambitph/Stackable#31]
I would love to be able to list a unique category per column. I've created a frontpage with themezee where there are multiple columnal layouts, each layout has two or more columns where each category is listed in one column. Right now most Gutenberg plugins list either only one or only 15 to 20 categories. 

If the whole list of categories can be listed and then one can pick one category to display in a column I can re-create my fronpage at jim4x4.com.

**Comment by yssagambit** [comment]
you can now choose a category for the Post Block
