### ISSUE TITLE
Some Columns block settings aren't working properly if Columns block is inside Query Loop block

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3109]
**Describe the bug**
- Issue only in editor. Works correctly on frontend
- Happens to query loop blocks such as:
    - WordPress Query Loop block
    - Advanced Posts block (Blocksy)  
- Settings in the Layout tab such as:
    - [ ] Inner Column Spacing - doesn't work
    - [ ] Column Gap - doesn't work
    - [ ] Row Gap - doesn't work
    - [ ] Block / Content Width - doesn't work
    - [ ] Content Max Width - doesn't work
    - [ ] Content Horizontal Align - doesn't work
    - [ ] Column Justify - not working properly

**To Reproduce**
1. Add a new page
2. Add a Query Loop block or Advanced Posts block
3. Add a Columns block inside the **Post Template** block
4. Try changing settings mentioned above
5. See that it doesn't work as expected

**Expected behavior**
Settings should work as expected. 

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/386ea31a-ccb0-49f4-9803-fb68fa9a4baf

**Comment by Arukuen** [comment]
Tried replicating the issue with both Query Loop Block and Blocksy Advanced Posts block, and it seems that the columns block is working properly. Can we verify if the issue still persists?

cc: @andeng1106 

https://github.com/user-attachments/assets/0a961955-0f47-409f-ab88-cc2d439e1822

**Comment by andeng1106** [comment]
@Arukuen I tried replicating on Sandbox what you experienced and it seems like it's still not working. Here's my test page [link](https://gambitsandbox.instawp.xyz/andrea/wp-admin/post.php?post=13942&action=edit). Let me know how it goes!

OS: Mac
Browser: Chrome
Theme Used: Blocksy

https://github.com/user-attachments/assets/74376094-5869-4f2a-b925-7b7857728ae1
