### ISSUE TITLE
ACF - When adding a list item in WYSIWYG editor field, it adds a <br> when displayed on text blocks in frontend

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3110]
**Describe the bug**
- Issue only with ACF
- Issue on text blocks
- Issue for the WYSIWYG field

**To Reproduce**
1. Add an ACF field group with WYSIWYG custom field
2. Set Post Type to Page
3. Add a new page
4. In the WYSIWYG field created on step 1, add this:
```
<ol>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ol>
```
5. Add any Stackable text blocks
6. Fetch the WYSIWYG field data using Dynamic Content
7. Save page and view frontend
8. See that there are spaces/line breaks after each list item
9. Inspect page and select the Text block
10. See that after each `<li></li>`, there's a `<br>`

**Expected behavior**
Should not encounter line breaks in each list item when fetching ACF WYSIWYG field data via Dynamic Content

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/5cc4531c-1ade-440b-b3fc-5f3f7e7fcf47

**Comment by bfintal** [comment]
Proposed solution: Let's add an option to ACF wysiwyg whether to allow line breaks or not
