### ISSUE TITLE
Column Arrangement issues with Carousel block

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3113]
**Describe the bug**
Two issues are visible:
- When there's an assigned Column Arrangement on tablet or mobile and there's a Carousel block present, it encounters:
   - Carousel Type > Slide - encounters strong flippings (usually on the third slide)
   - Carousel Type > Fade - the content disappears
- Issue on frontend only
- Issue for both tablet & mobile view
- Happens to blocks with Column Arrangement such as:
     - [ ] Columns
     - [ ] Feature
     - [ ] Feature Grid

**To Reproduce**
_**- Carousel Type > Slide**_
1. Add a new page
2. Add any of the blocks above (e.g. Columns block)
3. Add a Carousel block inside with at least 4 slides
4. Change Carousel Type to "Slide"
5. In the Columns block, change any Tablet or Mobile Column Arrangement setting
6. Save page and view frontend
7. Try clicking next until the third slide
8. Observe that the third slide encounters a strong flipping (which is supposed to happen only when navigating back to the 1st slide)

_**- Carousel Type > Fade**_
1. Add a new page
2. Add any of the blocks above (e.g. Columns block)
3. Add a Carousel block inside with at least 4 slides
4. Change Carousel Type to "Fade"
5. In the Columns block, change any Tablet or Mobile Column Arrangement setting
6. Save page and view frontend
7. See that the content disappeared

**Expected behavior**
- Carousel Type > Slide - Should not encounter strong flippings on the third slide
- Carousel Type > Fade - Contents inside the Carousel should not disappear

**Screenshots**
_**- Carousel Type > Slide**_

https://github.com/gambitph/Stackable/assets/103395655/ce5594fd-954c-4c15-bba5-1cebe965f9e2

_**Carousel Type > Fade**_

https://github.com/gambitph/Stackable/assets/103395655/48ecd0f3-44d5-4289-8be4-2d5b50e533ec

**Comment by bfintal** [comment]
Instead of forcing to make the arrangement option work for these special types of containers, let's just disable (hide) the option for them.

- Disable the column arrangement option for the carousel block
- If the issue also happens with the horizontal scroller (I doubt it), then we'll have to disable the option there too
- For feature & feature grid blocks, I'm not certain whether the issue applies to them
