### ISSUE TITLE
Card block becomes invalid when edited by a non-super admin user

### ISSUE THREAD

**Issue by alzanki** [gambitph/Stackable#314]
**Describe the bug**
Card block works fine when used by a user with super admin privilege. But when a non-super admin add or edit a card block. The block becomes invalid after refresh.

**To Reproduce**
Steps to reproduce the behavior: (by a non-super admin user)
1. add a card block
2. click save or publish
3. refresh the page

**Expected behavior**
The card block should stay editable.

**Screenshots**
![Screen Shot 2019-10-26 at 2 25 41 AM](https://user-images.githubusercontent.com/4064320/67610706-3f927600-f79d-11e9-9f73-3d6a1a0f7a58.png)
note: it's possible to recover the block by super admin.

Also, this's what I get in the browser console: https://paste.ofcode.org/eHTqdNk7RCa3gtBkugaAVG (not sure if it helps)

**Desktop:**
 - OS: [MacOS]
 - Browser: [Safari]
 - Browser Version: [13]

**Comment by bfintal** [comment]
Unfortunately, it's an ongoing issue across many block plugins. Closing this, please continue the discussion in #184
