### ISSUE TITLE
header 2nd button is placed directly below the 1st button on v2 free 

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#319]
![image](https://user-images.githubusercontent.com/50035760/67748712-849cfd80-fa66-11e9-8e46-12df9c2c2492.png)

**Comment by jkapunan** [comment]
Can't replicate in both basic & plain layouts. Can I have the steps to replicate? :) @mico97 @yssagambit 
<img width="1680" alt="Screen Shot 2019-11-20 at 1 49 59 AM" src="https://user-images.githubusercontent.com/14865936/69172137-3f855c00-0b38-11ea-8af4-23e7b0c6b6d7.png">

**Comment by yssagambit** [comment]
@jkapunan we just set the header block to full width then turned on the button 2. here's a video on how we did it. maybe it 

![ezgif-5-498ccdc1368a](https://user-images.githubusercontent.com/51441886/69205347-aa5c8480-0b84-11ea-90c8-a8d970b28a86.gif)
