### ISSUE TITLE
Accordion block - Accordion with HTML anchor is nested inside an Accordion, it's not recognized properly

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3192]
**Describe the bug**
- Happens to browsers such as:
  - Firefox
  - Safari
- Issue on frontend

**To Reproduce**
1. Add a new page (or skip steps 2-6 and use this [page](https://gambitsandbox.instawp.xyz/andrea/13584-2/))
2. Add an Accordion block
3. Inside the accordion content, add an Accordion block inside
4. Inside the nested Accordion block's content, add an Accordion block
5. In the Accordion block created in step 4, add an HTML Anchor
6. Save page and view frontend
7. Try typing in the URL the Accordion block's HTML anchor (e.g ...example.com/**#accordion-3**)
8. See that it doesn't scroll down and expand the Accordion

**Expected behavior**
- Should be recognized and expand even if the Accordion is nested inside another Accordion block

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/a07939ff-911e-4d60-b31b-3d732d046644

**Comment by bfintal** [comment]
Let's not handle this. It's difficult to handle these types of multiple nesting because if we handle one scenario there will be others. Let's just say that if you're doing it this way, then it's not recommended
