### ISSUE TITLE
[WP 6.6] Javascript errors on console related to Stackable

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3220]
**Describe the bug**
- Make sure that WP Debug is set to true
![image](https://github.com/gambitph/Stackable/assets/103395655/6b869b2e-20eb-40eb-8ecb-ff596f98917d)

**To Reproduce**
1. Add a new page
2. Add a Heading block
3. See console for this error: 
`Warning: pd: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/523b91e0-aa19-4cb9-8079-c3db7e57e615

**Comment by andeng1106** [comment]
@andeng1106 Comment out all stuff but keep `WP_DEBUG`

**Comment by andeng1106** [comment]
@bfintal Upon removing the other items and kept `WP_DEBUG`, the error is no longer visible.

**Comment by bfintal** [comment]
Closing this now :)
