### ISSUE TITLE
[WP 6.6] Lagging/freezing encountered when saving Stackable blocks as a Synced Pattern

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3229]
## Freezing
- Here's a [sample set of blocks](https://github.com/user-attachments/files/16061736/timeline.inside.columns.-.lagging.issue.txt) that freezes when creating/adding to page as a new synced pattern
- Also related to: https://github.com/gambitph/Stackable/issues/3226

- Columns block with nested Timeline blocks

   https://github.com/gambitph/Stackable/assets/103395655/aae518ea-f26d-4a9c-bbed-643d893f49e7

---

## Lagging 
- Here are sample videos of the lagging that happens whether saving a nested or single block as a new synced pattern

**Actual/Issue (WP 6.6):**
- Nested:

   https://github.com/gambitph/Stackable/assets/103395655/5d75a7ab-fb5d-4058-a920-22e4d1ff5efe

- Single (no stylings):

   https://github.com/gambitph/Stackable/assets/103395655/d4925e74-4072-48d3-9c9c-71781d4b2dfc

**Expected (WP 6.5 and older):**
- Nested

   https://github.com/gambitph/Stackable/assets/103395655/90fee58b-d9a2-40cf-9c04-9d03ce034fcc

- Single (no stylings):

   https://github.com/gambitph/Stackable/assets/103395655/59624ec1-cbcc-477d-8821-5c86a02606e5

**Comment by andeng1106** [comment]
@andeng1106 Test out on WP 6.6 RC3 (Jul. 10)

**Comment by bfintal** [comment]
@mxkae, @Arukuen & @andeng1106 I feel that #3201 might solve this
