### ISSUE TITLE
Image block - If image has a small size/dimensions, it appears bigger when uploading in Stackable Image block

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3231]
**Describe the bug**
- Compared to uploading in WP Native Image block, the image appears bigger when uploading a small sized image in Stackable Image block
- Smaller images doesn't look as same as their image size when uploading as a Stackable Image block

**To Reproduce**
1. Add a new page
2. Add a new Stackable Image block
3. Upload this image
![landscape](https://github.com/gambitph/Stackable/assets/103395655/37ffeb4c-a3f3-4b67-83ad-77d15bb38302)
4. Add a new WordPress Image block
5. Repeat step 3
6. Compare the difference between Stackable & WordPress Image block's image size
7. See that the Stackable Image appears a bigger even though the original image is small

**Expected behavior**
- Smaller images should look as same as their image size when uploading as a Stackable Image block
- Expected result is the same when uploading the image in a WordPress Image block

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/eb877fa3-99c6-4099-90ab-d8353f70026e

**Comment by bfintal** [comment]
@andeng1106 this is expected. Our Image block occupies the entire width of the content unlike the native image block.
