### ISSUE TITLE
JS Error in rich-text.min.js

### ISSUE THREAD

**Issue by nicmare** [gambitph/Stackable#325]
**Describe the bug**
Plugin works but JS Console prints this error msg:

> Format "ugb/highlight" is already registered to handle bare tag name "span".

**To Reproduce**
Install stackable and load any gutenberg editor page

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: 78

**Comment by bfintal** [comment]
This has already been reported to Gutenberg and they're working on the fix: https://github.com/WordPress/gutenberg/pull/15072 :)

**Comment by bfintal** [comment]
Fixed in WordPress 5.3
