### ISSUE TITLE
Slim SEO with Accordion block slowdown

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3260]
**Describe the bug**
- When adding multiple Accordion blocks in a page while Slim SEO is activated, the page lags.
- Might be connected to: https://github.com/gambitph/Stackable/issues/2633

**To Reproduce**
1. Activate [Slim SEO](https://wordpress.org/plugins/slim-seo/) plugin
2. Add a new page
3. Add an Accordion block
4. Duplicate Accordion block at least 5 or more times
5. Observe that there's a lag when typing, selecting items in list view, etc.

**Expected behavior**
Accordion block added should not cause a slowdown/lagging when Slim SEO is activated

**Screenshots**

https://github.com/user-attachments/assets/79f982c7-c370-4a31-9cf2-369f10863587

**Comment by bfintal** [comment]
This has been fixed by the recent editor performance update
