### ISSUE TITLE
[WP 6.6] Stackable blocks with WP 6.6 causes slow down

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3261]
**Describe the bug**
- When using this sample Stackable blocks on WP 6.6, it causes slow down/lagging: 
[sample stackable blocks - wp 6.6 issue.txt](https://github.com/user-attachments/files/16345216/sample.stackable.blocks.-.wp.6.6.issue.txt)

- Issue doesn't happen on WP 6.5

**To Reproduce**
1. Make sure WordPress version is set to 6.6
2. Add a new page
3. Add the sample Stackable blocks
4. Observe slow down (typing, selecting blocks in list view, moving blocks around, etc.

**Expected behavior**
A page with Stackable blocks should not encounter slow down when using WP 6.6

**Screenshots**
[tba]

**Comment by bfintal** [comment]
Re-opening because this one still occurs even with the fix @mxkae
