### ISSUE TITLE
When default text block is Stackable Text block, I'm unable to paste Text blocks properly

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3330]
**Describe the bug**
- Related to this new feature: https://github.com/gambitph/Stackable/issues/3279
- It only copies the text content and not the whole text block
- Issue happens when trying to paste any text block on a Stackable Text block or a WordPress Paragraph block
- Text blocks such as:
   - Heading
   - Subtitle
   - Text
   - Icon List (becomes a normal Text block)
- Native WordPress text blocks and other third party block plugins are also affected
- Issue happens if this Stackable setting is enabled:
<img width="963" alt="Screenshot 2024-09-27 at 8 38 02 AM" src="https://github.com/user-attachments/assets/6fe5023d-6191-47d7-a597-0ace31d318bd">

**To Reproduce**
1. Go to Stackable settings
2. Enable "Stackable Text as Default Block" setting
3. Add a new page
4. Add any text block (e.g. Heading)
5. Add any stylings
6. Copy block
7. Add a new Stackable Text block or Paragraph block
8. Paste the Heading block
9. See that it only pastes the text content

**Workaround**
- Turn off the default text block setting first when copying the blocks listed above

**Expected behavior**
- Should still be able to paste the whole block

**Screenshots**

https://github.com/user-attachments/assets/93912b82-dea6-49e8-b11f-24a2a33a319f

**Comment by Arukuen** [comment]
The issue exist even before the previous version without the implementation of Stackable default block. The pasting of block works fine with Native Paragraph but not on Stackable Text block.

https://github.com/user-attachments/assets/973650be-5c6c-4cda-82a9-bd249e46ff31

**Comment by andeng1106** [comment]
@Arukuen I see. For the current version, pasting in the Native Paragraph block doesn't work also if the setting is enabled. Is it possible to be fixed even for the Paragraph block only?

@bfintal I'd like to ask if ever we'll support this for Stackable text blocks (currently can't paste another Stackable text block inside), can I file this as another issue instead?
