### ISSUE TITLE
[WP 6.7] Fix deprecation errors in console

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3336]
- [x] `wp.compose.withState is deprecated since version 5.8. Please use wp.element.useState instead.`
<img width="423" alt="Screenshot 2024-10-02 at 10 30 52 AM" src="https://github.com/user-attachments/assets/325c4df3-8ba1-405c-b97d-4fa5842538e7">

---------

- [x] `select( 'core/edit-site' ).__experimentalGetPreviewDeviceType is deprecated since version 6.5 and will be removed in version 6.7. Please use select( 'core/editor' ).getDeviceType instead.`
<img width="421" alt="Screenshot 2024-10-02 at 10 28 15 AM" src="https://github.com/user-attachments/assets/c217292d-60c9-4958-abbb-48b8a8223110">

---------

- [ ] `select( 'core/edit-post' ).isEditingTemplate is deprecated since version 6.5. Please use select( 'core/editor' ).getRenderingMode instead.`
<img width="426" alt="Screenshot 2024-10-02 at 10 29 02 AM" src="https://github.com/user-attachments/assets/2af4a337-0781-4c67-9ba3-93b2412c0bdc">

---------

- [x] `wp.blockEditor.useSetting is deprecated since version 6.5. Please use wp.blockEditor.useSettings instead.`
<img width="425" alt="Screenshot 2024-10-02 at 10 29 29 AM" src="https://github.com/user-attachments/assets/ff8d429f-11b6-48cd-a5dc-903d62e5520a">

---------

- [x] `wp.editPost.PluginSidebar is deprecated since version 6.6. Please use wp.editor.PluginSidebar instead.`
<img width="421" alt="Screenshot 2024-10-02 at 10 31 31 AM" src="https://github.com/user-attachments/assets/1070e2a7-d99f-471b-82cf-e3e3139463f5">

---------

- [x] `wp.editPost.PluginSidebarMoreMenuItem is deprecated since version 6.6. Please use wp.editor.PluginSidebarMoreMenuItem instead.`
<img width="427" alt="Screenshot 2024-10-02 at 10 32 26 AM" src="https://github.com/user-attachments/assets/5b82f585-fa20-4125-82df-cb881a87aa02">

----------

- [x] `Using custom components as toolbar controls is deprecated since version 5.6. Please use ToolbarItem, ToolbarButton or ToolbarDropdownMenu components instead. See: https://developer.wordpress.org/block-editor/components/toolbar-button/#inside-blockcontrols`
<img width="424" alt="Screenshot 2024-10-02 at 10 33 59 AM" src="https://github.com/user-attachments/assets/a99703bd-234e-48bf-bc8b-6bf3027215fe">

----------

- [x] `wp.blockEditor.RichText onSplit prop is deprecated since version 6.4. Please use block.json support key: "splitting" instead.`
<img width="423" alt="Screenshot 2024-10-02 at 10 33 25 AM" src="https://github.com/user-attachments/assets/bfa03ed1-a833-4869-9ed4-b5ea7bb6740d">

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Arukuen** [comment]
The deprecated `select( 'core/edit-post' ).isEditingTemplate` will not be converted to `select( 'core/editor' ).getRenderingMode` yet since the newer implementation has some inconsistencies.
