### ISSUE TITLE
[WP 6.7] Link / URL field overlaps in the editor and Dynamic Content button is missing

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3356]
**Describe the bug**
- The Link / URL field overlaps if there's no link present
    - If I add a link, it shows the dynamic content

**To Reproduce**
1. Add a new page
2. Add any Stackable block with Link tab (e.g. Card)
3. Go to Link tab
4. See if Link / URL field overlaps and Dynamic Content button is also missing

**Expected behavior**
- Link / URL field should not overlap if there's no link present
- Dynamic Content button should be beside the Link / URL

**Screenshots**

https://github.com/user-attachments/assets/392e0425-9eac-4d29-883e-8cc0f8f5447f

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
