### ISSUE TITLE
[WP 6.7] Countdown block - When selecting a date in the calendar, the highlight color overlapped the number

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#3357]
**Describe the bug**
When a date is selected in the calendar, the digit is not seen and might be overlapped by the highlight color

**To Reproduce**
1. Add a new page
2. Add a Timeline block
3. In the DATE section, select any date
4. See that the digit is not visible

**Expected behavior**
![image](https://github.com/user-attachments/assets/74e3aba9-74b5-422f-96c9-041953c1823e)

**Screenshots**
- See that the “31” is no longer visible

![image](https://github.com/user-attachments/assets/1930b2f5-fb1e-4936-bb14-177cd444f139)

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
