### ISSUE TITLE
The Half layouts from Feature, Card and Team Member should also have the "Collapse image on Mobile" option 

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#339]
**Describe the bug**
The Half layouts from Feature, Card and Team Member should also have the "Collapse image on Mobile" option 

![image](https://user-images.githubusercontent.com/51441886/68840186-2b3afc80-06fd-11ea-883d-4c24f63fcfe4.png)

**Comment by jkapunan** [comment]
They already collapse automatically. No need for a toggle.
