### ISSUE TITLE
 divider goes off screen on mobile when aligned right and height is large

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#350]
![divider2](https://user-images.githubusercontent.com/50035760/69117754-bc2e2100-0acb-11ea-9509-60d8a607b2b7.png)

**Comment by yssagambit** [comment]
the issue is only fixed on Premium version

Free Version:
![image](https://user-images.githubusercontent.com/51441886/69312140-1dd7c200-0c69-11ea-9961-4fb8fa76afb7.png)
