### ISSUE TITLE
divider reset options not working properly

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#351]
- resetting divider width changes the value to 100% instead of the default 50%

- divider disappears in editor when resetting height (it appears in the front end and is resetted 
properly)

![image](https://user-images.githubusercontent.com/50035760/69118071-09f75900-0acd-11ea-8dbc-873657fde985.png)
![image](https://user-images.githubusercontent.com/50035760/69118105-23000a00-0acd-11ea-901d-cdfd3be92d64.png)

**Comment by yssagambit** [comment]
Already fixed for Basic and bar layouts.

For the Dots and Asterisks layouts, resetting the Height / Size will make them disappear 

![ezgif-1-56aaa5f9545a](https://user-images.githubusercontent.com/51441886/69311759-1d8af700-0c68-11ea-8e0c-b6ee2d346ef7.gif)
