### ISSUE TITLE
Accordion does not close/open in IE

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#4]
**Describe the bug**
Originally reported here: https://wordpress.org/support/topic/accordion-does-not-work-wit-latest-ie/

Accordion block doesn't close/open in IE (check also in Edge)

**To Reproduce**
1. Add Accordion block
2. Preview in frontend
3. Click the title to toggle

**Expected behavior**
Accordion should collapse/expand upon click.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Check if IE 11 or Edge

**Comment by Gambit-Alyssa** [comment]
**Screencast**

EDGE [https://screencast-o-matic.com/watch/cqVZ1z3Okq](url)
Working properly

IE11 [https://screencast-o-matic.com/watch/cqVZ1k3Oku](url)
Accordion doesn't collapse

**Comment by bfintal** [comment]
https://github.com/gambitph/Stackable/blob/0e41f6993a3549713aa3e536b00a72ecf2981f52/src/block/accordion/frontend.js#L9-L12

IE11 doesn't have `NodeList.prototype.forEach`
