### ISSUE TITLE
Separators inside accordions are off center in back end when set to full width 

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#405]
the visual bug only happens when in full width. there does not seem to be any visual difference from non full width separators when inside an accordion in the front end.
Back End
![image](https://user-images.githubusercontent.com/50035760/69332015-c6e5e300-0c90-11ea-80ac-e50ad2fb9304.png)

Front End
![image](https://user-images.githubusercontent.com/50035760/69332047-d6fdc280-0c90-11ea-9839-ac70b26870d3.png)

**Comment by yssagambit** [comment]
already fixed on 2020 theme, but not on 2019 theme.

2020 theme:
![image](https://user-images.githubusercontent.com/51441886/69516216-ff850580-0f8b-11ea-8400-00cc80dc2b5d.png)


2019 theme:
![image](https://user-images.githubusercontent.com/51441886/69516213-fbf17e80-0f8b-11ea-92b8-9268ef11aa22.png)
