### ISSUE TITLE
Text & Highlight button closes when selecting a color from the gradient picker

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#414]

**Comment by bfintal** [comment]
This issue will be fixed when this is merged https://github.com/WordPress/gutenberg/pull/17617

**Comment by yssagambit** [comment]
This issue should be fixed in https://github.com/WordPress/gutenberg/pull/19536

Recheck in WordPress v5.4

**Comment by blankart** [comment]
Already resolved
