### ISSUE TITLE
clicking the text alignments removes the layout of the button (changes back to basic)

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#421]
**Describe the bug**
clicking the text alignments removes the layout of the button (changes back to basic)

![ezgif-1-3b27b4923db2](https://user-images.githubusercontent.com/51441886/69401776-eaf90100-0d30-11ea-8a5b-f17baa193371.gif)

**Comment by jkapunan** [comment]
This is the correct behavior. 

`// If the alignment was changed, but the design doesn't support it, go back to the basic design to allow the alignment change.`

@bfintal
