### ISSUE TITLE
spacer height retains value when switching from px to vh

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#423]
this can lead to values over the slider limit

![Edit-Page-‹-Test-Site-—-WordPress-Brave-2019-11-22-15-28-30](https://user-images.githubusercontent.com/50035760/69406680-96a84e00-0d3d-11ea-8692-14e946cd3fa1.gif)

**Comment by yssagambit** [comment]
the issue applies to all attributes that have VH and PX options.

**Comment by yssagambit** [comment]
maybe it is better to change the max of VH as same as the max of PX.

**Comment by yssagambit** [comment]
The fix will be too complicated for a low priority fix.
