### ISSUE TITLE
Post block contents does not show as excerpt in a post/page

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#430]
When displaying excerpts of pages or posts in a post block, if those pages have post blocks, then the contents of that post block is not shown as an excerpt. however, they are shown in the back end

Back End
![image](https://user-images.githubusercontent.com/50035760/69421886-345f4580-0d5d-11ea-962e-371cbb1ce954.png)

Front End
![image](https://user-images.githubusercontent.com/50035760/69421918-44772500-0d5d-11ea-89ec-af0db6760ae4.png)

Post Page
![image](https://user-images.githubusercontent.com/50035760/69421940-58228b80-0d5d-11ea-90e0-d03ee9cf277f.png)

**Comment by jkapunan** [comment]
Won't fix.
