### ISSUE TITLE
Expand "show less" link does not break line when the more text is only 1 line long

### ISSUE THREAD

**Issue by mico97** [gambitph/Stackable#441]
issue is present in stackable theme, does not appear in twenty nineteen

**EDIT:** 
- issue is present in both themes
- issue appears even with text in the show less section
- issue appears when the show more section is only 1 line long and if there is enough space in the line to fit the "show less" link

BACK END
![image](https://user-images.githubusercontent.com/50035760/69476060-e6574a00-0e0f-11ea-92c3-8cdfb33cfa92.png)

FRONT END
![image](https://user-images.githubusercontent.com/50035760/69476066-f96a1a00-0e0f-11ea-8589-0a6786096a8c.png)

**Comment by yssagambit** [comment]
2019 theme only
