### ISSUE TITLE
Accordion Block: Auto-minimize when expanding another accordion

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#48]
https://wordpress.org/support/topic/accordions-minimize-when-you-open-another-one/

**Is your feature request related to a problem? Please describe.**
I want accordions to open one at a time.

**Describe the solution you'd like**
This is applicable to multiple accordion blocks. There should be an option to automatically collapse the other accordions when you expand another.

**Comment by bfintal** [comment]
Add a new toggle option that forces other adjacent Accordion blocks to close.

Helpful snippets to get the job done:

```js
// Get the data of a block
wp.data.select( 'core/editor' ).getBlocks()[0]

// Update attributes of another block
// wp.data.dispatch( 'core/editor' ).updateBlockAttributes( clientID, attributes )
wp.data.dispatch( 'core/editor' ).updateBlockAttributes( '10d88a6d-95d6-4e07-8293-5f59c83a26c0', { heading: 'New Heading' } )

// Get currently selected block.
wp.data.select( 'core/editor' ).getBlockSelectionStart()
```
