### ISSUE TITLE
Content Vertical Align not working on these blocks/layouts:

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#489]
Content Vertical Align not working:
- [x] header half overlay (if full height) 
- [x] count up 
  - [x] plain
  - [x] plain2
  - [x] side
  - [x] boxed
- [x] container
  - [x] image 2
  - [x] image 3
- [x] team member
  - [x] half
  - [x] overlay and overlay simple should not have content vertical align
- [x] post

Blocks that don't have Column Vertical Align but should:
- [x] Count Up
- [x] Number Box
- [x] Feature Grid
- [x] Card
- [x] ~Image Box~
- [x] Post

Column Vertical Align not working on these blocks/layouts:
- [x] testimonial
  - [ ] ~bubble layout, stretch is not working~

**Comment by bfintal** [comment]
Removed column vertical align option for posts block

**Comment by bfintal** [comment]
This should be okay: bubble layout, stretch is not working
