### ISSUE TITLE
Post Block: Full Post Content

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#49]
https://wordpress.org/support/topic/full-width-button-option/

**Is your feature request related to a problem? Please describe.**
I want an option to show full post content.

**Describe the solution you'd like**
Create an option to add full post content or a toggle to show full content on post blocks.

**Comment by dtmpsc** [comment]
Sorry for the erroneous link verbiage. Edited after posting.

**Comment by yssagambit** [comment]
Sorry but we've decided to limit the Post block to use only excerpts.
