### ISSUE TITLE
Stackable 2: only brand icons

### ISSUE THREAD

**Issue by nicmare** [gambitph/Stackable#491]
<img width="269" alt="Bildschirmfoto 2019-11-26 um 13 35 13" src="https://user-images.githubusercontent.com/898582/69634042-b4cdc100-1051-11ea-9b00-0c45f05247ee.png">

WP 5.3, STACKABLE 2.0, CountUp Block

**Comment by bfintal** [comment]
I'm sorry, what's the issue here?

**Comment by nicmare** [comment]
i was wondering about the icons. what kind of icons are these? **thats all** i can pick from. seems like company/brand icons. you have to use the search in order to see more icons like arrows. but where do i know what kind of icons are available if i don't know the search term?

**Comment by bfintal** [comment]
They're sorted alphabetically at the start (so "accessibility" and "creative commons" ones are shown) and then only a few are shown to not clog the list. They're FontAwesome icons :)

**Comment by nicmare** [comment]
yes. i already noticed. btw i am font awesome pro user. how to add my fontawesome pro kit to have more icons available?

**Comment by bfintal** [comment]
Oh, there's no way as of the moment to add more or use FontAwesome Pro :( Currently everyone's limited to just the free ones from FontAwesome

**Comment by bfintal** [comment]
This issue has been addressed by version 2.7 already
