### ISSUE TITLE
Lost control over transparency in Accordion title bar

### ISSUE THREAD

**Issue by RolfKyburz** [gambitph/Stackable#493]
I can control the transparency of the Accordion background color in the body, through Custom CSS entries. I can apparently also control the transparency of the title font. However, since my site upgraded to Stackable version 2.0.1, it seems impossible to make the accordion header line transparent, which leaves an ugly white bar in my layout. Prior to the upgrade to 2.0.1, this used to work just fine. Somewhere, the transparency segment of the color seems to be stripped — or something is overriding the background color setting for the title line? One example: https://www.rolf-musicblog.net/

 - OS: MacOS
 - Browser: Chrome / Safari
 - Browser Version: 78.0.3904.108 / 13.0.3

**Comment by bfintal** [comment]
Hi @RolfKyburz are things okay now?

**Comment by RolfKyburz** [comment]
Hi — thanks for checking back. I managed to fix this through controls (CSS) in the sidebar. Doing this through global Custom CSS (another plugin) doesn't seem to work, which still worries me, as I may have to fix some 150 blog posts through meticulous modifications in the sidebar. I'd rather prefer a set of global CSS settings for all of my blog posts.
On a related note: at the front end, there is now (since 2.0.1) a box around the title bar that I'm unable to disable. Plus, the Accordion  block somehow forces some extra white space under the title (closed) or under the content (open)—no idea where that comes from (maybe from the chain of **six** subsequent </div> near the end of the Accordion code??). Sigh ...

**Comment by bfintal** [comment]
@RolfKyburz The 6 end div tags at the end are because we standardized the structure of all the blocks, in order to include some of the advanced controls, css generation and others.

> as I may have to fix some 150 blog posts through meticulous modifications in the sidebar.

If you have a sample page containing your accordions, let me know what you're trying to achieve and I can try and see on whether I can help you out in crafting some CSS to make them work.

> there is now (since 2.0.1) a box around the title bar (as soon as the title bar is selected) that I'm unable to disable

We've added that in pre-v2 for accessibility. Although now though since the styles have been updated in v2, they're probably harder to get rid of. 

You can use this CSS to get rid of the outline when the accordion title is focused:

```css
.ugb-accordion.ugb-accordion--v2 .ugb-accordion__heading:focus {
    outline: none;
}
```

or

```css
.ugb-accordion.ugb-accordion--v2 .ugb-accordion__heading:focus {
    outline: none !important;
}
```

**Comment by RolfKyburz** [comment]
Hi @bfintal — thanks again. Yes, I can indeed disable the focus box with your CSS addition, thanks. **However**, this only works when I change the CSS locally, at the very instance  in my posting. This does nothing for me, as I can't afford to amend 150 instances "by hand", and even just for new blog posts, I don't want to think about this every time. I want to be able to set this in a **global** fashion (i.e., in my custom CSS), once and for all—and without having to mess around with the plugin's internals (as such modifications would be lost with the next update). One example where I have *locally* disabled the box is at https://www.rolf-musicblog.net/merel-quartet-zurich-2019-09-22/ — the box is gone, but that shows the extra white space below either the accordion header (closed) or at the bottom of the accordion content (when open). Finally, it's nice that you add tons of new controls for the layout—however, if that only is accessible locally, it does nothing to me (see above)—why not give users the possibility to set the style properties of the accordion for **all** instances in a site: after all, isn't this why CSS were invented in first place?

**Comment by bfintal** [comment]
@RolfKyburz Sorry, I forgot to mention to add that CSS in your Customizer → Additional CSS. That would make it apply everywhere :)

As for the properties of all instances, that's actually one of our goals for either v2.2-v2.4 - slated for Q1 or Q2 next year. No definite schedule yet though and we're still throwing ideas around on how such a thing would work in the block editor since I would think that nobody has done this yet.

**Comment by RolfKyburz** [comment]
Hi @bfintal, yes Customizer → Additional CSS seems to do the job. I have been using the Custom CSS plugin to customize fonts, etc. (started probably at a time when the Customizer → Additional CSS wasn't available yet?). Custom CSS works for all my blog, including widgets, etc., *except* the Stackable plugin (or at least the Accordion component, which is the only one I use right now). So, I suspect that Stackable somehow does not follow the standard WP CSS hierarchy? I'm a bit wary of transferring all of my detailed Custom CSS contents to "Additional CSS" — my blog content is huge, so there is a lot at stake...

**Comment by yssagambit** [comment]
I created a new issue #600 that takes care of what you are looking for.

I'm closing this issue, since the original issue was solved already.
