### ISSUE TITLE
Accordion Block: Anchor Links to expanded accordion block

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#51]
https://wordpress.org/support/topic/scroll-to-accordion-header-on-expansion/
with reference to #16 

**Is your feature request related to a problem? Please describe.**
I want an option to scroll to the accordion (and expanded) using anchored links (with reference to Custom IDs)

**Describe the solution you'd like**
Anchor links to accordions should be automatically expanded.

**Comment by yssagambit** [comment]
This sounds like a special case that can be handled with custom Javascript code. We will not pursue this feature. Hope you understand. :)
