### ISSUE TITLE
Video Popup: Only open video popups in mobile when you tap the image

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#52]
https://wordpress.org/support/topic/video-popup-opens-on-scroll-not-tap-iphone/

**Is your feature request related to a problem? Please describe.**
Scrolling in your page or touching the image preview will open the video popup.

**Describe the solution you'd like**
Change video popup trigger: only open the video when you tap

**Comment by emendoza2** [comment]
I'm getting the same issue as well. I think the problem is with the "touchend" event listener in [https://github.com/gambitph/Stackable/blob/master/src/block/video-popup/frontend.js](video-popup/frontend.js).

**Comment by IDisposable** [comment]
I end up having to comment out the body of the touchend handler in the actual dist file /stackable-ultimate-gutenberg-blocks/dist/frontend_blocks.js

**Comment by yssagambit** [comment]
Reopening this issue. The issue hasn't been fixed yet.
