### ISSUE TITLE
Title color and Hover color is not changing on backend

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#533]
Title color and Hover color is not changing on backend

Image Card layout only

Backend:
![image](https://user-images.githubusercontent.com/51441886/70618705-7984e200-1c4e-11ea-87c7-571417fc178a.png)

Frontend:
![image](https://user-images.githubusercontent.com/51441886/70618731-86a1d100-1c4e-11ea-8893-02810d5d588f.png)

**Comment by blankart** [comment]
Already resolved. Closing this issue.
