### ISSUE TITLE
when you've change the Image Shape (on Style tab), then change the Stretch Shape Mask (on Advance tab) it will not change

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#536]
when you've change the Image Shape (on Style tab), then change the Stretch Shape Mask (on Advance tab) it will not change

![ezgif-5-d71503e1fe5a](https://user-images.githubusercontent.com/51441886/70620105-57409380-1c51-11ea-9bf0-833898825806.gif)

**Comment by blankart** [comment]
Additional note: Switching the image shape first before toggling the Stretch Shape Mask solves the issue for now.
