### ISSUE TITLE
upgrading to V2, the z-index of the separator is not that high (V1 upgrading to V2)

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#537]
upgrading to V2, the z-index of the separator is not that high

instead of the separator is on top of an image native block, the separator is on the bottom

V1 upgrading to V2, then click Preview

![image](https://user-images.githubusercontent.com/51441886/70620398-1e54ee80-1c52-11ea-937a-b1f2d7998f5d.png)

**Comment by yssagambit** [comment]
Must be 
```
.ugb-main-block {
    z-index: 1;
}
```

instead of
```
div[class^=wp-block-] {
     z-index: 1; 
}
```

**Comment by bfintal** [comment]
Can no longer recreate the error in v2.1
