### ISSUE TITLE
IE11 Fallback Styling

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#54]
https://wordpress.org/support/topic/css-variables-ie/

**Is your feature request related to a problem? Please describe.**
IE11 doesn't support CSS variables, some block styling may be missing in IE11.

**Describe the solution you'd like**
Create fallback styling for IE11.

**Comment by nuxodin** [comment]
Maybe this polyfill helps:
https://github.com/nuxodin/ie11CustomProperties
