### ISSUE TITLE
Title, Price Prefix, Price, Price Suffix and Sub Price wont change color

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#541]
frontend and backend
for colored layout - Title, Price Prefix, Price, Price Suffix and Sub Price
for sectioned layout - Title

![image](https://user-images.githubusercontent.com/51441886/70695520-df2fa780-1cfc-11ea-90cf-51482361b3fe.png)

**Comment by blankart** [comment]
Fixed in v2.11.0
