### ISSUE TITLE
Mobile responsiveness for font size is not working

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#544]
Mobile responsiveness for font size is not working for the following text:
 - [x] All Buttons
 - [x] Testimonial - ~Body and~ Position
 - [x] Post - Excerpt
 - [x] Count Up - Number
 - [x] Icon List - List Text

**Comment by bfintal** [comment]
Fixed by c06ff474655528076b4d20bc98991cba6c59c61b
