### ISSUE TITLE
Icon List adds extra bullets beside it when using Genesis Theme

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#55]
https://wordpress.org/support/topic/icon-list-bullet-still-visible/

**Describe the bug**
Icon List is producing extra bullets beside it.

**To Reproduce**
1. Create an Icon list and save
2. Extra bullets will appear upon viewing the page

**Expected behavior**
There should be no extra bullets beside the list.

**Screenshots**
![chrome_zyywvlfou0](https://user-images.githubusercontent.com/11436202/52619761-95f4a880-2edd-11e9-9580-e390b3ba003e.png)

**Comment by bfintal** [comment]
Please provide a quick fix CSS to forcibly remove the bullets

**Comment by Gambit-Alyssa** [comment]
Temporary Fix:
`.ugb-icon-list li {
    list-style: none !important;
}`
