### ISSUE TITLE
Icon List: Icons doesn't show in IE11

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#56]
https://wordpress.org/support/topic/display-issues-with-ie11/

**Describe the bug**
Icons from Icon List doesn't show in IE11. It seemed that the problem may be related to #54 

**To Reproduce**
1. Create Icon List and Save.
2. View in IE11

**Expected behavior**
The Icons should show beside the list.

**Screenshots**
Chrome:
![chrome_6uwkasyuc9](https://user-images.githubusercontent.com/11436202/52622685-68abf880-2ee5-11e9-8c41-e45fb53afffb.png)

IE11:
![iexplore_ubx1ylkw3r](https://user-images.githubusercontent.com/11436202/52622698-71043380-2ee5-11e9-9bfc-f997303a0bc4.png)

**Desktop (please complete the following information):**
 - Browser: IE11

**Comment by bfintal** [comment]
This was fixed previously and IE11 falls back to the default bullet points
