### ISSUE TITLE
Spacing (for Number) and Number Alignment are not working on mobile

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#570]
Spacing (for Number) and Number Alignment are not working on mobile

this is for Abstract Layout

Spacing (Backend)
![image](https://user-images.githubusercontent.com/51441886/71664161-e6455500-2d92-11ea-9874-69ed638ee3d1.png)

Number Alignment Backend
![image](https://user-images.githubusercontent.com/51441886/71664209-1f7dc500-2d93-11ea-92e9-cd53225f4b8e.png)

On mobile
![image](https://user-images.githubusercontent.com/51441886/71664192-06751400-2d93-11ea-9067-c18d7b11d0c5.png)

**Comment by blankart** [comment]
Spacing and Number Alignment is already fixed
