### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by bigvibes909** [gambitph/Stackable#575]
Whenever I go to publish or update a post I get this error: “Updating failed. Error message: The response is not a valid JSON response.”

which prevents me from publishing / updating. The problem only happens when I'm using Stackable elements (namely buttons) so that's how I know it's a Stackable problem.

Any ideas how to fix this?

**To Reproduce**
1. Go to a page or post
2. Create a button
3. Try publishing or saving

**Comment by yssagambit** [comment]
1. Head over to Settings > Permalinks, then click on Save Changes. Afterwards, check whether the saving error still occurs.

2. You may have some debugging or performance plugin or setting turned on that occasionally places in performance metrics on pages, mostly things that measure "Peak Memory Usage" or the number of "SQL Queries". Turn those off and check whether that fixes the saving issue.

https://rudrastyh.com/gutenberg/updating-failed.html
