### ISSUE TITLE
Accordion's content height problem

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#581]
the accordion not registering the correct height for the content

![image](https://user-images.githubusercontent.com/51441886/72697420-e6a76380-3b7a-11ea-9dca-6e41d6419b13.png)

**Comment by yssagambit** [comment]
This code fixes the issue:

`.ugb-inner-block {
    --max-height: auto !important;
}
`

**Comment by yssagambit** [comment]
https://www.mcgowantranscriptions.co.uk/about-us/transcription-templates/

**Comment by bfintal** [comment]
Fixed by fc8b17babce55d0c56db751051c0193e46e571f1
