### ISSUE TITLE
Preventing Slides plugin from working

### ISSUE THREAD

**Issue by dartiss** [gambitph/Stackable#587]
I don't know if this is an issue with Stackable or Slides, but installing both (Slides is https://wordpress.org/plugins/slide/) causes an issue with Slides, where you can't edit a slide.

Recreate...

1. Install and activate both plugins
2. Head to Presentations -> Add New 
3. Try clicking into the slide and nothing happens. 
4. Deactivate Stackable
5. Try adding a presentation again
6. Clicking into the slide now allows you to edit it

**Comment by bfintal** [comment]
Thanks for the report! Yes it's something in Stackable.
