### ISSUE TITLE
Wordpress sent me a message Stackable - Gutenberg Blocks is broken

### ISSUE THREAD

**Issue by livinginbauty** [gambitph/Stackable#588]
Here is the message I got a few minutes ago: 

An error of type E_COMPILE_ERROR was caused in line 19 of the file /srv/htdocs/wp-content/plugins/stackable-ultimate-gutenberg-blocks/freemius.php. Error message: require_once(): Failed opening required '/srv/htdocs/wp-content/plugins/stackable-ultimate-gutenberg-blocks/freemius/start.php' (include_path='/:.')

**Comment by bfintal** [comment]
@livinginbauty Is Stackable working while in your Block Editor?

**Comment by yssagambit** [comment]
To be addressed by Freemius.
