### ISSUE TITLE
Container Column Paddings (right and left) are not working

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#592]
Container Column Paddings (right and left) are not working

Backend
![image](https://user-images.githubusercontent.com/51441886/74118807-f0f7d300-4bf7-11ea-9155-2d388c1eb38d.png)

Frontend
![image](https://user-images.githubusercontent.com/51441886/74118836-0e2ca180-4bf8-11ea-8eaa-e69c1759cb1e.png)

**Comment by bfintal** [comment]
This is connected to #678
