### ISSUE TITLE
Make sure images are responsive (filesize-wise)

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#6]
**Is your feature request related to a problem? Please describe.**
Right now, all images are not responsive, no `srcset` no `sizes`.

**Describe the solution you'd like**
All images should be responsive.

- Add class `wp-image-<ID>` on all <img> in saves to trigger automatic placement of `srcset` and `sizes`
- Instead of just saving the image URL, let the user pick the image size (e.g. thumbnail, medium, etc), then save the image URL of that corresponding size, then also let the user pick the `width` and `height` of the image.
- Get the registered image sizes from 
 `wp.data.select( 'core/editor' ).getEditorSettings().imageSizes`
- Get the actual image sizes from `wp.data.select( 'core' ).getMedia( <ID> )`, but we will need to use `withSelect` for this, see bottom of [packages/block-library/src/image/edit.js](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/image/edit.js#L706-L721) for implementation on how they query the sizes of an image, and [`getImageSizeOptions`](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/image/edit.js#L331-L343) on how to use them.

**Comment by nickwinder** [comment]
Is this staged to be worked on? Is there a workaround that could be applied as this is harming load speeds for users.

**Comment by bradenheckman** [comment]
I'm just emphasizing that background images in blocks such as Image Block should also be made responsive with the appropriate CSS Media Queries.

**Comment by nickwinder** [comment]
@bfintal I see this isn't in any of the V2 milestones? Are we going to be seeing responsive images in the update? Thanks
