### ISSUE TITLE
Posts Block: Make links clickable

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#60]
https://wordpress.org/support/topic/links-dont-appear-in-post-block/

**Is your feature request related to a problem? Please describe.**
My post content have links included, but the links aren't clickable within the posts block.

**Describe the solution you'd like**
All URLs in post content should be converted to clickable links.

**Comment by yssagambit** [comment]
We have decided to stick with the default behavior of WordPress regarding blog post excerpts. If there's a WordPress plugin that adds links to excerpts, that may work.
