### ISSUE TITLE
Blockquote has more Bottom Padding than the Top Padding

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#619]
Blockquote has more Bottom Padding than the Top Padding. When you view your Blockquote on frontend, it has more Bottom padding than Top padding.

![image](https://user-images.githubusercontent.com/51441886/75419548-051a2f00-5971-11ea-97e7-fb565c22c589.png)

One workaround for this is to change the Column Paddings.

**Comment by blankart** [comment]
Closing the issue. Top and bottom padding are now equal by default
