### ISSUE TITLE
Some layout of the CTA is not working properly on IE 11

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#632]
Some layout of the CTA is not working properly on IE 11

ON IE 11
![image](https://user-images.githubusercontent.com/51441886/75856210-d4ce0700-5e2e-11ea-981f-a97f6dbd6303.png)

![image](https://user-images.githubusercontent.com/51441886/75856214-da2b5180-5e2e-11ea-948e-d3742211afe4.png)

**Comment by blankart** [comment]
Already resolved. Closing this issue

**Comment by blankart** [comment]
Reopening the issue. Still now working in IE 11
