### ISSUE TITLE
Make Title Headings selectable

### ISSUE THREAD

**Issue by Daddaaff** [gambitph/Stackable#64]
**Is your feature request related to a problem? Please describe.**
By using fixed headings (e.g. h4 inside the card block) the heading hirachy gets mixed up. 

**Describe the solution you'd like**
Make the heading selectable.

**Describe alternatives you've considered**
Use 'core/heading' instead of a custom one, if that is even possible ...

**Comment by bfintal** [comment]
Hi, can you give an example on how to replicate this?

**Comment by Daddaaff** [comment]
Insert a card block and look at the genertated markup. The title is an h4 tag, which may break the heading hirachy.

**Comment by jrgong420** [comment]
+1 for this

When using the feature box, the feature title is an h2. I would like to use h3 or h4 instead. H2 messes up the TOC

**Comment by bfintal** [comment]
All blocks have a heading tag selector in v2
