### ISSUE TITLE
Block BG doesn't work properly

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#648]
Block BG doesn't work, it just makes the block into full width. 

![ezgif-1-10c8a2bf0485](https://user-images.githubusercontent.com/51441886/76061774-38873a00-5fbf-11ea-9584-70f2f2ad7f33.gif)

This only happens on Backend.

On frontend:
![image](https://user-images.githubusercontent.com/51441886/76389903-5847a500-63a7-11ea-848e-3f9436b79c07.png)

**Comment by bfintal** [comment]
Block alignment when in block bg is turned on doesn't work either.

May be related to #643
