### ISSUE TITLE
Feature Block - Overridden Alignment

### ISSUE THREAD

**Issue by LensDigitalUK** [gambitph/Stackable#65]
If you set the alignment of the text part of the feature block, this is being overridden by the theme styling.

Using the block in the Ascend theme, the text is aligned right but is being overridden by the following CSS from the theme;

`.main:not(.kt-sidebar) .entry-content .alignfull:not(.wp-block-kadence-rowlayout) {
    text-align: center; 
}`

**Comment by LensDigitalUK** [comment]
This also applies to the padding of the block. The Ascend theme is setting it to 0.

**Comment by bfintal** [comment]
@LensDigitalUK It would be best if the CSS of Ascend was adjusted instead since the CSS you pointed out is targeting everything `.alignfull` that's NOT `.wp-block-kadence-rowlayout`
