### ISSUE TITLE
When you lower the Z-Index the block will fade out

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#655]
When you lower the Z-Index the block will fade out

![ezgif-2-5bf664a9bda5](https://user-images.githubusercontent.com/51441886/76390715-deb0b680-63a8-11ea-9b96-b7ee302a3571.gif)

This only happens when you don't have the block background on.

**Comment by blankart** [comment]
Closing this issue since this is how z-index works. Lowing the z-index of an element is one way of hiding an element
