### ISSUE TITLE
Use wp.blockEditor.ColorPaletteControl instead of our own Component

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#671]
We implemented our own ColorPaletteControl since the one in Gutenberg wasn't exposed in the API. Now that https://github.com/WordPress/gutenberg/issues/13018 is resolved, we can now do:

`import { ColorPalleteControl } from '@wordpress/block-editor'`

This only works in WP 5.4+, so we'll need to do backward compatibility for lower versions.

**Comment by ruock** [comment]
Hi @bfintal , thank you for your message.
I'm trying to use ColorPaletteControl with the last Wordpress' version, but I don't see nothing on backend, but nothing is printed. 

What am I doing wrong?

```
const {ColorPaletteControl} = wp.blockEditor;

<ColorPaletteControl
         label={label}
         colors={colors}
         value={value}
/>
```
