### ISSUE TITLE
Content Vertical Align (under the Block Spacing) does not work

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#690]
Content Vertical Align (under the Block Spacing) does not work. It should move the placement of the column container to top, center or bottom.

![ezgif-3-456c11b754c8](https://user-images.githubusercontent.com/51441886/78649158-a80a8500-78ef-11ea-9ac6-53a836b5f840.gif)

**Comment by bfintal** [comment]
Solution: remove content vertical align option
