### ISSUE TITLE
if you've added any block (with block background on and the layout is wide width) inside a Container Block, the text will extend beyond the container

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#711]
if you've added any block (with block background on and the layout is wide width) inside a Container Block, the text will extend beyond the container

steps:
1. Place any Stackable block inside a container
2. Turn on the Block Background
3. Change the layout to Wide Width
4. Preview

Backend:
![image](https://user-images.githubusercontent.com/51441886/84115560-d6781e00-aa60-11ea-9ff2-3b7048365a4c.png)

Frontend:
![image](https://user-images.githubusercontent.com/51441886/84115594-e55ed080-aa60-11ea-9877-7f0abd4ccbd2.png)

**Comment by blankart** [comment]
Already resolved. The text no longer extends beyond the container.
