### ISSUE TITLE
remove the default number in the top and bottom line, it should be empty

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#714]
remove the default number in the top and bottom line

![image](https://user-images.githubusercontent.com/51441886/85120212-8580da80-b255-11ea-878f-e6e38c3cf88e.png)

it should look like this:
![image](https://user-images.githubusercontent.com/51441886/85120291-9f222200-b255-11ea-8c2b-082da8d5febc.png)

**Comment by blankart** [comment]
Closing this issue. All range controls have default values already in WP 5.5.
