### ISSUE TITLE
Load More button is not taking up the whole content width of the block

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#718]
Load More button is not taking up the whole content width of the block

here's the Load More button on 2.6.0:
![ezgif-6-f48e504c7265](https://user-images.githubusercontent.com/51441886/85493691-f0416580-b609-11ea-912f-0e5cb3ce9d88.gif)

here's the Load More button on 2.6.1:
![ezgif-6-c9af8fe14109](https://user-images.githubusercontent.com/51441886/85493763-12d37e80-b60a-11ea-8b5f-3dc2fc43609b.gif)

**Comment by blankart** [comment]
Issue is already resolved.
