### ISSUE TITLE
Stackable Design Library button is missing on WP5.5

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#726]
Stackable Design Library button is missing on WP5.5

WP5.5
![image](https://user-images.githubusercontent.com/51441886/86713369-9781bc00-c050-11ea-9c80-a3a70ba28475.png)

WP5.4
![image](https://user-images.githubusercontent.com/51441886/86713538-c304a680-c050-11ea-88b9-7def7223af56.png)

**Comment by reelism** [comment]
Yep, it's not there.

Any progress?
