### ISSUE TITLE
some icons look bigger

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#728]
some icons look bigger

alignment icon:
![image](https://user-images.githubusercontent.com/51441886/86717685-f9dcbb80-c054-11ea-8bb1-5973e6864b86.png)

Title HTML Tag
![image](https://user-images.githubusercontent.com/51441886/86717885-27c20000-c055-11ea-807a-57ada1680d90.png)

Content Horizontal Align
![image](https://user-images.githubusercontent.com/51441886/86718068-52ac5400-c055-11ea-9672-4e7247116e90.png)

Content Vertical Align
![image](https://user-images.githubusercontent.com/51441886/86718146-6657ba80-c055-11ea-8330-e38b8aaf8e4d.png)

**Comment by yssagambit** [comment]
re-opening this issue.

adding Icon and Icon Shape for the Icon List block
![image](https://user-images.githubusercontent.com/51441886/87630553-f7224a80-c767-11ea-829c-dab8ab46a607.png)

**Comment by blankart** [comment]
Already merged fixes regarding this issue. Closing this issue.
