### ISSUE TITLE
Icon Alignment is not working

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#730]
alignment on Icon tab is not working, but the alignment on General tab is working.

![ezgif-6-59b10000facf](https://user-images.githubusercontent.com/51441886/86728274-e33b6200-c05e-11ea-8537-eebff2a91aa0.gif)

**Comment by bfintal** [comment]
It's because there's no title, so the alignment doesn't have any effect. The solution is to just enable the option when there's a title.

**Comment by yssagambit** [comment]
re-opening this issue. even if you've turned on the Title, Icon Alignment still doesn't work.

![ezgif-6-dccb6474f4b6](https://user-images.githubusercontent.com/51441886/87002087-75707100-c1eb-11ea-9b93-9a456a8ef114.gif)

**Comment by bfintal** [comment]
This should be okay since the icon is bigger than the title. It's aligned left already except that there's no room to move.
