### ISSUE TITLE
SVG file type problem

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#734]
can't upload some SVG file type

![ezgif-6-fba3ba68d0ff](https://user-images.githubusercontent.com/51441886/86755143-fdcc0600-c073-11ea-95ce-32c69fa52a20.gif)

**Comment by bfintal** [comment]
The issue is that some SVGs start with

```xml
<?xml ... ?>
<!--- Generated by -->
<svg>...</svg>
```

We need to strip out the non-svg parts
