### ISSUE TITLE
Default spacing, font size, and font style appear to be different

### ISSUE THREAD

**Issue by blankart** [gambitph/Stackable#736]
Some issues with default padding, font-size, and font-style.

### Accordion Block
All themes have the same issue.
- Title default spacing inconsistent with 5.4
- More font weight in the title
- Larger font
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86877402-6620f300-c119-11ea-89af-91d39665beb2.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86876946-68368200-c118-11ea-8266-6431cdc5969f.png)

### Blockquote 
All themes have the same issue.
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86879728-2577a880-c11e-11ea-85ae-95992f0c6e85.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86879794-48a25800-c11e-11ea-98f3-248795b4cd49.png)

### Count up
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86879906-7ab3ba00-c11e-11ea-9e72-6a91c5199d12.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86879973-9919b580-c11e-11ea-8a04-11ec173b39a8.png)

### Advanced Heading
All themes have the same issue
- DIfferent font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86880158-e7c74f80-c11e-11ea-9137-347f0ea65feb.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86880179-f01f8a80-c11e-11ea-8cd4-efe67c1cda79.png)

### Icon List
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86880327-2bba5480-c11f-11ea-9dc7-ae2b96d31636.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86880338-2eb54500-c11f-11ea-84d3-3b391d122431.png)

###  Posts
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86881101-4e00a200-c120-11ea-8f3a-3e4eee09eba5.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86880685-a08d8e80-c11f-11ea-8ac2-9bdb07cc548c.png)

### Button
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86880886-f6facd00-c11f-11ea-9ca0-78ffea871ae9.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86880916-0548e900-c120-11ea-845c-4b8a2774d57f.png)

### Call to Action
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86881168-6ffa2480-c120-11ea-804a-d949c17e3ce7.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86881201-7d171380-c120-11ea-89f2-f57968a494b2.png)

### Cards
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86881397-d41ce880-c120-11ea-95fd-62758e8d3bc5.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86881407-daab6000-c120-11ea-9269-377f88b442de.png)

### Expand / Show More
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86881611-4ab9e600-c121-11ea-84d6-a67d196aba94.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86881617-4e4d6d00-c121-11ea-9896-8f9e8ac59f66.png)

### Feature Grid
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86881714-80f76580-c121-11ea-87b8-3cfabca425d9.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86881731-89e83700-c121-11ea-9365-d0eebe5e1b9e.png)

### Feature
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86881822-bbf99900-c121-11ea-8654-741d02bffd17.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86881836-c156e380-c121-11ea-9a91-0fec4968dabb.png)

### Header
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86881916-ecd9ce00-c121-11ea-9592-b8f09ea0b80b.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86881929-f3684580-c121-11ea-8370-c6edf64656b8.png)

### Image Box
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86882036-27dc0180-c122-11ea-99b3-b4ea180c6de1.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86882049-2ca0b580-c122-11ea-80c0-6dc7a1d0ba4a.png)

### Notification
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86882130-522dbf00-c122-11ea-8b9f-cd6e75b9d0a2.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86882147-5a85fa00-c122-11ea-9827-347eeb6706f1.png)

### Number Box
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86882235-86a17b00-c122-11ea-9c5c-7be2409d6c6f.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86882247-8903d500-c122-11ea-956e-d87aa10e0bb3.png)

### Pricing Box
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86882309-a6d13a00-c122-11ea-8e30-6852b48c2ec1.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86882337-b18bcf00-c122-11ea-8399-bb5692162ae3.png)

### Team Member
All themes have the same issue
- Different font
- The top offset background color is still white. It does not blend with the new page background color

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86882538-fd3e7880-c122-11ea-8033-3bfe4ab81f66.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86882607-1ba47400-c123-11ea-87b4-d1c3d1749ead.png)

### Testimonial
All themes have the same issue
- Different font 

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86882808-69b97780-c123-11ea-9d43-886d44383be5.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86882848-763dd000-c123-11ea-9c31-1042eafa00ef.png)

### Advanced Text
All themes have the same issue
- Different font

Version 5.4
![image](https://user-images.githubusercontent.com/24480990/86882911-9e2d3380-c123-11ea-9050-6d55b21eae26.png)

Version 5.5
![image](https://user-images.githubusercontent.com/24480990/86882922-a2595100-c123-11ea-8d68-6117ba6d9180.png)

**Comment by bfintal** [comment]
This is possibly theme related and not necessarily a compatibility issue with WordPress 5.5
