### ISSUE TITLE
Top and Bottom Separator appear to have a white background color

### ISSUE THREAD

**Issue by blankart** [gambitph/Stackable#742]
The top and bottom separator do not blend with the new background color in WP 5.5. See screenshot below:

![image](https://user-images.githubusercontent.com/24480990/86888571-f7e62b80-c12c-11ea-82ab-bfbf02fd618c.png)

![image](https://user-images.githubusercontent.com/24480990/86888762-4eec0080-c12d-11ea-944a-8b2d40590342.png)

**Comment by yssagambit** [comment]
the default color of our separators are white. and not transparent. so this is the expected behavior,
