### ISSUE TITLE
Posts Blocks: Specify Post ID

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#76]
https://wordpress.org/support/topic/post-blocks-on-home-page/

**Is your feature request related to a problem? Please describe.**
I want my Posts Block to specify a specific ID:
1. Specify specific post ID as a starting point for date and recent posts.
2. Specify multiple IDs for Posts

**Describe the solution you'd like**
An additional field to specify the post IDs

**Comment by jrgong420** [comment]
+1 for this! would be great if you could implement it
