### ISSUE TITLE
title font size changing unit on tablet and mobile not working

### ISSUE THREAD

**Issue by blankart** [gambitph/Stackable#770]
Changing unit from PX to EM or EM to PX is not working.

![image](https://user-images.githubusercontent.com/24480990/87640812-dcf16800-c779-11ea-9a2f-56846c950734.png)

**Comment by bfintal** [comment]
Changing the unit should only have an effect if there's a numeric value in the field

**Comment by blankart** [comment]
Resolved. Numeric value in the field is required to make it work
