### ISSUE TITLE
Click that Opens Modal

### ISSUE THREAD

**Issue by jebrennan** [gambitph/Stackable#78]
Click on button leads to a modal/pop up with many buttons, all in the same style.

I don't want a cluster of buttons always in view. I want a simple layout with one button that provides details when the user needs it. 
I'd like a button that, when pressed, presents a modal (or other element) that has related buttons. Selecting a secondary button follows a link, or has other standard button behavior.  
The modal closes when a button within it is selected. Modal should also have standard dismiss X & action (Esc).
The problem I'm trying to solve: 
Web site for author whose books can be purchased at a number of places. Would like a <buy> button that then has (a grid of) buttons to <amazon> <powells> <bookStore3> in a modal. 
Modal should have the standard set of Stackable options: background color/image selection, text display options 

I imagine this to be a versatile implementation: A click opens a Stackable Container block (however that's contained -a page or post?) that has the look of a modal. The click can originate from a button, image, <More...> link; anywhere that a link can be placed can lead to a modal. That stand-alone container can be used in a variety of ways: Registration/sign-up forms, showing options/choices, lightboxes, etc. Users will find ways to use it, especially in a familiar (Stackable Block) interface. 

Options like the following are:
1. Not as nice looking or consistently styled as Stackable blocks used together. [Popup anything on click](http://demo.wponlinesupport.com/popup-anything-on-click-demo/)
2. Too complex and too powerful to use on a simple project [Popup Maker – Popup Forms, Optins & More](https://wppopupmaker.com/features/)  [ Popup Builder – Responsive WordPress Pop up – Subscription & Newsletter ](https://popup-builder.com/)
3. Too specialized

**Comment by yssagambit** [comment]
let's continue the discussion in #316
