### ISSUE TITLE
Can't type your own value

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#788]
This happens when you try to add your own value:
![ezgif-7-72aed6dec7f5](https://user-images.githubusercontent.com/51441886/88613652-86acef00-d0c0-11ea-911c-d97fb2f02352.gif)

This applies to all range controls.

**Comment by blankart** [comment]
Related to: https://github.com/WordPress/gutenberg/issues/24264

**Comment by blankart** [comment]
Issue is already closed in Gutenberg Repository. Already resolved.
