### ISSUE TITLE
Some Blocks doesn't support grid column in IE11

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#79]
**Describe the bug**
Some blocks that have a number of columns doesn't show in columns at IE11. Instead, they show up vertically.

**To Reproduce**
1.  Add 2 or more columns of these blocks: Pricing Box, Number Box, Image Box, Testimonial or Team Member 
2. View in IE11, they'll show up vertically.

**Expected behavior**
They should show up in columns accordingly.

**Screenshots**
![image](https://user-images.githubusercontent.com/11436202/54912513-baf02880-4f2b-11e9-8a9a-edcee046f9be.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: IE11

**Comment by yssagambit** [comment]
duplicate issue #128
