### ISSUE TITLE
Columns 7 and 8 retain when changing the layout from Grid to Plain

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#793]
Steps to replicate the issue:
1. Add Advanced Columns & Grid block
2. Change the layout to Grid
3. Add Columns, make it 8
4. Change the layout to Plain

WP5.5
![ezgif-2-5577e7d8b833](https://user-images.githubusercontent.com/51441886/88778386-0b7c3380-d1bb-11ea-9354-024330a75213.gif)

WP5.4
![ezgif-2-da88246cb351](https://user-images.githubusercontent.com/51441886/88778700-6ada4380-d1bb-11ea-8374-8d5a06622ae4.gif)

**Comment by bfintal** [comment]
Might be connected to #792

**Comment by yssagambit** [comment]
Still happening on latest build v2.9.0-dev1:

![ezgif-6-ef9089f2e48b](https://user-images.githubusercontent.com/51441886/89375444-3406af00-d720-11ea-942e-a4b8bd33c555.gif)

**Comment by yssagambit** [comment]
reopening this issue, still happening:
![ezgif-7-dcd48405bbd3](https://user-images.githubusercontent.com/51441886/89405737-9f677580-d74e-11ea-983f-e00ff319dc83.gif)
