### ISSUE TITLE
The block encountered an error when highlighting blocks

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#794]
- [ ] The block will error out when you highlight block and there are different blocks in your block editor

Steps on how to replicate:
1. Add blocks in your block editor
2. Highlight/select multiple blocks
3. When you highlight blocks and it detects that there's another block selected, some block will error out

When you highlight the same blocks:
![ezgif-7-a4e72efabb4c](https://user-images.githubusercontent.com/51441886/88891153-3c20a380-d275-11ea-88ba-02aa2fa351eb.gif)

When you highlight block with different blocks:
![ezgif-7-7044b5c6d570](https://user-images.githubusercontent.com/51441886/88890983-fb288f00-d274-11ea-8880-6378840459d5.gif)

- [ ] The lower block will error out when you use CTRL + A to select all then click the 2nd or 3rd block

Steps on how to replicate:
1. Add blocks in your block editor
2. use CTRL + A to select all blocks
3. Click the 2nd or 3rd block. Not the 1st block, the block will not error out if you click on the 1st block.

When clicking the 1st block after you CTRL + A:
![nCHTLcE3wH](https://user-images.githubusercontent.com/51441886/88899163-4e540f00-d280-11ea-8e28-c079d7bbf9bf.gif)

When clicking the 2nd or 3rd block after you CTRL + A:
![pl2A97XC9H](https://user-images.githubusercontent.com/51441886/88900374-e1da0f80-d281-11ea-8c11-12ae1fa6f737.gif)

![GF9rm4BHT6](https://user-images.githubusercontent.com/51441886/88900720-63ca3880-d282-11ea-8590-eac8d9eca32f.gif)

**Comment by bfintal** [comment]
There is a new version of 5.5 available. Please re-test this with the new 5.5-RC1
