### ISSUE TITLE
Getting a PHP error

### ISSUE THREAD

**Issue by The-Web-Mechanic** [gambitph/Stackable#798]
I'm running Query Monitor on my client's site and am getting the following error.

register_setting was called incorrectly. When registering an "array" setting to show in the REST API, you must specify the schema for each array item in "show_in_rest.schema.items". Please see Debugging in WordPress for more information. (This message was added in version 5.4.0.)

    wp-includes/functions.php:5167
    register_setting()
    wp-content/plugins/stackable-ultimate-gutenberg-blocks-premium/pro__premium_only/src/editor-mode.php:70
    Stackable_Premium_Editor_Mode->register_editor_mode_settings()
    wp-includes/class-wp-hook.php:287
    do_action('init')
    wp-settings.php:540

I'm getting tons of that first error message in my wp-debug.log

**Comment by bfintal** [comment]
This has been fixed in v2.9.1. Thanks!
