### ISSUE TITLE
Align on Divider Block is not working on Tablet/Mobile Preview Mode

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#810]
Align on Divider Block is not working on Tablet/Mobile Preview Mode

![ezgif-6-30c311394b36](https://user-images.githubusercontent.com/51441886/89284443-601f2300-d681-11ea-928c-e81e9b9388d3.gif)

**Comment by yssagambit** [comment]
Still happening on latest build v2.9.0-dev1

**Comment by blankart** [comment]
This issue also exists in Wordpress 5.4
