### ISSUE TITLE
When you switch between designs on Mobile Preview Mode, sometimes the block will error out

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#814]
Steps:
1. Add any block that has pre-set design
2. Switch to Mobile Preview Mode
3. Switch between designs

![ezgif-6-aa58b84253b6](https://user-images.githubusercontent.com/51441886/89495514-05093f80-d7eb-11ea-8caa-447f09e0c77c.gif)

**Comment by blankart** [comment]
Tested by @yssagambit. Fixed.
