### ISSUE TITLE
Blocks that you've recently added will error out if there are already blocks that error out on your block editor

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#815]
I also noticed, if there's a block that has an error on your page, then if you add another block while on Mobile Preview Mode, the block that you've recently added will error out too. This only happens if you are in Mobile Preview Mode.

![ezgif-6-37d447e37da0](https://user-images.githubusercontent.com/51441886/89495807-a4c6cd80-d7eb-11ea-96f6-41e6b0199d2f.gif)

**Comment by blankart** [comment]
Tested by @yssagambit . Fixed
