### ISSUE TITLE
Accordion Block: Accordion is leaving "ghost" links

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#82]
https://wordpress.org/support/topic/accordion-content-still-live-blocking-other-content-when-closed/

**Describe the bug**
Closed accordions with links leave a "ghost" link on the location where the link is when opened.

**To Reproduce**
1. Create an accordion with a link
2. Open the page and hover on the area where the link is (while accordion is closed) 

**Expected behavior**
It shouldn't show any "ghost links" when the accordion is closed.

**Comment by bfintal** [comment]
Previously fixed
