### ISSUE TITLE
The Number isn't centered on Mobile and Tablet when you change the Shape Size into a higher value 

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#829]
This is happening on Backend and Frontend.

On Desktop Preview Mode:
![image](https://user-images.githubusercontent.com/51441886/90222459-aa9d5e00-de3e-11ea-85e2-40a474c297fb.png)

On Tablet Preview Mode:
![image](https://user-images.githubusercontent.com/51441886/90222495-bdb02e00-de3e-11ea-9807-1572cfd6d513.png)

On Mobile Preview Mode:
![image](https://user-images.githubusercontent.com/51441886/90222518-c86ac300-de3e-11ea-91c7-b80b390c3e41.png)

**Comment by bfintal** [comment]
Issue introduced by #789

**Comment by yssagambit** [comment]
already fix on stackable-v2.10.0-responsive-fix-v8
