### ISSUE TITLE
Block Auto-height for unpopulated content

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#83]
https://wordpress.org/support/topic/equalising-card-height/

**Is your feature request related to a problem? Please describe.**
If I don't add a certain content in a block, I want it to be unpopulated but still has the same height as how it should. This is important if I use multiple column blocks like number box, card (in columns), etc. It would look better if they can be unpopulated but retains the same even "look".

**Describe the solution you'd like**
Unpopulated fields should still leave space for extra height, while an extra X button should remove the content instead.

**Comment by bfintal** [comment]
The new advanced column controls have this feature
