### ISSUE TITLE
Blocksy Icon List icon color doesn't apply

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#835]
The main cause is that css custom properties don't appear to work as expected when included in an SVG that's used as a CSS image URL. The icon list block uses this for icons (it's used to style the li:before):

```css
background-image: url('data:image/svg+xml;utf8,<svg viewBox="0 0 190 190" xmlns="http://www.w3.org/2000/svg" style="fill:var(--paletteColor1)"><path d="M95.4 6.3l29.2 58 64.2 9.9-46.2 45.7 10.5 64.1-57.7-29.8L37.6 184l10.5-64.1L2 74.2l64.2-9.9z"></path></svg>')
```

The `var(--paletteColor1)` that's being pulled from Blocksy doesn't take effect, so the icon remains the default color.

I think what's happening here is that the custom property might have a scope that's outside the current document, so it's not detecting the definitions for `--paletteColor1` in the document. This is just a hunch.

I think that can be the reason why, doing `var(--paletteColor1, blue)` and `style="--paletteColor1: red; fill: var(--paletteColor1)"` both work.

Suggestion to Blocksy: instead of the color picker just returning `var(--paletteColor1)` it would now include the fallback color `var(--paletteColor1, #abcdef)`

**Comment by blankart** [comment]
Already resolved. Fallback values are now appended to blocksy's global css variables.
