### ISSUE TITLE
Accordion block: title cannot be edited, invalid block content error

### ISSUE THREAD

**Issue by voneff** [gambitph/Stackable#836]
Hi there, I encountered this bug today:

**Describe the bug**
The accordion title cannot be edited, field turns blank. When I try to edit the content via the block HTML editor, it throws an  invalid content error.

**To Reproduce**
1. Go to Gutenberg Editor
2. Add new accordion block
3. Try to edit the title.

**Expected behavior**
I would like to edit the title.

**Screenshots**
Here is a quick recording of the behavior of the block:
https://share.getcloudapp.com/YEuoX8QO

Here is a screenshot from the invalid block content:
https://share.getcloudapp.com/yAub6ojY

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Browser Version: 79.0

**WordPress:**
WP 5.5.
Stackable current version
PHP 7,3
TwentyTwenty Theme

I'd really appreciate if you could take a look at this!
Let me know if you need more info!

**Comment by bfintal** [comment]
@voneff do you have any other plugins installed? Based from the screenshot you gave it seems like the contents are being formatted.

**Comment by voneff** [comment]
Hi Benjamin, thank you for picking this up. 

I tried again, with all plugins (but Stackable) deactivated and with the TwentyTwenty Standard theme active.

The accordion block still behaves the same as described above.

Please see the screen recording:
https://share.getcloudapp.com/wbu7DxPJ

I guess you did not get any reports like this? It is quite weird.

**Comment by bfintal** [comment]
@voneff This is the first report of this. This is very peculiar, it looks like you only have the bare minimum in your site as well.

I tried matching everything I could see in your video (did it have audio? I couldn't hear anything), even changing the language to German, but it still behaved normally.

What do you see in the browser's console? Can you paste here any errors? Or is there any other setting that's in there that might affect this? Or perhaps a browser extension?

**Comment by voneff** [comment]
@bfintal Hi Benjamin, I am sorry for the late reply. It's pretty embarrassing but the error really was caused by a browser extension. (The culprint was "Language Tool", as spell check error similar to Grammarly.) So, never mind, really sorry to bother you with this!
