### ISSUE TITLE
Icon Color doesn't change when you upload your own SVG.

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#838]
Icon Color doesn't change when you upload your own SVG.

On Icon List Block:
![ezgif-7-791883710734](https://user-images.githubusercontent.com/51441886/90748967-6a8a1f80-e305-11ea-8e62-95f6d6e93b18.gif)

On Icon Block:
![ezgif-7-9c5584264569](https://user-images.githubusercontent.com/51441886/90748892-56462280-e305-11ea-8fe3-8cee9219b630.gif)

**Comment by blankart** [comment]
Fixed on PR #840
