### ISSUE TITLE
Separators: Scroll bars appear when the height is changed

### ISSUE THREAD

**Issue by pjadolfo** [gambitph/Stackable#84]
Adjusted the height of the separators 

1. Create Container > Add block and text inside > Add button below
2. Add separator before/after the container block
3. Adjust the height and padding to create the diamond / hexagon effect

![Screen Shot 2019-03-29 at 12 15 53 PM](https://user-images.githubusercontent.com/46951551/55209333-f5eca780-521c-11e9-87ec-5deb21bcea8b.jpg)

Desktop
 - OS: MacOS
 - Browser: Chrome
 - Browser Version: 73.0.3683.86 (Official Build) (64-bit)

**Comment by bfintal** [comment]
Fixed by e05d9019c1a1be1b6a72045488763785dcee3d67
