### ISSUE TITLE
How to adjust Stackable's breakpoints for mobile/tablet/desktop, etc.

### ISSUE THREAD

**Issue by ErinPo** [gambitph/Stackable#858]
I would like to make the stackable breakpoints match those of my theme.

**Comment by bfintal** [comment]
@ErinPo This is one of the things we're currently exploring, but this will be further down the line.

There is currently some very basic theme integration here: https://docs.wpstackable.com/resources/theme-integration-guide

I'm closing this since we'll really do this :)
