### ISSUE TITLE
broken view using image box 15 after duplication

### ISSUE THREAD

**Issue by horatiov** [gambitph/Stackable#859]
go to: http://training-teaching.online/

I use the image box 15 from design library
Then I duplicate it.
The result you can see in the attached files.
![broken image box 15 after duplication-2](https://user-images.githubusercontent.com/70438927/91637648-436cd580-ea0a-11ea-9aa6-04fe4de32a4c.jpg)

**Describe the bug**

**To Reproduce**
1. Add new page
2. Click on Add image box no 15 from design library
3. clone it
4. view site

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Browser Version: [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS 12.0]
 - Browser: [e.g. stock browser, Safari, Chrome]
 - Browser Version: [e.g. 22]

**Comment by bfintal** [comment]
@horatiov can you set the block centered width?

Sorry the image is a bit hard to understand, what does the page look like prior to adding it?

**Comment by horatiov** [comment]
I add a picture of the editing mode - 
![editing view](https://user-images.githubusercontent.com/70438927/91828124-05f18d80-ec40-11ea-8192-631c769b6cae.jpg) I easily can reproduce this bug, just choosing image box 15, then duplicate (as described above)

**Comment by horatiov** [comment]
And the result is
![live view](https://user-images.githubusercontent.com/70438927/91828529-8c0dd400-ec40-11ea-89ba-976c8174aab2.jpg)

**Comment by bfintal** [comment]
We sent you a reply in your support ticket. It seems like some HTML is being removed from the page in the frontend, and it looks like each image box is getting displayed inside each other. 

Do you have any plugins or is there a theme function that can possibly do that?

**Comment by horatiov** [comment]
Is it possible that the classic editor (i just deleted it) leads to trouble? I did not have this issue before...

**Comment by bfintal** [comment]
@horatiov found the issue, can you remove the formatting of the titles in the image box block for now? The design 15 has italics on them. Removing that should fix it.

I'll close this issue since I've already added a fix for this that will be included in an update soon.

Fixed by 26176f376e159eb5cf41f8ce4f253122e76c324f
