### ISSUE TITLE
Pages block

### ISSUE THREAD

**Issue by lutrov** [gambitph/Stackable#86]
I have already raised this as a [question](https://wordpress.org/support/topic/page-blocks/) in the Wordpress support forum but I thought it would be better to post here.

Are there any plans to develop a pages block? It could work in a similar fashion to the posts block, but we could make use of the built-in WordPress feature that is parent/child attributes. For instance, show all child pages of the page we’re on now.

**Comment by yssagambit** [comment]
This might be a good idea, but the feature may be too specific to a few use cases. In V2, you can already exclude pages or display specific pages using a Post Block, so its possible to use that instead.
