### ISSUE TITLE
Container Preview breaks!

### ISSUE THREAD

**Issue by The-Web-Mechanic** [gambitph/Stackable#861]
Hi!
I'm using the latest Stackable Pro, WP 5.5.1

If I select a Stackable container and go to the Block/Advanced settings and select either tablet or phone size, the block resizes appropriately, but if I try to make any adjustments, the block disappears and I get the following message...

This block has encountered an error and cannot be previewed. All of the Container Block adjustments disappear as well.

When in Desktop size, everything works well.

I hope this can be fixed quickly... I'm kind of dead in the water on my site until this is resolved.

**Comment by bfintal** [comment]
@The-Web-Mechanic Would you be able to post here your page content? What does your browser console say when you start editing tablet/mobile values?

**Comment by The-Web-Mechanic** [comment]
When I click on either the tablet or mobile I get many of these errors in the browser console...

![image](https://user-images.githubusercontent.com/3058054/92177619-17809400-edfe-11ea-890d-9b914f82636b.png)

When I have selected tablet or mobile and go to make an adjustment (this is when the display borques) I get many more of the above and a few of the below...

![image](https://user-images.githubusercontent.com/3058054/92178000-d5a41d80-edfe-11ea-8308-e24f1b4ebc85.png)

I'll attach the html for the page as a txt file.

In the images and the txt file I have obscured the actual site url.

Hope this helps!
[container-preview-breaks.txt](https://github.com/gambitph/Stackable/files/5171666/container-preview-breaks.txt)

**Comment by The-Web-Mechanic** [comment]
I have tried this on two other sites with different themes and plugins... Same problem. I've tried disabling plugins... Problem persists.

This is pretty major I think!!

**Comment by The-Web-Mechanic** [comment]
The problem goes away if I downgrade WordPress to v.5.4.2

**Comment by bfintal** [comment]
I see, thanks for the report. The error means that the editor CSS files for Stackable is hosted in a remote location, so it's encountering a cross-origin error.

I've added a fix for this. The error will go away, but as long as the CSS files are hosted externally, responsive editing of Stackable blocks will be disabled in Gutenberg.

**Comment by bfintal** [comment]
Fixed by 59463947470b715162c606e99843522e9f4e8709

**Comment by The-Web-Mechanic** [comment]
Hi!
Thank you for the fix!  But I have to ask... maybe request that the css files be hosted locally or at least maybe cached locally so that external calls don't need to be made. While I'm sure that they can be delivered rapidly... There are always times that for some reason they aren't.
There are caching plugins that can do that, but frequently they do not cache the WP admin so as not to interfere with page builder/ Gutenberg Blocks.

As an example... Google Fonts...  Usually they load very fast... But I have seen times when they can slow a site load time by seconds
