### ISSUE TITLE
Unable to choose these options. These options are always at default.

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#863]
Unable to choose these options:
- [ ] Weight (Under Typography)
- [ ] Transform (Under Typography)
- [ ] Mix Blend Mode (Under Separator Layer 2)

When you click them the selection box closes and will not save the one that you've chosen. This issue applies to all themes all blocks that have these options.

Sample video screenshots of what's happening:

Weight
![ezgif-2-6a84f14fc0d6](https://user-images.githubusercontent.com/51441886/92086087-47c73300-edfc-11ea-8dcb-d0dd21304e87.gif)

Transform
![ezgif-2-a56476ce3c70](https://user-images.githubusercontent.com/51441886/92086321-9c6aae00-edfc-11ea-9104-deac4f9deec2.gif)

Mix Blend Mode
![ezgif-2-afda65ae5926](https://user-images.githubusercontent.com/51441886/92086561-e9e71b00-edfc-11ea-9d5d-3c89e27b7b67.gif)

**Comment by yssagambit** [comment]
You'll also encounter this issue in Global Typography Settings

**Comment by bfintal** [comment]
Fixed, this was a mouse detection issue in Firefox
