### ISSUE TITLE
Global Typography is not working on frontend

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#866]
Global Typography is not working on frontend

Backend:
![image](https://user-images.githubusercontent.com/51441886/92371038-b1fa1380-f12d-11ea-9e25-e1803b4a0d10.png)

Frontend:
![image](https://user-images.githubusercontent.com/51441886/92371094-c3dbb680-f12d-11ea-86f2-4c9eb5bcd518.png)

**Comment by yssagambit** [comment]
need to turn on "Force Typography Styles" to apply the changes on frontend

**Comment by bfintal** [comment]
Force Typography should be the last resort. For TwentyTwenty and other popular themes, this shouldn't be required.
