### ISSUE TITLE
ImageBox Bug

### ISSUE THREAD

**Issue by jgabrielccmachado** [gambitph/Stackable#87]
When using Image Box, images doesn’t appear on the same line. Imagine you choose 4 columns, it shows 3 images in one line and the last image on the line below.

Example Link: http://www.dev.isasensing.com/teste/

Thanks

**Comment by Gambit-Alyssa** [comment]
Hi @jgabrielccmachado,

Thanks for showing us your site, though the site shows all 4 image boxes in the same line. Here's a screenshot of how it looks like in our end:
![image](https://user-images.githubusercontent.com/11436202/55954726-0cb9e200-5c92-11e9-91d7-1d19d7ffa812.png)

Is the problem still happening? We also tried replicating this in our sandbox, but it doesn't happen there. It's possible that the problem only happens in your end. It could be from your caching (please clear your browser, caching plugin and Cloudflare if you have one) or it may be happening in a particular browser, platform and screen size.

We tested this with Chrome, Firefox and EDGE for Windows so far and it's working well.
