### ISSUE TITLE
when you added colors in Kadence Blocks, this color shouldn't be removed on Stackable Blocks

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#884]
add a lock on the colors that are added with other block libraries

This is from kadence blocks:
![image](https://user-images.githubusercontent.com/51441886/92847931-44dfca00-f41c-11ea-8e69-c4d710c40c9c.png)

**Comment by bfintal** [comment]
Not sure whether we can do this since this means we'll need to have deep knowledge of how the other plugins work
