### ISSUE TITLE
Block error on Feature block v.2.12.1

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#935]
**Describe the bug**
There is a block error showing on Feature block when plugin v2.11.4 is upgraded to v2.12.1

**To Reproduce**
1. Activate the Stackable version 2.11.4 
2. Add a Feature block and change the following settings:
- [ ]  Layout design: Feature 17
- [ ]  Layout: Half Background
- [ ]  Style > General > Image Column Width = 34
- [ ]  General > Border radius = 0; Shadow/Outline = 3
- [ ]  Background > Background Color opacity = 1.0
- [ ]  Spacing > Title=16; Description=16; Button=0
- [ ]  Image > Size = Large; BG Image Position=Default; BG Image Repeat=Default; BG Image Size=Default
- [ ]  Title > H2 heading; Size=46
- [ ]  Title > Typography > Size=46; Weight=Bold; Transform=Uppercase; Line-Height=1.5; Letter Spacing=0
- [ ]  Description > Typography > Size=21; Line-height=1.5; Letter Spacing=0
- [ ]  Button > Ghost, Button Color=#313131; Hover Opacity=0.8
- [ ]  Button > Typography > Size=21; Weight=Default; Transform=Uppercase; Letter Spacing=0
- [ ]  Button > Size=Normal; Border radius=0; Vertical Padding=8; Horizontal padd=26; Border width=2; Opacity=1.0
- [ ]  Button > Adv Icon Settings > Icon Position=Right; Icon Spacing=16
- [ ]  Block background > BG color=Black; Background Media Tint Strength=7
- [ ]  Block background > Adv. Background Image Settings > Default Default Default, Image Blend Mode=None
**No top & bottom separator**
- [ ]  Advanced > General > Opacity=1.0; Z-index=1
- [ ]  Advanced > Block Spacing > Min Block Height=700; Max Content width=100; Content Horizontal Align=Right
- [ ]  Advanced > Block Spacing > Block Margins> Down=35
- [ ]  Advanced > Block Spacing > Block Paddings> Right=100; Left=35

3. Update the settings
4. Update to version 2.12.1
5. Open the Feature block and see the block error

**Screenshots**
![FEATURE BLOCK ERROR](https://user-images.githubusercontent.com/28699204/99355076-9b68f900-28e2-11eb-9616-376b65d65521.PNG)

**Comment by blankart** [comment]
Old attribute error, will be resolved by the revamped design library
