### ISSUE TITLE
Posts Block: Support Custom Post Types

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#94]
https://wordpress.org/support/topic/custom-post-types-fields-2/

**Is your feature request related to a problem? Please describe.**
Allow Custom Post Type selection for Posts Blocks

**Describe the solution you'd like**
Add a selection (checkboxes) for Custom Post Type

**Comment by christinablust** [comment]
Came here specifically to request this. We use a lot of Custom Post Types and being able to use the Post block for them would be very helpful.
