### ISSUE TITLE
Dotted border creates an overlapped solid border

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#941]
Choosing dotted border for containers with a border width value of 3, creates an overlapped solid border.

1. Add a Card block
2. Choose the **dotted border**
3. Set border width = 3

_This happens only when you choose the value 3 for border width_
_Applies to all blocks with border options_

![image](https://user-images.githubusercontent.com/28699204/99790125-9fa14a80-2b5e-11eb-8bd9-45081d5e2640.png)

**Comment by bfintal** [comment]
This seems to be an odd browser issue. Only happens in Elaine's browser at 100% zoom level. When zoomed in or out, the dots begin to show again.
