### ISSUE TITLE
Posts block cannot be viewed on back end

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#970]
1. Add a few posts on your website
2. Create a new page on your website
3. Add a posts block - see bug

![image](https://user-images.githubusercontent.com/28699204/100823418-26272780-348f-11eb-91dd-50a8baa49e9f.png)

Wordpress Version: 5.6 RC2
Stackable Version: 2.13.0 dev-3

**Comment by blankart** [comment]
Are the blog posts showing in the frontend?

**Comment by legaspielaine** [comment]
@blankart Yes, it shows in the frontend

**Comment by blankart** [comment]
> @blankart Yes, it shows in the frontend

Okay great! Thank you for the info

**Comment by blankart** [comment]
Hi @legaspielaine. Upon checking, the blog posts block is working fine in my Local

![image](https://user-images.githubusercontent.com/24480990/100955870-4e2b8f00-3552-11eb-91a5-302005a94c13.png)

What WordPress version are you using? Any third plugins installed?

**Comment by legaspielaine** [comment]
> Hi @legaspielaine. Upon checking, the blog posts block is working fine in my Local
> 
> ![image](https://user-images.githubusercontent.com/24480990/100955870-4e2b8f00-3552-11eb-91a5-302005a94c13.png)
> 
> What WordPress version are you using? Any third plugins installed?

This is in the version 5.6 of WP. When adding a new posts block, it shows "no posts found"
