### ISSUE TITLE
layout picker reopens on upgrade

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#977]
if you upgrade to the latest build (v2.13.0 dev-5), the layout picker reopens on previously created blocks

1. upgrade to v2.13.0 dev5
2. Open a previously created page to edit
3. update the page and refresh
4. see bug

![image](https://user-images.githubusercontent.com/28699204/100858426-ed0ba900-34c8-11eb-8aed-2fcbc2abe497.png)

Check all blocks -

**Comment by blankart** [comment]
Let's close this issue for now.
