### ISSUE TITLE
Fixed Background stretching the image when you scroll

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#98]
**Describe the bug**
Adding fixed backgrounds on blocks (such as container and header blocks) makes the image look warped (the image stretches) upon scrolling. The warping looks more obvious when the block is scrolled to the lower part of your screen.

**To Reproduce**
1. Create a Container or Header Block
2. Add a background image and set it as Fixed Background
3. Scroll through the background

**Expected behavior**
The background should appear nicely and smoothly instead of warping the portions while scrolling.

**Comment by bfintal** [comment]
I think this might be a Chrome issue since the image itself is warping and there are no hackish css/js used, just plain `background-attachment: fixed`
