### ISSUE TITLE
Block paddings bug in back end

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#987]
![block-padd](https://user-images.githubusercontent.com/28699204/101129680-02a1df80-363d-11eb-9b39-17a25de32303.gif)

1. Add a call to action block
2. In block designs, select "Chic call to action"
3. go to Advanced > Block spacing > Block paddings
4. edit the right & left _Block paddings_, See bug (em & %)

WP 5.6 RC-3

**Comment by legaspielaine** [comment]
Similar issue:
Icon List > Aspire Icon List
Style > List Text > Size

![image](https://user-images.githubusercontent.com/28699204/101139729-e9a12a80-364c-11eb-9b54-8d714ed90660.png)

@blankart

**Comment by blankart** [comment]
Reopening the issue, accidentally linked the wrong PR

**Comment by legaspielaine** [comment]
Icon block:

Style > Spacing > Paddings (px, em & %)

![image](https://user-images.githubusercontent.com/28699204/101153201-13634d00-365f-11eb-93e7-37ec5d930e60.png)

**Comment by bfintal** [comment]
so is it only when you force the area to be squeezed and the content has no room?

**Comment by legaspielaine** [comment]
> so is it only when you force the area to be squeezed and the content has no room?

It also happens on Icon List - when changing the List Text Size. I cross-checked the issues here with wp5.5 and it does not happen. (Only happens on 5.6)

**Comment by blankart** [comment]
It seems like this is a gutenberg issue. Other non-stackable blocks with block paddings control (% unit) offset the inspector to the right.
