### ISSUE TITLE
Desktop view redirects to top of the page

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#991]
Editing a block which is in the middle of the page, when I switch between mobile and tablet view, the screen is still focused on the blog I am editing but when I switch back to desktop view the page goes to the top and I have to scroll back down to see my block

1. open a previously created page
2. edit a block in the middle of the page
3. switch view to Tablet (Preview > Tablet)
4. switch view to Mobile (Preview > Mobile)
5. then switch view to Desktop (Preview > Desktop)
The editor brings you to the top of the page (in desktop view) instead of the current block being edited.

_report from notion page_

**Comment by bfintal** [comment]
I don't think we need to fix this since it's a Gutenberg issue.

Can you check whether you have Stackable disabled, and the same issue still exists when editing other blocks? If the issue is still there, let's close this.

**Comment by legaspielaine** [comment]
Same issue persists when Stackable is disabled. Closing this issue
