### ISSUE TITLE
need to scroll when opening a panel on the inspector

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#993]
clicked the bottom separator panel but it does not automatically show, you have to scroll down afterwards to see. 

1. add an icon list block
2. go to style > click the bottom separator
the panel opens but you still need to scroll down further to see the settings

automatically display on the inspector view the panel that I just opened

_report from notion page_

**Comment by bfintal** [comment]
Gutenberg related, no need to fix this. Closing this
