### ISSUE TITLE
Button design does not apply

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#995]
Browser: Firefox
![image](https://user-images.githubusercontent.com/28699204/101156382-78b93d00-3663-11eb-9a60-b0807a02ba92.png)

1. Add a button
2. Style > Button > Design > change to "ghost" "plain" "link"
the styles does not apply

**Comment by bfintal** [comment]
I can't replicate this. even if I use Twenty Twenty in my local

**Comment by legaspielaine** [comment]
> I can't replicate this. even if I use Twenty Twenty in my local

I cannot reproduce this again, it works as it should now. We can close this issue
